INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21250001', '部品B1', '部品B1', '30', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21250002', '部品B2', '部品B2', '60', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21250003', '部品B3', '部品B3', '100', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21250004', '部品B4', '部品B4', '170', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21250005', '部品B5', '部品B5', '200', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21250006', '部品B6', '部品B6', '230', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21250007', '部品B7', '部品B7', '250', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21250008', '部品B8', '部品B8', '270', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21250009', '部品B9', '部品B9', '300', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21250010', '部品B10', '部品B10', '320', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21250011', '部品B11', '部品B11', '350', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21250012', '部品B12', '部品B12', '370', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21250014', '部品B14', '部品B14', '390', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21250015', '部品B15', '部品B15', '590', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21250016', '部品B16', '部品B16', '610', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21250017', '部品B17', '部品B17', '630', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21250018', '部品B18', '部品B18', '670', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21250019', '部品B19', '部品B19', '690', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21250020', '部品B20', '部品B20', '730', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21250021', '部品B21', '部品B21', '780', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21250022', '部品B22', '部品B22', '800', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21250023', '部品B23', '部品B23', '820', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21250024', '部品B24', '部品B24', '840', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21250025', '部品B25', '部品B25', '870', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21250026', '部品B26', '部品B26', '900', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21250027', '部品B27', '部品B27', '930', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21250028', '部品B28', '部品B28', '950', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21250029', '部品B29', '部品B29', '980', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21250030', '部品B30', '部品B30', '1000', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21250031', '部品B31', '部品B31', '1040', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21250032', '部品B32', '部品B32', '1060', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21250033', '部品B33', '部品B33', '1080', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21250034', '部品B34', '部品B34', '1120', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21250035', '部品B35', '部品B35', '1160', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212500011', '控制柜', '控制柜', '30', '0', '0', 'Z21250001', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212500012', '马达', '马达', '40', '0', '0', 'Z21250001', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212500021', '限速器', '限速器', '60', '0', '0', 'Z21250002', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212500022', '反绳轮', '反绳轮', '70', '0', '0', 'Z21250002', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212500023', '涨紧轮', '涨紧轮', '80', '0', '0', 'Z21250002', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212500061', 'PG', 'PG', '230', '0', '0', 'Z21250006', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212500071', '马达', '马达', '250', '0', '0', 'Z21250007', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212500111', '制动器', '制动器', '350', '0', '0', 'Z21250011', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212500121', '控制柜', '控制柜', '370', '0', '0', 'Z21250012', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212500191', '轿厢滚轮导靴', '轿厢滚轮导靴', '690', '0', '0', 'Z21250019', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212500192', '对重滚轮导靴', '对重滚轮导靴', '700', '0', '0', 'Z21250019', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212500211', '轿门', '轿门', '780', '0', '0', 'Z21250021', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212500212', '轿门', '轿门', '790', '0', '0', 'Z21250021', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212500221', '轿门', '轿门', '800', '0', '0', 'Z21250022', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212500222', '厅门', '厅门', '810', '0', '0', 'Z21250022', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212500231', '轿门', '轿门', '820', '0', '0', 'Z21250023', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212500232', '厅门', '厅门', '830', '0', '0', 'Z21250023', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212500251', '门光电', '门光电', '870', '0', '0', 'Z21250025', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212500252', '门关幕', '门关幕', '880', '0', '0', 'Z21250025', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212500281', '安全触板', '安全触板', '950', '0', '0', 'Z21250028', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212500291', '门刀', '门刀', '980', '0', '0', 'Z21250029', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212500301', '轿门大偏心轮', '轿门大偏心轮', '1000', '0', '0', 'Z21250030', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212500303', '轿门小偏心轮', '轿门小偏心轮', '1020', '0', '0', 'Z21250030', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212500311', '轿门接近开关', '轿门接近开关', '1040', '0', '0', 'Z21250031', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212500321', '门机皮带', '门机皮带', '1060', '0', '0', 'Z21250032', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212500331', '安全触板', '安全触板', '1080', '0', '0', 'Z21250033', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212500341', '轿门开关', '轿门开关', '1120', '0', '0', 'Z21250034', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212500351', '门刀', '门刀', '1160', '0', '0', 'Z21250035', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22250001', '不良点Q1', '不良点Q1', '30', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22250002', '不良点Q2', '不良点Q2', '60', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22250003', '不良点Q3', '不良点Q3', '100', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22250004', '不良点Q4', '不良点Q4', '170', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22250005', '不良点Q5', '不良点Q5', '200', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22250006', '不良点Q6', '不良点Q6', '230', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22250007', '不良点Q7', '不良点Q7', '250', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22250008', '不良点Q8', '不良点Q8', '270', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22250009', '不良点Q9', '不良点Q9', '300', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22250010', '不良点Q10', '不良点Q10', '320', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22250011', '不良点Q11', '不良点Q11', '350', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22250012', '不良点Q12', '不良点Q12', '370', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22250014', '不良点Q14', '不良点Q14', '390', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22250015', '不良点Q15', '不良点Q15', '590', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22250016', '不良点Q16', '不良点Q16', '610', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22250017', '不良点Q17', '不良点Q17', '630', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22250018', '不良点Q18', '不良点Q18', '670', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22250019', '不良点Q19', '不良点Q19', '690', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22250020', '不良点Q20', '不良点Q20', '730', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22250021', '不良点Q21', '不良点Q21', '780', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22250022', '不良点Q22', '不良点Q22', '800', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22250023', '不良点Q23', '不良点Q23', '820', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22250024', '不良点Q24', '不良点Q24', '840', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22250025', '不良点Q25', '不良点Q25', '870', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22250026', '不良点Q26', '不良点Q26', '900', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22250027', '不良点Q27', '不良点Q27', '930', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22250028', '不良点Q28', '不良点Q28', '950', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22250029', '不良点Q29', '不良点Q29', '980', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22250030', '不良点Q30', '不良点Q30', '1000', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22250031', '不良点Q31', '不良点Q31', '1040', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22250032', '不良点Q32', '不良点Q32', '1060', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22250033', '不良点Q33', '不良点Q33', '1080', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22250034', '不良点Q34', '不良点Q34', '1120', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22250035', '不良点Q35', '不良点Q35', '1160', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500011', '电源欠相保护机能无效', '电源欠相保护机能无效', '30', '0', '0', 'Z22250001', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500012', '马达温度监控装置无效', '马达温度监控装置无效', '40', '0', '0', 'Z22250001', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500013', '其他（手写）', '其他（手写）', '50', '0', '0', 'Z22250001', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500021', '限速器轴润滑不良', '限速器轴润滑不良', '60', '0', '0', 'Z22250002', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500022', '反绳轮轴润滑不良', '反绳轮轴润滑不良', '70', '0', '0', 'Z22250002', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500023', '涨紧轮轴润滑不良', '涨紧轮轴润滑不良', '80', '0', '0', 'Z22250002', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500024', '其他（手写）', '其他（手写）', '90', '0', '0', 'Z22250002', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500031', '电源回路绝缘不良', '电源回路绝缘不良', '100', '0', '0', 'Z22250003', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500032', '电机回路绝缘不良', '电机回路绝缘不良', '110', '0', '0', 'Z22250003', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500033', '照明回路绝缘不良', '照明回路绝缘不良', '120', '0', '0', 'Z22250003', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500034', '操作回路绝缘不良', '操作回路绝缘不良', '130', '0', '0', 'Z22250003', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500035', '显示回路绝缘不良', '显示回路绝缘不良', '140', '0', '0', 'Z22250003', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500036', '保险丝规格不符', '保险丝规格不符', '150', '0', '0', 'Z22250003', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500037', '其他（手写）', '其他（手写）', '160', '0', '0', 'Z22250003', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500041', '电源电源过高', '电源电源过高', '170', '0', '0', 'Z22250004', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500042', '电源电源不足', '电源电源不足', '180', '0', '0', 'Z22250004', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500043', '其他（手写）', '其他（手写）', '190', '0', '0', 'Z22250004', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500051', '电压过高', '电压过高', '200', '0', '0', 'Z22250005', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500052', '电压不足', '电压不足', '210', '0', '0', 'Z22250005', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500053', '其他（手写）', '其他（手写）', '220', '0', '0', 'Z22250005', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500061', 'PG电缆线未单独铺设', 'PG电缆线未单独铺设', '230', '0', '0', 'Z22250006', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500062', '其他（手写）', '其他（手写）', '240', '0', '0', 'Z22250006', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500071', '未使用端子', '未使用端子', '250', '0', '0', 'Z22250007', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500072', '其他（手写）', '其他（手写）', '260', '0', '0', 'Z22250007', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500081', '不能有效平层', '不能有效平层', '270', '0', '0', 'Z22250008', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500082', '不能有效制停', '不能有效制停', '280', '0', '0', 'Z22250008', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500083', '其他（手写）', '其他（手写）', '290', '0', '0', 'Z22250008', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222500091', '轿厢在110%载重实验未符合要求', '轿厢在110%载重实验未符合要求', '300', '0', '0', 'Z22250009', '0', sysdate, '0', sysdate, '0',
   '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500092', '其他（手写）', '其他（手写）', '310', '0', '0', 'Z22250009', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500101', '安全钳不能有效制停轿厢', '安全钳不能有效制停轿厢', '320', '0', '0', 'Z22250010', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500102', '轿厢制停后，马达不能实现空转', '轿厢制停后，马达不能实现空转', '330', '0', '0', 'Z22250010', '0', sysdate, '0', sysdate, '0',
        '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500103', '其他（手写）', '其他（手写）', '340', '0', '0', 'Z22250010', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500111', '滑距不符合要求', '滑距不符合要求', '350', '0', '0', 'Z22250011', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500112', '其他（手写）', '其他（手写）', '360', '0', '0', 'Z22250011', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500121', '抱闸电压超标', '抱闸电压超标', '370', '0', '0', 'Z22250012', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500122', '其他（手写）', '其他（手写）', '380', '0', '0', 'Z22250012', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500141', '两台并联功能不良', '两台并联功能不良', '390', '0', '0', 'Z22250014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500142', '专用控制功能不良', '专用控制功能不良', '400', '0', '0', 'Z22250014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500143', '司机功能不良', '司机功能不良', '410', '0', '0', 'Z22250014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500144', '停电自动平层装置不良', '停电自动平层装置不良', '420', '0', '0', 'Z22250014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222500145', '轿厢内管制运行显示灯不良', '轿厢内管制运行显示灯不良', '430', '0', '0', 'Z22250014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500146', '火灾管制运行功能不良', '火灾管制运行功能不良', '440', '0', '0', 'Z22250014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222500147', '火灾管制运行回归信号触点', '火灾管制运行回归信号触点', '450', '0', '0', 'Z22250014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500148', '消防功能不良', '消防功能不良', '460', '0', '0', 'Z22250014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222500149', '光电管轿门安全触板功能不良', '光电管轿门安全触板功能不良', '470', '0', '0', 'Z22250014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z2225001410', '光幕轿门安全触板功能不良', '光幕轿门安全触板功能不良', '480', '0', '0', 'Z22250014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z2225001411', '超声波轿门安全触板功能不良', '超声波轿门安全触板功能不良', '490', '0', '0', 'Z22250014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z2225001412', '基准层回归控制功能不良', '基准层回归控制功能不良', '500', '0', '0', 'Z22250014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z2225001413', '满员通过功能不良', '满员通过功能不良', '510', '0', '0', 'Z22250014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z2225001414', '轿厢内监控（ＣＣＤ）摄像头不良', '轿厢内监控（ＣＣＤ）摄像头不良', '520', '0', '0', 'Z22250014', '0', sysdate, '0', sysdate, '0',
   '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z2225001415', 'IC卡管制功能不良', 'IC卡管制功能不良', '530', '0', '0', 'Z22250014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z2225001416', '监控盘功能不良', '监控盘功能不良', '540', '0', '0', 'Z22250014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z2225001417', '到站铃不良', '到站铃不良', '550', '0', '0', 'Z22250014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z2225001418', '轿厢内ＢＧＭ功能不良', '轿厢内ＢＧＭ功能不良', '560', '0', '0', 'Z22250014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z2225001419', '对讲机不良', '对讲机不良', '570', '0', '0', 'Z22250014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z2225001420', '其他（手写）', '其他（手写）', '580', '0', '0', 'Z22250014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500151', '系统时间无法设定完成', '系统时间无法设定完成', '590', '0', '0', 'Z22250015', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500152', '其他（手写）', '其他（手写）', '600', '0', '0', 'Z22250015', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222500161', '对重块缺失，平衡系数无法达到标准', '对重块缺失，平衡系数无法达到标准', '610', '0', '0', 'Z22250016', '0', sysdate, '0', sysdate, '0',
   '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500162', '其他（手写）', '其他（手写）', '620', '0', '0', 'Z22250016', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222500171', '100%载重时马达电流超过定额电流的1.1倍', '100%载重时马达电流超过定额电流的1.1倍', '630', '0', '0', 'Z22250017', '0', sysdate, '0',
                 sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500172', '其他（手写）', '其他（手写）', '640', '0', '0', 'Z22250017', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222500173', '110%载重时马达电流超过定额电流的1.2倍', '110%载重时马达电流超过定额电流的1.2倍', '650', '0', '0', 'Z22250017', '0', sysdate, '0',
                 sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500174', '其他（手写）', '其他（手写）', '660', '0', '0', 'Z22250017', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222500181', '额定速度的偏差超过标准范围', '额定速度的偏差超过标准范围', '670', '0', '0', 'Z22250018', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500182', '其他（手写）', '其他（手写）', '680', '0', '0', 'Z22250018', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500191', '调整不良', '调整不良', '690', '0', '0', 'Z22250019', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500192', '未调整', '未调整', '700', '0', '0', 'Z22250019', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500193', '滚轮导靴损坏', '滚轮导靴损坏', '710', '0', '0', 'Z22250019', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500194', '其他（手写）', '其他（手写）', '720', '0', '0', 'Z22250019', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500201', '开关缺失', '开关缺失', '730', '0', '0', 'Z22250020', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500202', '开关损坏', '开关损坏', '740', '0', '0', 'Z22250020', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222500203', '开关安装尺寸不良，不能有效动作', '开关安装尺寸不良，不能有效动作', '750', '0', '0', 'Z22250020', '0', sysdate, '0', sysdate, '0',
   '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222500204', '由于进水，开关未安装，安全回路短接', '由于进水，开关未安装，安全回路短接', '760', '0', '0', 'Z22250020', '0', sysdate, '0', sysdate,
   '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500205', '其他（手写）', '其他（手写）', '770', '0', '0', 'Z22250020', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500211', '轿门固定螺丝紧固不良', '轿门固定螺丝紧固不良', '780', '0', '0', 'Z22250021', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500212', '其他（手写）', '其他（手写）', '790', '0', '0', 'Z22250021', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500221', '安装不良', '安装不良', '800', '0', '0', 'Z22250022', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500222', '其他（手写）', '其他（手写）', '810', '0', '0', 'Z22250022', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500231', '速度不良', '速度不良', '820', '0', '0', 'Z22250023', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500232', '其他（手写）', '其他（手写）', '830', '0', '0', 'Z22250023', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500241', '平层板安装误差大', '平层板安装误差大', '840', '0', '0', 'Z22250024', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500242', '非平层板安装原因', '非平层板安装原因', '850', '0', '0', 'Z22250024', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500243', '其他（手写）', '其他（手写）', '860', '0', '0', 'Z22250024', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500251', '光电或光幕损坏', '光电或光幕损坏', '870', '0', '0', 'Z22250025', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500252', '光电或光幕未安装', '光电或光幕未安装', '880', '0', '0', 'Z22250025', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500253', '其他（手写）', '其他（手写）', '890', '0', '0', 'Z22250025', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500261', '呼梯不正常', '呼梯不正常', '900', '0', '0', 'Z22250026', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500262', '残障功能不正常', '残障功能不正常', '910', '0', '0', 'Z22250026', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500263', '其他（手写）', '其他（手写）', '920', '0', '0', 'Z22250026', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500271', '连接器缺失，手动压接', '连接器缺失，手动压接', '930', '0', '0', 'Z22250027', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500272', '其他（手写）', '其他（手写）', '940', '0', '0', 'Z22250027', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222500281', '安全触板开关的伸出量不足', '安全触板开关的伸出量不足', '950', '0', '0', 'Z22250028', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222500282', '安全触板开关的伸出量过大', '安全触板开关的伸出量过大', '960', '0', '0', 'Z22250028', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500283', '其他（手写）', '其他（手写）', '970', '0', '0', 'Z22250028', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500291', '门刀尺寸不良', '门刀尺寸不良', '980', '0', '0', 'Z22250029', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500292', '其他（手写）', '其他（手写）', '990', '0', '0', 'Z22250029', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222500301', '轿门大偏芯轮的偏芯位置不良', '轿门大偏芯轮的偏芯位置不良', '1000', '0', '0', 'Z22250030', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222500302', '小偏心轮与导轨间隙不良', '小偏心轮与导轨间隙不良', '1010', '0', '0', 'Z22250030', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500304', '其他（手写）', '其他（手写）', '1030', '0', '0', 'Z22250030', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500311', '接近开关不符合要求', '接近开关不符合要求', '1040', '0', '0', 'Z22250031', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500312', '其他（手写）', '其他（手写）', '1050', '0', '0', 'Z22250031', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500321', '门机皮带张力不良', '门机皮带张力不良', '1060', '0', '0', 'Z22250032', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500322', '其他（手写）', '其他（手写）', '1070', '0', '0', 'Z22250032', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500331', '开关缺失', '开关缺失', '1080', '0', '0', 'Z22250033', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500332', '开关调整不良', '开关调整不良', '1090', '0', '0', 'Z22250033', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500333', '走线方式不好', '走线方式不好', '1100', '0', '0', 'Z22250033', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500334', '其他（手写）', '其他（手写）', '1110', '0', '0', 'Z22250033', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500341', '开关缺失', '开关缺失', '1120', '0', '0', 'Z22250034', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500342', '开关调整不良', '开关调整不良', '1130', '0', '0', 'Z22250034', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500343', '走线方式不好', '走线方式不好', '1140', '0', '0', 'Z22250034', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500344', '其他（手写）', '其他（手写）', '1150', '0', '0', 'Z22250034', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222500351', '地坎安装不一致，导致部分楼层间隙符合标准，部分楼层间隙偏大或偏小', '地坎安装不一致，导致部分楼层间隙符合标准，部分楼层间隙偏大或偏小', '1160', '0', '0', 'Z22250035',
                 '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500352', '间隙过小', '间隙过小', '1170', '0', '0', 'Z22250035', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500353', '间隙过大', '间隙过大', '1180', '0', '0', 'Z22250035', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500354', '其他（手写）', '其他（手写）', '1190', '0', '0', 'Z22250035', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23250001', '不良点Q1', '不良点Q1', '30', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23250002', '不良点Q2', '不良点Q2', '60', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23250003', '不良点Q3', '不良点Q3', '100', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23250004', '不良点Q4', '不良点Q4', '170', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23250005', '不良点Q5', '不良点Q5', '200', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23250006', '不良点Q6', '不良点Q6', '230', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23250007', '不良点Q7', '不良点Q7', '250', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23250008', '不良点Q8', '不良点Q8', '270', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23250009', '不良点Q9', '不良点Q9', '300', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23250010', '不良点Q10', '不良点Q10', '320', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23250011', '不良点Q11', '不良点Q11', '350', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23250012', '不良点Q12', '不良点Q12', '370', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23250014', '不良点Q14', '不良点Q14', '390', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23250015', '不良点Q15', '不良点Q15', '590', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23250016', '不良点Q16', '不良点Q16', '610', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23250017', '不良点Q17', '不良点Q17', '630', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23250018', '不良点Q18', '不良点Q18', '670', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23250019', '不良点Q19', '不良点Q19', '690', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23250020', '不良点Q20', '不良点Q20', '730', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23250021', '不良点Q21', '不良点Q21', '780', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23250022', '不良点Q22', '不良点Q22', '800', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23250023', '不良点Q23', '不良点Q23', '820', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23250024', '不良点Q24', '不良点Q24', '840', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23250025', '不良点Q25', '不良点Q25', '870', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23250026', '不良点Q26', '不良点Q26', '900', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23250027', '不良点Q27', '不良点Q27', '930', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23250028', '不良点Q28', '不良点Q28', '950', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23250029', '不良点Q29', '不良点Q29', '980', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23250030', '不良点Q30', '不良点Q30', '1000', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23250031', '不良点Q31', '不良点Q31', '1040', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23250032', '不良点Q32', '不良点Q32', '1060', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23250033', '不良点Q33', '不良点Q33', '1080', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23250034', '不良点Q34', '不良点Q34', '1120', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23250035', '不良点Q35', '不良点Q35', '1160', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232500011', '调试员以故障报告形式反馈工厂', '调试员以故障报告形式反馈工厂', '30', '0', '0', 'Z23250001', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500013', '其他（手写）', '其他（手写）', '50', '0', '0', 'Z23250001', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500021', '安装责任者整改', '安装责任者整改', '60', '0', '0', 'Z23250002', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500024', '其他（手写）', '其他（手写）', '90', '0', '0', 'Z23250002', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232500031', '原因不明，故障报告反馈，并寻求支援', '原因不明，故障报告反馈，并寻求支援', '100', '0', '0', 'Z23250003', '0', sysdate, '0', sysdate,
   '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500037', '其他（手写）', '其他（手写）', '160', '0', '0', 'Z23250003', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500041', '要求甲方调整电源电压', '要求甲方调整电源电压', '170', '0', '0', 'Z23250004', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500043', '其他（手写）', '其他（手写）', '190', '0', '0', 'Z23250004', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500053', '其他（手写）', '其他（手写）', '220', '0', '0', 'Z23250005', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500061', '安装责任者整改', '安装责任者整改', '230', '0', '0', 'Z23250006', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500062', '其他（手写）', '其他（手写）', '240', '0', '0', 'Z23250006', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500071', '安装责任者整改', '安装责任者整改', '250', '0', '0', 'Z23250007', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500072', '其他（手写）', '其他（手写）', '260', '0', '0', 'Z23250007', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232500081', '电梯禁用，原因不明，故障报告反馈，并寻求支援', '电梯禁用，原因不明，故障报告反馈，并寻求支援', '270', '0', '0', 'Z23250008', '0', sysdate, '0',
                 sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232500082', '电梯禁用，抱闸不良，故障报告反馈，相关部门后续处理', '电梯禁用，抱闸不良，故障报告反馈，相关部门后续处理', '280', '0', '0', 'Z23250008', '0', sysdate,
                 '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500083', '其他（手写）', '其他（手写）', '290', '0', '0', 'Z23250008', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232500091', '电梯禁用，原因不明，故障报告反馈，并寻求支援', '电梯禁用，原因不明，故障报告反馈，并寻求支援', '300', '0', '0', 'Z23250009', '0', sysdate, '0',
                 sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500092', '其他（手写）', '其他（手写）', '310', '0', '0', 'Z23250009', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500101', '安装责任者整改', '安装责任者整改', '320', '0', '0', 'Z23250010', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232500102', '原因不明，故障报告反馈，并寻求支援', '原因不明，故障报告反馈，并寻求支援', '330', '0', '0', 'Z23250010', '0', sysdate, '0', sysdate,
   '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500103', '其他（手写）', '其他（手写）', '340', '0', '0', 'Z23250010', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232500111', '电梯禁用，抱闸不良，故障报告反馈，相关部门后续处理', '电梯禁用，抱闸不良，故障报告反馈，相关部门后续处理', '350', '0', '0', 'Z23250011', '0', sysdate,
                 '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500112', '其他（手写）', '其他（手写）', '360', '0', '0', 'Z23250011', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500121', '调试员以故障报告形式反馈工厂', '调试员以故障报告形式反馈工厂', '370', '0', '0', 'Z23250012', '0', sysdate, '0', sysdate, '0',
        '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500122', '其他（手写）', '其他（手写）', '380', '0', '0', 'Z23250012', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232500141', '原因不明，故障报告反馈，并寻求支援', '原因不明，故障报告反馈，并寻求支援', '390', '0', '0', 'Z23250014', '0', sysdate, '0', sysdate,
   '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z2325001420', '其他（手写）', '其他（手写）', '580', '0', '0', 'Z23250014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232500151', '原因不明，故障报告反馈，并寻求支援', '原因不明，故障报告反馈，并寻求支援', '590', '0', '0', 'Z23250015', '0', sysdate, '0', sysdate,
   '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500152', '其他（手写）', '其他（手写）', '600', '0', '0', 'Z23250015', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232500161', '由责任方故障处理或购买补齐部品后重新申请调试', '由责任方故障处理或购买补齐部品后重新申请调试', '610', '0', '0', 'Z23250016', '0', sysdate, '0',
                 sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500162', '其他（手写）', '其他（手写）', '620', '0', '0', 'Z23250016', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500171', '相关部门确认', '相关部门确认', '630', '0', '0', 'Z23250017', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500172', '其他（手写）', '其他（手写）', '640', '0', '0', 'Z23250017', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500173', '相关部门确认', '相关部门确认', '650', '0', '0', 'Z23250017', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500174', '其他（手写）', '其他（手写）', '660', '0', '0', 'Z23250017', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500181', '相关部门确认', '相关部门确认', '670', '0', '0', 'Z23250018', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500182', '其他（手写）', '其他（手写）', '680', '0', '0', 'Z23250018', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232500191', '由责任方故障处理或购买补齐部品', '由责任方故障处理或购买补齐部品', '690', '0', '0', 'Z23250019', '0', sysdate, '0', sysdate, '0',
   '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500192', '调试员寻求支援整改', '调试员寻求支援整改', '700', '0', '0', 'Z23250019', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500194', '其他（手写）', '其他（手写）', '720', '0', '0', 'Z23250019', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232500201', '由责任方故障处理或购买补齐部品', '由责任方故障处理或购买补齐部品', '730', '0', '0', 'Z23250020', '0', sysdate, '0', sysdate, '0',
   '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500202', '安装责任者整改', '安装责任者整改', '740', '0', '0', 'Z23250020', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232500203', '进水不可使用，水干后安装责任者装好开关', '进水不可使用，水干后安装责任者装好开关', '750', '0', '0', 'Z23250020', '0', sysdate, '0', sysdate,
   '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500205', '其他（手写）', '其他（手写）', '770', '0', '0', 'Z23250020', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500211', '安装责任者整改', '安装责任者整改', '780', '0', '0', 'Z23250021', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500212', '其他（手写）', '其他（手写）', '790', '0', '0', 'Z23250021', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500221', '安装责任者整改', '安装责任者整改', '800', '0', '0', 'Z23250022', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500222', '其他（手写）', '其他（手写）', '810', '0', '0', 'Z23250022', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232500231', '原因不明，故障报告反馈，并寻求支援', '原因不明，故障报告反馈，并寻求支援', '820', '0', '0', 'Z23250023', '0', sysdate, '0', sysdate,
   '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500232', '其他（手写）', '其他（手写）', '830', '0', '0', 'Z23250023', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500241', '安装责任者整改', '安装责任者整改', '840', '0', '0', 'Z23250024', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232500242', '原因不明，故障报告反馈，并寻求支援', '原因不明，故障报告反馈，并寻求支援', '850', '0', '0', 'Z23250024', '0', sysdate, '0', sysdate,
   '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500243', '其他（手写）', '其他（手写）', '860', '0', '0', 'Z23250024', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232500251', '由责任方故障处理或购买补齐部品', '由责任方故障处理或购买补齐部品', '870', '0', '0', 'Z23250025', '0', sysdate, '0', sysdate, '0',
   '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500252', '安装责任者整改', '安装责任者整改', '880', '0', '0', 'Z23250025', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500253', '其他（手写）', '其他（手写）', '890', '0', '0', 'Z23250025', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232500261', '原因不明，故障报告反馈，并寻求支援', '原因不明，故障报告反馈，并寻求支援', '900', '0', '0', 'Z23250026', '0', sysdate, '0', sysdate,
   '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500263', '其他（手写）', '其他（手写）', '920', '0', '0', 'Z23250026', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232500271', '由责任方故障处理或购买补齐部品', '由责任方故障处理或购买补齐部品', '930', '0', '0', 'Z23250027', '0', sysdate, '0', sysdate, '0',
   '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500272', '其他（手写）', '其他（手写）', '940', '0', '0', 'Z23250027', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500281', '安装责任者整改', '安装责任者整改', '950', '0', '0', 'Z23250028', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500283', '其他（手写）', '其他（手写）', '970', '0', '0', 'Z23250028', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500291', '安装责任者整改', '安装责任者整改', '980', '0', '0', 'Z23250029', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500292', '其他（手写）', '其他（手写）', '990', '0', '0', 'Z23250029', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500301', '安装责任者整改', '安装责任者整改', '1000', '0', '0', 'Z23250030', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500304', '其他（手写）', '其他（手写）', '1030', '0', '0', 'Z23250030', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500311', '安装责任者整改', '安装责任者整改', '1040', '0', '0', 'Z23250031', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500312', '其他（手写）', '其他（手写）', '1050', '0', '0', 'Z23250031', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500321', '安装责任者整改', '安装责任者整改', '1060', '0', '0', 'Z23250032', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500322', '其他（手写）', '其他（手写）', '1070', '0', '0', 'Z23250032', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232500331', '由责任方故障处理或购买补齐部品', '由责任方故障处理或购买补齐部品', '1080', '0', '0', 'Z23250033', '0', sysdate, '0', sysdate, '0',
   '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500332', '安装责任者整改', '安装责任者整改', '1090', '0', '0', 'Z23250033', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500334', '其他（手写）', '其他（手写）', '1110', '0', '0', 'Z23250033', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232500341', '由责任方故障处理或购买补齐部品', '由责任方故障处理或购买补齐部品', '1120', '0', '0', 'Z23250034', '0', sysdate, '0', sysdate, '0',
   '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500342', '安装责任者整改', '安装责任者整改', '1130', '0', '0', 'Z23250034', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500344', '其他（手写）', '其他（手写）', '1150', '0', '0', 'Z23250034', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500351', '安装责任者整改', '安装责任者整改', '1160', '0', '0', 'Z23250035', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500354', '其他（手写）', '其他（手写）', '1190', '0', '0', 'Z23250035', '0', sysdate, '0', sysdate, '0', '0');

--------------Add


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21250013', '部品B13', '部品B13', '390', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

Insert into SYSTEM_CODE (CODE,CODE_DESC_EN,CODE_DESC_ZH,PRIORITY,DISABLED,NEED_CONTROL,PARENT_CODE,VERSION,CREATED_DTM,CREATED_BY,LAST_MODIFIED_DTM,LAST_MODIFIED_BY,DELETED) values ('Z21Z212500131','其他（手写）','其他（手写）',10,0,0,'Z21250013',0,sysdate,0,sysdate,0,0);




INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22250013', '不良点Q13', '不良点Q13', '390', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED) VALUES ('Z222500131', '载重补偿的设定不良', '载重补偿的设定不良', '390', '0', '0', 'Z22250013', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222500132', '其他（手写）', '其他（手写）', '400', '0', '0', 'Z22250013', '0', sysdate, '0', sysdate, '0', '0');



INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23250013', '不良点Q13', '不良点Q13', '390', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232500131', '原因不明，故障报告反馈，并寻求支援', '原因不明，故障报告反馈，并寻求支援', '390', '0', '0', 'Z23250013', '0', sysdate, '0', sysdate,
   '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232500132', '其他（手写）', '其他（手写）', '400', '0', '0', 'Z23250013', '0', sysdate, '0', sysdate, '0', '0');
