INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21260001', '部品B1', '部品B1', '30', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21260002', '部品B2', '部品B2', '60', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21260003', '部品B3', '部品B3', '100', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21260004', '部品B4', '部品B4', '170', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21260005', '部品B5', '部品B5', '200', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21260006', '部品B6', '部品B6', '230', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21260007', '部品B7', '部品B7', '250', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21260008', '部品B8', '部品B8', '270', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21260009', '部品B9', '部品B9', '300', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21260010', '部品B10', '部品B10', '320', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21260011', '部品B11', '部品B11', '350', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21260012', '部品B12', '部品B12', '370', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21260013', '部品B13', '部品B13', '390', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21260014', '部品B14', '部品B14', '410', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21260015', '部品B15', '部品B15', '610', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21260016', '部品B16', '部品B16', '630', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21260017', '部品B17', '部品B17', '650', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21260018', '部品B18', '部品B18', '690', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21260019', '部品B19', '部品B19', '710', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21260020', '部品B20', '部品B20', '750', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21260021', '部品B21', '部品B21', '800', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21260022', '部品B22', '部品B22', '820', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21260023', '部品B23', '部品B23', '840', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21260024', '部品B24', '部品B24', '860', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21260025', '部品B25', '部品B25', '890', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21260026', '部品B26', '部品B26', '920', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21260027', '部品B27', '部品B27', '950', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21260028', '部品B28', '部品B28', '970', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21260029', '部品B29', '部品B29', '1000', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21260030', '部品B30', '部品B30', '1020', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21260031', '部品B31', '部品B31', '1060', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21260032', '部品B32', '部品B32', '1080', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21260033', '部品B33', '部品B33', '1100', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21260034', '部品B34', '部品B34', '1140', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21260035', '部品B35', '部品B35', '1180', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212600011', '控制柜', '控制柜', '30', '0', '0', 'Z21260001', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212600012', '马达', '马达', '40', '0', '0', 'Z21260001', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212600021', '限速器', '限速器', '60', '0', '0', 'Z21260002', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212600022', '反绳轮', '反绳轮', '70', '0', '0', 'Z21260002', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212600023', '涨紧轮', '涨紧轮', '80', '0', '0', 'Z21260002', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212600061', 'PG', 'PG', '230', '0', '0', 'Z21260006', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212600071', '马达', '马达', '250', '0', '0', 'Z21260007', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212600111', '制动器', '制动器', '350', '0', '0', 'Z21260011', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212600121', '控制柜', '控制柜', '370', '0', '0', 'Z21260012', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212600191', '轿厢滚轮导靴', '轿厢滚轮导靴', '710', '0', '0', 'Z21260019', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212600192', '对重滚轮导靴', '对重滚轮导靴', '720', '0', '0', 'Z21260019', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212600211', '轿门', '轿门', '800', '0', '0', 'Z21260021', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212600212', '轿门', '轿门', '810', '0', '0', 'Z21260021', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212600221', '轿门', '轿门', '820', '0', '0', 'Z21260022', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212600222', '厅门', '厅门', '830', '0', '0', 'Z21260022', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212600231', '轿门', '轿门', '840', '0', '0', 'Z21260023', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212600232', '厅门', '厅门', '850', '0', '0', 'Z21260023', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212600251', '门光电', '门光电', '890', '0', '0', 'Z21260025', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212600252', '门关幕', '门关幕', '900', '0', '0', 'Z21260025', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212600281', '安全触板', '安全触板', '970', '0', '0', 'Z21260028', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212600291', '门刀', '门刀', '1000', '0', '0', 'Z21260029', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212600301', '轿门大偏心轮', '轿门大偏心轮', '1020', '0', '0', 'Z21260030', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212600303', '轿门小偏心轮', '轿门小偏心轮', '1040', '0', '0', 'Z21260030', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212600311', '轿门接近开关', '轿门接近开关', '1060', '0', '0', 'Z21260031', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212600321', '门机皮带', '门机皮带', '1080', '0', '0', 'Z21260032', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212600331', '安全触板', '安全触板', '1100', '0', '0', 'Z21260033', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212600341', '轿门开关', '轿门开关', '1140', '0', '0', 'Z21260034', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212600351', '门刀', '门刀', '1180', '0', '0', 'Z21260035', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22260001', '不良点Q1', '不良点Q1', '30', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22260002', '不良点Q2', '不良点Q2', '60', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22260003', '不良点Q3', '不良点Q3', '100', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22260004', '不良点Q4', '不良点Q4', '170', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22260005', '不良点Q5', '不良点Q5', '200', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22260006', '不良点Q6', '不良点Q6', '230', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22260007', '不良点Q7', '不良点Q7', '250', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22260008', '不良点Q8', '不良点Q8', '270', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22260009', '不良点Q9', '不良点Q9', '300', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22260010', '不良点Q10', '不良点Q10', '320', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22260011', '不良点Q11', '不良点Q11', '350', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22260012', '不良点Q12', '不良点Q12', '370', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22260013', '不良点Q13', '不良点Q13', '390', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22260014', '不良点Q14', '不良点Q14', '410', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22260015', '不良点Q15', '不良点Q15', '610', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22260016', '不良点Q16', '不良点Q16', '630', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22260017', '不良点Q17', '不良点Q17', '650', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22260018', '不良点Q18', '不良点Q18', '690', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22260019', '不良点Q19', '不良点Q19', '710', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22260020', '不良点Q20', '不良点Q20', '750', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22260021', '不良点Q21', '不良点Q21', '800', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22260022', '不良点Q22', '不良点Q22', '820', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22260023', '不良点Q23', '不良点Q23', '840', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22260024', '不良点Q24', '不良点Q24', '860', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22260025', '不良点Q25', '不良点Q25', '890', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22260026', '不良点Q26', '不良点Q26', '920', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22260027', '不良点Q27', '不良点Q27', '950', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22260028', '不良点Q28', '不良点Q28', '970', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22260029', '不良点Q29', '不良点Q29', '1000', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22260030', '不良点Q30', '不良点Q30', '1020', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22260031', '不良点Q31', '不良点Q31', '1060', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22260032', '不良点Q32', '不良点Q32', '1080', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22260033', '不良点Q33', '不良点Q33', '1100', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22260034', '不良点Q34', '不良点Q34', '1140', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22260035', '不良点Q35', '不良点Q35', '1180', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600011', '电源欠相保护机能无效', '电源欠相保护机能无效', '30', '0', '0', 'Z22260001', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600012', '马达温度监控装置无效', '马达温度监控装置无效', '40', '0', '0', 'Z22260001', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600013', '其他（手写）', '其他（手写）', '50', '0', '0', 'Z22260001', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600021', '限速器轴润滑不良', '限速器轴润滑不良', '60', '0', '0', 'Z22260002', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600022', '反绳轮轴润滑不良', '反绳轮轴润滑不良', '70', '0', '0', 'Z22260002', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600023', '涨紧轮轴润滑不良', '涨紧轮轴润滑不良', '80', '0', '0', 'Z22260002', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600024', '其他（手写）', '其他（手写）', '90', '0', '0', 'Z22260002', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600031', '电源回路绝缘不良', '电源回路绝缘不良', '100', '0', '0', 'Z22260003', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600032', '电机回路绝缘不良', '电机回路绝缘不良', '110', '0', '0', 'Z22260003', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600033', '照明回路绝缘不良', '照明回路绝缘不良', '120', '0', '0', 'Z22260003', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600034', '操作回路绝缘不良', '操作回路绝缘不良', '130', '0', '0', 'Z22260003', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600035', '显示回路绝缘不良', '显示回路绝缘不良', '140', '0', '0', 'Z22260003', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600036', '保险丝规格不符', '保险丝规格不符', '150', '0', '0', 'Z22260003', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600037', '其他（手写）', '其他（手写）', '160', '0', '0', 'Z22260003', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600041', '电源电源过高', '电源电源过高', '170', '0', '0', 'Z22260004', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600042', '电源电源不足', '电源电源不足', '180', '0', '0', 'Z22260004', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600043', '其他（手写）', '其他（手写）', '190', '0', '0', 'Z22260004', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600051', '电压过高', '电压过高', '200', '0', '0', 'Z22260005', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600052', '电压不足', '电压不足', '210', '0', '0', 'Z22260005', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600053', '其他（手写）', '其他（手写）', '220', '0', '0', 'Z22260005', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600061', 'PG电缆线未单独铺设', 'PG电缆线未单独铺设', '230', '0', '0', 'Z22260006', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600062', '其他（手写）', '其他（手写）', '240', '0', '0', 'Z22260006', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600071', '未使用端子', '未使用端子', '250', '0', '0', 'Z22260007', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600072', '其他（手写）', '其他（手写）', '260', '0', '0', 'Z22260007', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600081', '不能有效平层', '不能有效平层', '270', '0', '0', 'Z22260008', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600082', '不能有效制停', '不能有效制停', '280', '0', '0', 'Z22260008', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600083', '其他（手写）', '其他（手写）', '290', '0', '0', 'Z22260008', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222600091', '轿厢在110%载重实验未符合要求', '轿厢在110%载重实验未符合要求', '300', '0', '0', 'Z22260009', '0', sysdate, '0', sysdate, '0',
   '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600092', '其他（手写）', '其他（手写）', '310', '0', '0', 'Z22260009', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600101', '安全钳不能有效制停轿厢', '安全钳不能有效制停轿厢', '320', '0', '0', 'Z22260010', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600102', '轿厢制停后，马达不能实现空转', '轿厢制停后，马达不能实现空转', '330', '0', '0', 'Z22260010', '0', sysdate, '0', sysdate, '0',
        '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600103', '其他（手写）', '其他（手写）', '340', '0', '0', 'Z22260010', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600111', '滑距不符合要求', '滑距不符合要求', '350', '0', '0', 'Z22260011', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600112', '其他（手写）', '其他（手写）', '360', '0', '0', 'Z22260011', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600121', '抱闸电压超标', '抱闸电压超标', '370', '0', '0', 'Z22260012', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600122', '其他（手写）', '其他（手写）', '380', '0', '0', 'Z22260012', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600131', '载重补偿的设定不良', '载重补偿的设定不良', '390', '0', '0', 'Z22260013', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600132', '其他（手写）', '其他（手写）', '400', '0', '0', 'Z22260013', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600141', '两台并联功能不良', '两台并联功能不良', '410', '0', '0', 'Z22260014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600142', '专用控制功能不良', '专用控制功能不良', '420', '0', '0', 'Z22260014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600143', '司机功能不良', '司机功能不良', '430', '0', '0', 'Z22260014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600144', '停电自动平层装置不良', '停电自动平层装置不良', '440', '0', '0', 'Z22260014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222600145', '轿厢内管制运行显示灯不良', '轿厢内管制运行显示灯不良', '450', '0', '0', 'Z22260014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600146', '火灾管制运行功能不良', '火灾管制运行功能不良', '460', '0', '0', 'Z22260014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222600147', '火灾管制运行回归信号触点', '火灾管制运行回归信号触点', '470', '0', '0', 'Z22260014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600148', '消防功能不良', '消防功能不良', '480', '0', '0', 'Z22260014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222600149', '光电管轿门安全触板功能不良', '光电管轿门安全触板功能不良', '490', '0', '0', 'Z22260014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z2226001410', '光幕轿门安全触板功能不良', '光幕轿门安全触板功能不良', '500', '0', '0', 'Z22260014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z2226001411', '超声波轿门安全触板功能不良', '超声波轿门安全触板功能不良', '510', '0', '0', 'Z22260014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z2226001412', '基准层回归控制功能不良', '基准层回归控制功能不良', '520', '0', '0', 'Z22260014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z2226001413', '满员通过功能不良', '满员通过功能不良', '530', '0', '0', 'Z22260014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z2226001414', '轿厢内监控（ＣＣＤ）摄像头不良', '轿厢内监控（ＣＣＤ）摄像头不良', '540', '0', '0', 'Z22260014', '0', sysdate, '0', sysdate, '0',
   '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z2226001415', 'IC卡管制功能不良', 'IC卡管制功能不良', '550', '0', '0', 'Z22260014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z2226001416', '监控盘功能不良', '监控盘功能不良', '560', '0', '0', 'Z22260014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z2226001417', '到站铃不良', '到站铃不良', '570', '0', '0', 'Z22260014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z2226001418', '轿厢内ＢＧＭ功能不良', '轿厢内ＢＧＭ功能不良', '580', '0', '0', 'Z22260014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z2226001419', '对讲机不良', '对讲机不良', '590', '0', '0', 'Z22260014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z2226001420', '其他（手写）', '其他（手写）', '600', '0', '0', 'Z22260014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600151', '系统时间无法设定完成', '系统时间无法设定完成', '610', '0', '0', 'Z22260015', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600152', '其他（手写）', '其他（手写）', '620', '0', '0', 'Z22260015', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222600161', '对重块缺失，平衡系数无法达到标准', '对重块缺失，平衡系数无法达到标准', '630', '0', '0', 'Z22260016', '0', sysdate, '0', sysdate, '0',
   '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600162', '其他（手写）', '其他（手写）', '640', '0', '0', 'Z22260016', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222600171', '100%载重时马达电流超过定额电流的1.1倍', '100%载重时马达电流超过定额电流的1.1倍', '650', '0', '0', 'Z22260017', '0', sysdate, '0',
                 sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600172', '其他（手写）', '其他（手写）', '660', '0', '0', 'Z22260017', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222600173', '110%载重时马达电流超过定额电流的1.2倍', '110%载重时马达电流超过定额电流的1.2倍', '670', '0', '0', 'Z22260017', '0', sysdate, '0',
                 sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600174', '其他（手写）', '其他（手写）', '680', '0', '0', 'Z22260017', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222600181', '额定速度的偏差超过标准范围', '额定速度的偏差超过标准范围', '690', '0', '0', 'Z22260018', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600182', '其他（手写）', '其他（手写）', '700', '0', '0', 'Z22260018', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600191', '调整不良', '调整不良', '710', '0', '0', 'Z22260019', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600192', '未调整', '未调整', '720', '0', '0', 'Z22260019', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600193', '滚轮导靴损坏', '滚轮导靴损坏', '730', '0', '0', 'Z22260019', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600194', '其他（手写）', '其他（手写）', '740', '0', '0', 'Z22260019', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600201', '开关缺失', '开关缺失', '750', '0', '0', 'Z22260020', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600202', '开关损坏', '开关损坏', '760', '0', '0', 'Z22260020', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222600203', '开关安装尺寸不良，不能有效动作', '开关安装尺寸不良，不能有效动作', '770', '0', '0', 'Z22260020', '0', sysdate, '0', sysdate, '0',
   '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222600204', '由于进水，开关未安装，安全回路短接', '由于进水，开关未安装，安全回路短接', '780', '0', '0', 'Z22260020', '0', sysdate, '0', sysdate,
   '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600205', '其他（手写）', '其他（手写）', '790', '0', '0', 'Z22260020', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600211', '轿门固定螺丝紧固不良', '轿门固定螺丝紧固不良', '800', '0', '0', 'Z22260021', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600212', '其他（手写）', '其他（手写）', '810', '0', '0', 'Z22260021', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600221', '安装不良', '安装不良', '820', '0', '0', 'Z22260022', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600222', '其他（手写）', '其他（手写）', '830', '0', '0', 'Z22260022', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600231', '速度不良', '速度不良', '840', '0', '0', 'Z22260023', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600232', '其他（手写）', '其他（手写）', '850', '0', '0', 'Z22260023', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600241', '平层板安装误差大', '平层板安装误差大', '860', '0', '0', 'Z22260024', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600242', '非平层板安装原因', '非平层板安装原因', '870', '0', '0', 'Z22260024', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600243', '其他（手写）', '其他（手写）', '880', '0', '0', 'Z22260024', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600251', '光电或光幕损坏', '光电或光幕损坏', '890', '0', '0', 'Z22260025', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600252', '光电或光幕未安装', '光电或光幕未安装', '900', '0', '0', 'Z22260025', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600253', '其他（手写）', '其他（手写）', '910', '0', '0', 'Z22260025', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600261', '呼梯不正常', '呼梯不正常', '920', '0', '0', 'Z22260026', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600262', '残障功能不正常', '残障功能不正常', '930', '0', '0', 'Z22260026', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600263', '其他（手写）', '其他（手写）', '940', '0', '0', 'Z22260026', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600271', '连接器缺失，手动压接', '连接器缺失，手动压接', '950', '0', '0', 'Z22260027', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600272', '其他（手写）', '其他（手写）', '960', '0', '0', 'Z22260027', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222600281', '安全触板开关的伸出量不足', '安全触板开关的伸出量不足', '970', '0', '0', 'Z22260028', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222600282', '安全触板开关的伸出量过大', '安全触板开关的伸出量过大', '980', '0', '0', 'Z22260028', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600283', '其他（手写）', '其他（手写）', '990', '0', '0', 'Z22260028', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600291', '门刀尺寸不良', '门刀尺寸不良', '1000', '0', '0', 'Z22260029', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600292', '其他（手写）', '其他（手写）', '1010', '0', '0', 'Z22260029', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222600301', '轿门大偏芯轮的偏芯位置不良', '轿门大偏芯轮的偏芯位置不良', '1020', '0', '0', 'Z22260030', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222600302', '小偏心轮与导轨间隙不良', '小偏心轮与导轨间隙不良', '1030', '0', '0', 'Z22260030', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600304', '其他（手写）', '其他（手写）', '1050', '0', '0', 'Z22260030', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600311', '接近开关不符合要求', '接近开关不符合要求', '1060', '0', '0', 'Z22260031', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600312', '其他（手写）', '其他（手写）', '1070', '0', '0', 'Z22260031', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600321', '门机皮带张力不良', '门机皮带张力不良', '1080', '0', '0', 'Z22260032', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600322', '其他（手写）', '其他（手写）', '1090', '0', '0', 'Z22260032', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600331', '开关缺失', '开关缺失', '1100', '0', '0', 'Z22260033', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600332', '开关调整不良', '开关调整不良', '1110', '0', '0', 'Z22260033', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600333', '走线方式不好', '走线方式不好', '1120', '0', '0', 'Z22260033', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600334', '其他（手写）', '其他（手写）', '1130', '0', '0', 'Z22260033', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600341', '开关缺失', '开关缺失', '1140', '0', '0', 'Z22260034', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600342', '开关调整不良', '开关调整不良', '1150', '0', '0', 'Z22260034', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600343', '走线方式不好', '走线方式不好', '1160', '0', '0', 'Z22260034', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600344', '其他（手写）', '其他（手写）', '1170', '0', '0', 'Z22260034', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222600351', '地坎安装不一致，导致部分楼层间隙符合标准，部分楼层间隙偏大或偏小', '地坎安装不一致，导致部分楼层间隙符合标准，部分楼层间隙偏大或偏小', '1180', '0', '0', 'Z22260035',
                 '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600352', '间隙过小', '间隙过小', '1190', '0', '0', 'Z22260035', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600353', '间隙过大', '间隙过大', '1200', '0', '0', 'Z22260035', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222600354', '其他（手写）', '其他（手写）', '1210', '0', '0', 'Z22260035', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23260001', '不良点Q1', '不良点Q1', '30', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23260002', '不良点Q2', '不良点Q2', '60', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23260003', '不良点Q3', '不良点Q3', '100', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23260004', '不良点Q4', '不良点Q4', '170', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23260005', '不良点Q5', '不良点Q5', '200', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23260006', '不良点Q6', '不良点Q6', '230', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23260007', '不良点Q7', '不良点Q7', '250', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23260008', '不良点Q8', '不良点Q8', '270', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23260009', '不良点Q9', '不良点Q9', '300', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23260010', '不良点Q10', '不良点Q10', '320', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23260011', '不良点Q11', '不良点Q11', '350', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23260012', '不良点Q12', '不良点Q12', '370', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23260013', '不良点Q13', '不良点Q13', '390', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23260014', '不良点Q14', '不良点Q14', '410', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23260015', '不良点Q15', '不良点Q15', '610', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23260016', '不良点Q16', '不良点Q16', '630', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23260017', '不良点Q17', '不良点Q17', '650', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23260018', '不良点Q18', '不良点Q18', '690', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23260019', '不良点Q19', '不良点Q19', '710', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23260020', '不良点Q20', '不良点Q20', '750', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23260021', '不良点Q21', '不良点Q21', '800', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23260022', '不良点Q22', '不良点Q22', '820', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23260023', '不良点Q23', '不良点Q23', '840', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23260024', '不良点Q24', '不良点Q24', '860', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23260025', '不良点Q25', '不良点Q25', '890', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23260026', '不良点Q26', '不良点Q26', '920', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23260027', '不良点Q27', '不良点Q27', '950', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23260028', '不良点Q28', '不良点Q28', '970', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23260029', '不良点Q29', '不良点Q29', '1000', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23260030', '不良点Q30', '不良点Q30', '1020', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23260031', '不良点Q31', '不良点Q31', '1060', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23260032', '不良点Q32', '不良点Q32', '1080', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23260033', '不良点Q33', '不良点Q33', '1100', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23260034', '不良点Q34', '不良点Q34', '1140', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23260035', '不良点Q35', '不良点Q35', '1180', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232600011', '调试员以故障报告形式反馈工厂', '调试员以故障报告形式反馈工厂', '30', '0', '0', 'Z23260001', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600013', '其他（手写）', '其他（手写）', '50', '0', '0', 'Z23260001', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600021', '安装责任者整改', '安装责任者整改', '60', '0', '0', 'Z23260002', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600024', '其他（手写）', '其他（手写）', '90', '0', '0', 'Z23260002', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232600031', '原因不明，故障报告反馈，并寻求支援', '原因不明，故障报告反馈，并寻求支援', '100', '0', '0', 'Z23260003', '0', sysdate, '0', sysdate,
   '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600037', '其他（手写）', '其他（手写）', '160', '0', '0', 'Z23260003', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600041', '要求甲方调整电源电压', '要求甲方调整电源电压', '170', '0', '0', 'Z23260004', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600043', '其他（手写）', '其他（手写）', '190', '0', '0', 'Z23260004', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600053', '其他（手写）', '其他（手写）', '220', '0', '0', 'Z23260005', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600061', '安装责任者整改', '安装责任者整改', '230', '0', '0', 'Z23260006', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600062', '其他（手写）', '其他（手写）', '240', '0', '0', 'Z23260006', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600071', '安装责任者整改', '安装责任者整改', '250', '0', '0', 'Z23260007', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600072', '其他（手写）', '其他（手写）', '260', '0', '0', 'Z23260007', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232600081', '电梯禁用，原因不明，故障报告反馈，并寻求支援', '电梯禁用，原因不明，故障报告反馈，并寻求支援', '270', '0', '0', 'Z23260008', '0', sysdate, '0',
                 sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232600082', '电梯禁用，抱闸不良，故障报告反馈，相关部门后续处理', '电梯禁用，抱闸不良，故障报告反馈，相关部门后续处理', '280', '0', '0', 'Z23260008', '0', sysdate,
                 '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600083', '其他（手写）', '其他（手写）', '290', '0', '0', 'Z23260008', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232600091', '电梯禁用，原因不明，故障报告反馈，并寻求支援', '电梯禁用，原因不明，故障报告反馈，并寻求支援', '300', '0', '0', 'Z23260009', '0', sysdate, '0',
                 sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600092', '其他（手写）', '其他（手写）', '310', '0', '0', 'Z23260009', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600101', '安装责任者整改', '安装责任者整改', '320', '0', '0', 'Z23260010', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232600102', '原因不明，故障报告反馈，并寻求支援', '原因不明，故障报告反馈，并寻求支援', '330', '0', '0', 'Z23260010', '0', sysdate, '0', sysdate,
   '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600103', '其他（手写）', '其他（手写）', '340', '0', '0', 'Z23260010', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232600111', '电梯禁用，抱闸不良，故障报告反馈，相关部门后续处理', '电梯禁用，抱闸不良，故障报告反馈，相关部门后续处理', '350', '0', '0', 'Z23260011', '0', sysdate,
                 '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600112', '其他（手写）', '其他（手写）', '360', '0', '0', 'Z23260011', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600121', '调试员以故障报告形式反馈工厂', '调试员以故障报告形式反馈工厂', '370', '0', '0', 'Z23260012', '0', sysdate, '0', sysdate, '0',
        '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600122', '其他（手写）', '其他（手写）', '380', '0', '0', 'Z23260012', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232600131', '原因不明，故障报告反馈，并寻求支援', '原因不明，故障报告反馈，并寻求支援', '390', '0', '0', 'Z23260013', '0', sysdate, '0', sysdate,
   '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600132', '其他（手写）', '其他（手写）', '400', '0', '0', 'Z23260013', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232600141', '原因不明，故障报告反馈，并寻求支援', '原因不明，故障报告反馈，并寻求支援', '410', '0', '0', 'Z23260014', '0', sysdate, '0', sysdate,
   '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z2326001420', '其他（手写）', '其他（手写）', '600', '0', '0', 'Z23260014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232600151', '原因不明，故障报告反馈，并寻求支援', '原因不明，故障报告反馈，并寻求支援', '610', '0', '0', 'Z23260015', '0', sysdate, '0', sysdate,
   '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600152', '其他（手写）', '其他（手写）', '620', '0', '0', 'Z23260015', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232600161', '由责任方故障处理或购买补齐部品后重新申请调试', '由责任方故障处理或购买补齐部品后重新申请调试', '630', '0', '0', 'Z23260016', '0', sysdate, '0',
                 sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600162', '其他（手写）', '其他（手写）', '640', '0', '0', 'Z23260016', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600171', '相关部门确认', '相关部门确认', '650', '0', '0', 'Z23260017', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600172', '其他（手写）', '其他（手写）', '660', '0', '0', 'Z23260017', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600173', '相关部门确认', '相关部门确认', '670', '0', '0', 'Z23260017', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600174', '其他（手写）', '其他（手写）', '680', '0', '0', 'Z23260017', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600181', '相关部门确认', '相关部门确认', '690', '0', '0', 'Z23260018', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600182', '其他（手写）', '其他（手写）', '700', '0', '0', 'Z23260018', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232600191', '由责任方故障处理或购买补齐部品', '由责任方故障处理或购买补齐部品', '710', '0', '0', 'Z23260019', '0', sysdate, '0', sysdate, '0',
   '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600192', '调试员寻求支援整改', '调试员寻求支援整改', '720', '0', '0', 'Z23260019', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600194', '其他（手写）', '其他（手写）', '740', '0', '0', 'Z23260019', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232600201', '由责任方故障处理或购买补齐部品', '由责任方故障处理或购买补齐部品', '750', '0', '0', 'Z23260020', '0', sysdate, '0', sysdate, '0',
   '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600202', '安装责任者整改', '安装责任者整改', '760', '0', '0', 'Z23260020', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232600203', '进水不可使用，水干后安装责任者装好开关', '进水不可使用，水干后安装责任者装好开关', '770', '0', '0', 'Z23260020', '0', sysdate, '0', sysdate,
   '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600205', '其他（手写）', '其他（手写）', '790', '0', '0', 'Z23260020', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600211', '安装责任者整改', '安装责任者整改', '800', '0', '0', 'Z23260021', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600212', '其他（手写）', '其他（手写）', '810', '0', '0', 'Z23260021', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600221', '安装责任者整改', '安装责任者整改', '820', '0', '0', 'Z23260022', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600222', '其他（手写）', '其他（手写）', '830', '0', '0', 'Z23260022', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232600231', '原因不明，故障报告反馈，并寻求支援', '原因不明，故障报告反馈，并寻求支援', '840', '0', '0', 'Z23260023', '0', sysdate, '0', sysdate,
   '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600232', '其他（手写）', '其他（手写）', '850', '0', '0', 'Z23260023', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600241', '安装责任者整改', '安装责任者整改', '860', '0', '0', 'Z23260024', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232600242', '原因不明，故障报告反馈，并寻求支援', '原因不明，故障报告反馈，并寻求支援', '870', '0', '0', 'Z23260024', '0', sysdate, '0', sysdate,
   '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600243', '其他（手写）', '其他（手写）', '880', '0', '0', 'Z23260024', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232600251', '由责任方故障处理或购买补齐部品', '由责任方故障处理或购买补齐部品', '890', '0', '0', 'Z23260025', '0', sysdate, '0', sysdate, '0',
   '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600252', '安装责任者整改', '安装责任者整改', '900', '0', '0', 'Z23260025', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600253', '其他（手写）', '其他（手写）', '910', '0', '0', 'Z23260025', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232600261', '原因不明，故障报告反馈，并寻求支援', '原因不明，故障报告反馈，并寻求支援', '920', '0', '0', 'Z23260026', '0', sysdate, '0', sysdate,
   '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600263', '其他（手写）', '其他（手写）', '940', '0', '0', 'Z23260026', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232600271', '由责任方故障处理或购买补齐部品', '由责任方故障处理或购买补齐部品', '950', '0', '0', 'Z23260027', '0', sysdate, '0', sysdate, '0',
   '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600272', '其他（手写）', '其他（手写）', '960', '0', '0', 'Z23260027', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600281', '安装责任者整改', '安装责任者整改', '970', '0', '0', 'Z23260028', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600283', '其他（手写）', '其他（手写）', '990', '0', '0', 'Z23260028', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600291', '安装责任者整改', '安装责任者整改', '1000', '0', '0', 'Z23260029', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600292', '其他（手写）', '其他（手写）', '1010', '0', '0', 'Z23260029', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600301', '安装责任者整改', '安装责任者整改', '1020', '0', '0', 'Z23260030', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600304', '其他（手写）', '其他（手写）', '1050', '0', '0', 'Z23260030', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600311', '安装责任者整改', '安装责任者整改', '1060', '0', '0', 'Z23260031', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600312', '其他（手写）', '其他（手写）', '1070', '0', '0', 'Z23260031', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600321', '安装责任者整改', '安装责任者整改', '1080', '0', '0', 'Z23260032', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600322', '其他（手写）', '其他（手写）', '1090', '0', '0', 'Z23260032', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232600331', '由责任方故障处理或购买补齐部品', '由责任方故障处理或购买补齐部品', '1100', '0', '0', 'Z23260033', '0', sysdate, '0', sysdate, '0',
   '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600332', '安装责任者整改', '安装责任者整改', '1110', '0', '0', 'Z23260033', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600334', '其他（手写）', '其他（手写）', '1130', '0', '0', 'Z23260033', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232600341', '由责任方故障处理或购买补齐部品', '由责任方故障处理或购买补齐部品', '1140', '0', '0', 'Z23260034', '0', sysdate, '0', sysdate, '0',
   '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600342', '安装责任者整改', '安装责任者整改', '1150', '0', '0', 'Z23260034', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600344', '其他（手写）', '其他（手写）', '1170', '0', '0', 'Z23260034', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600351', '安装责任者整改', '安装责任者整改', '1180', '0', '0', 'Z23260035', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232600354', '其他（手写）', '其他（手写）', '1210', '0', '0', 'Z23260035', '0', sysdate, '0', sysdate, '0', '0');
