INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21230001', '部品B1', '部品B1', '30', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21230002', '部品B2', '部品B2', '60', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21230003', '部品B3', '部品B3', '100', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21230004', '部品B4', '部品B4', '170', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21230005', '部品B5', '部品B5', '200', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21230006', '部品B6', '部品B6', '230', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21230007', '部品B7', '部品B7', '250', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21230008', '部品B8', '部品B8', '270', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21230009', '部品B9', '部品B9', '300', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21230010', '部品B10', '部品B10', '320', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21230011', '部品B11', '部品B11', '350', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21230012', '部品B12', '部品B12', '370', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21230013', '部品B13', '部品B13', '390', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21230014', '部品B14', '部品B14', '420', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21230015', '部品B15', '部品B15', '620', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21230016', '部品B16', '部品B16', '640', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21230017', '部品B17', '部品B17', '660', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21230018', '部品B18', '部品B18', '700', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21230019', '部品B19', '部品B19', '720', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21230020', '部品B20', '部品B20', '760', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21230021', '部品B21', '部品B21', '810', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21230022', '部品B22', '部品B22', '830', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21230023', '部品B23', '部品B23', '850', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21230024', '部品B24', '部品B24', '870', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21230025', '部品B25', '部品B25', '900', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21230026', '部品B26', '部品B26', '930', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21230027', '部品B27', '部品B27', '960', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21230028', '部品B28', '部品B28', '980', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21230029', '部品B29', '部品B29', '1010', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21230030', '部品B30', '部品B30', '1030', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21230031', '部品B31', '部品B31', '1070', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21230032', '部品B32', '部品B32', '1090', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21230033', '部品B33', '部品B33', '1110', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21230034', '部品B34', '部品B34', '1150', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21230035', '部品B35', '部品B35', '1190', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212300011', '控制柜', '控制柜', '30', '0', '0', 'Z21230001', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212300012', '马达', '马达', '40', '0', '0', 'Z21230001', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212300021', '限速器', '限速器', '60', '0', '0', 'Z21230002', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212300022', '反绳轮', '反绳轮', '70', '0', '0', 'Z21230002', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212300023', '涨紧轮', '涨紧轮', '80', '0', '0', 'Z21230002', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212300061', 'PG', 'PG', '230', '0', '0', 'Z21230006', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212300071', '马达', '马达', '250', '0', '0', 'Z21230007', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212300111', '制动器', '制动器', '350', '0', '0', 'Z21230011', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212300121', '控制柜', '控制柜', '370', '0', '0', 'Z21230012', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212300191', '轿厢滑动导靴', '轿厢滑动导靴', '720', '0', '0', 'Z21230019', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212300192', '对重滑动导靴', '对重滑动导靴', '730', '0', '0', 'Z21230019', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212300211', '轿门', '轿门', '810', '0', '0', 'Z21230021', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212300212', '轿门', '轿门', '820', '0', '0', 'Z21230021', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212300221', '轿门', '轿门', '830', '0', '0', 'Z21230022', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212300222', '厅门', '厅门', '840', '0', '0', 'Z21230022', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212300231', '轿门', '轿门', '850', '0', '0', 'Z21230023', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212300232', '厅门', '厅门', '860', '0', '0', 'Z21230023', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212300251', '门光电', '门光电', '900', '0', '0', 'Z21230025', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212300252', '门关幕', '门关幕', '910', '0', '0', 'Z21230025', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212300281', '安全触板', '安全触板', '980', '0', '0', 'Z21230028', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212300291', '门刀', '门刀', '1010', '0', '0', 'Z21230029', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212300301', '轿门大偏心轮', '轿门大偏心轮', '1030', '0', '0', 'Z21230030', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212300303', '轿门小偏心轮', '轿门小偏心轮', '1050', '0', '0', 'Z21230030', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212300311', '轿门接近开关', '轿门接近开关', '1070', '0', '0', 'Z21230031', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212300321', '门机皮带', '门机皮带', '1090', '0', '0', 'Z21230032', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212300331', '安全触板', '安全触板', '1110', '0', '0', 'Z21230033', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212300341', '轿门开关', '轿门开关', '1150', '0', '0', 'Z21230034', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212300351', '门刀', '门刀', '1190', '0', '0', 'Z21230035', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22230001', '不良点Q1', '不良点Q1', '30', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22230002', '不良点Q2', '不良点Q2', '60', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22230003', '不良点Q3', '不良点Q3', '100', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22230004', '不良点Q4', '不良点Q4', '170', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22230005', '不良点Q5', '不良点Q5', '200', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22230006', '不良点Q6', '不良点Q6', '230', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22230007', '不良点Q7', '不良点Q7', '250', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22230008', '不良点Q8', '不良点Q8', '270', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22230009', '不良点Q9', '不良点Q9', '300', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22230010', '不良点Q10', '不良点Q10', '320', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22230011', '不良点Q11', '不良点Q11', '350', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22230012', '不良点Q12', '不良点Q12', '370', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22230013', '不良点Q13', '不良点Q13', '390', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22230014', '不良点Q14', '不良点Q14', '420', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22230015', '不良点Q15', '不良点Q15', '620', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22230016', '不良点Q16', '不良点Q16', '640', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22230017', '不良点Q17', '不良点Q17', '660', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22230018', '不良点Q18', '不良点Q18', '700', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22230019', '不良点Q19', '不良点Q19', '720', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22230020', '不良点Q20', '不良点Q20', '760', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22230021', '不良点Q21', '不良点Q21', '810', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22230022', '不良点Q22', '不良点Q22', '830', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22230023', '不良点Q23', '不良点Q23', '850', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22230024', '不良点Q24', '不良点Q24', '870', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22230025', '不良点Q25', '不良点Q25', '900', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22230026', '不良点Q26', '不良点Q26', '930', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22230027', '不良点Q27', '不良点Q27', '960', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22230028', '不良点Q28', '不良点Q28', '980', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22230029', '不良点Q29', '不良点Q29', '1010', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22230030', '不良点Q30', '不良点Q30', '1030', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22230031', '不良点Q31', '不良点Q31', '1070', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22230032', '不良点Q32', '不良点Q32', '1090', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22230033', '不良点Q33', '不良点Q33', '1110', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22230034', '不良点Q34', '不良点Q34', '1150', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22230035', '不良点Q35', '不良点Q35', '1190', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300011', '电源欠相保护机能无效', '电源欠相保护机能无效', '30', '0', '0', 'Z22230001', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300012', '马达温度监控装置无效', '马达温度监控装置无效', '40', '0', '0', 'Z22230001', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300013', '其他（手写）', '其他（手写）', '50', '0', '0', 'Z22230001', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300021', '限速器轴润滑不良', '限速器轴润滑不良', '60', '0', '0', 'Z22230002', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300022', '反绳轮轴润滑不良', '反绳轮轴润滑不良', '70', '0', '0', 'Z22230002', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300023', '涨紧轮轴润滑不良', '涨紧轮轴润滑不良', '80', '0', '0', 'Z22230002', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300024', '其他（手写）', '其他（手写）', '90', '0', '0', 'Z22230002', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300031', '电源回路绝缘不良', '电源回路绝缘不良', '100', '0', '0', 'Z22230003', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300032', '电机回路绝缘不良', '电机回路绝缘不良', '110', '0', '0', 'Z22230003', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300033', '照明回路绝缘不良', '照明回路绝缘不良', '120', '0', '0', 'Z22230003', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300034', '操作回路绝缘不良', '操作回路绝缘不良', '130', '0', '0', 'Z22230003', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300035', '显示回路绝缘不良', '显示回路绝缘不良', '140', '0', '0', 'Z22230003', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300036', '保险丝规格不符', '保险丝规格不符', '150', '0', '0', 'Z22230003', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300037', '其他（手写）', '其他（手写）', '160', '0', '0', 'Z22230003', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300041', '电源电源过高', '电源电源过高', '170', '0', '0', 'Z22230004', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300042', '电源电源不足', '电源电源不足', '180', '0', '0', 'Z22230004', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300043', '其他（手写）', '其他（手写）', '190', '0', '0', 'Z22230004', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300051', '电压过高', '电压过高', '200', '0', '0', 'Z22230005', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300052', '电压不足', '电压不足', '210', '0', '0', 'Z22230005', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300053', '其他（手写）', '其他（手写）', '220', '0', '0', 'Z22230005', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300061', 'PG电缆线未单独铺设', 'PG电缆线未单独铺设', '230', '0', '0', 'Z22230006', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300062', '其他（手写）', '其他（手写）', '240', '0', '0', 'Z22230006', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300071', '未使用端子', '未使用端子', '250', '0', '0', 'Z22230007', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300072', '其他（手写）', '其他（手写）', '260', '0', '0', 'Z22230007', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300081', '不能有效平层', '不能有效平层', '270', '0', '0', 'Z22230008', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300082', '不能有效制停', '不能有效制停', '280', '0', '0', 'Z22230008', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300083', '其他（手写）', '其他（手写）', '290', '0', '0', 'Z22230008', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222300091', '轿厢在110%载重实验未符合要求', '轿厢在110%载重实验未符合要求', '300', '0', '0', 'Z22230009', '0', sysdate, '0', sysdate, '0',
   '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300092', '其他（手写）', '其他（手写）', '310', '0', '0', 'Z22230009', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300101', '安全钳不能有效制停轿厢', '安全钳不能有效制停轿厢', '320', '0', '0', 'Z22230010', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300102', '轿厢制停后，马达不能实现空转', '轿厢制停后，马达不能实现空转', '330', '0', '0', 'Z22230010', '0', sysdate, '0', sysdate, '0',
        '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300103', '其他（手写）', '其他（手写）', '340', '0', '0', 'Z22230010', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300111', '滑距不符合要求', '滑距不符合要求', '350', '0', '0', 'Z22230011', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300112', '其他（手写）', '其他（手写）', '360', '0', '0', 'Z22230011', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300121', '抱闸电压超标', '抱闸电压超标', '370', '0', '0', 'Z22230012', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300122', '其他（手写）', '其他（手写）', '380', '0', '0', 'Z22230012', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300131', '载重补偿的设定不良', '载重补偿的设定不良', '390', '0', '0', 'Z22230013', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300132', '其他（手写）', '其他（手写）', '400', '0', '0', 'Z22230013', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300141', '两台并联功能不良', '两台并联功能不良', '420', '0', '0', 'Z22230014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300142', '专用控制功能不良', '专用控制功能不良', '430', '0', '0', 'Z22230014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300143', '司机功能不良', '司机功能不良', '440', '0', '0', 'Z22230014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300144', '停电自动平层装置不良', '停电自动平层装置不良', '450', '0', '0', 'Z22230014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222300145', '轿厢内管制运行显示灯不良', '轿厢内管制运行显示灯不良', '460', '0', '0', 'Z22230014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300146', '火灾管制运行功能不良', '火灾管制运行功能不良', '470', '0', '0', 'Z22230014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222300147', '火灾管制运行回归信号触点', '火灾管制运行回归信号触点', '480', '0', '0', 'Z22230014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300148', '消防功能不良', '消防功能不良', '490', '0', '0', 'Z22230014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222300149', '光电管轿门安全触板功能不良', '光电管轿门安全触板功能不良', '500', '0', '0', 'Z22230014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z2223001410', '光幕轿门安全触板功能不良', '光幕轿门安全触板功能不良', '510', '0', '0', 'Z22230014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z2223001411', '超声波轿门安全触板功能不良', '超声波轿门安全触板功能不良', '520', '0', '0', 'Z22230014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z2223001412', '基准层回归控制功能不良', '基准层回归控制功能不良', '530', '0', '0', 'Z22230014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z2223001413', '满员通过功能不良', '满员通过功能不良', '540', '0', '0', 'Z22230014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z2223001414', '轿厢内监控（ＣＣＤ）摄像头不良', '轿厢内监控（ＣＣＤ）摄像头不良', '550', '0', '0', 'Z22230014', '0', sysdate, '0', sysdate, '0',
   '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z2223001415', 'IC卡管制功能不良', 'IC卡管制功能不良', '560', '0', '0', 'Z22230014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z2223001416', '监控盘功能不良', '监控盘功能不良', '570', '0', '0', 'Z22230014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z2223001417', '到站铃不良', '到站铃不良', '580', '0', '0', 'Z22230014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z2223001418', '轿厢内ＢＧＭ功能不良', '轿厢内ＢＧＭ功能不良', '590', '0', '0', 'Z22230014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z2223001419', '对讲机不良', '对讲机不良', '600', '0', '0', 'Z22230014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z2223001420', '其他（手写）', '其他（手写）', '610', '0', '0', 'Z22230014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300151', '系统时间无法设定完成', '系统时间无法设定完成', '620', '0', '0', 'Z22230015', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300152', '其他（手写）', '其他（手写）', '630', '0', '0', 'Z22230015', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222300161', '对重块缺失，平衡系数无法达到标准', '对重块缺失，平衡系数无法达到标准', '640', '0', '0', 'Z22230016', '0', sysdate, '0', sysdate, '0',
   '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300162', '其他（手写）', '其他（手写）', '650', '0', '0', 'Z22230016', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222300171', '100%载重时马达电流超过定额电流的1.1倍', '100%载重时马达电流超过定额电流的1.1倍', '660', '0', '0', 'Z22230017', '0', sysdate, '0',
                 sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300172', '其他（手写）', '其他（手写）', '670', '0', '0', 'Z22230017', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222300173', '110%载重时马达电流超过定额电流的1.2倍', '110%载重时马达电流超过定额电流的1.2倍', '680', '0', '0', 'Z22230017', '0', sysdate, '0',
                 sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300174', '其他（手写）', '其他（手写）', '690', '0', '0', 'Z22230017', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222300181', '额定速度的偏差超过标准范围', '额定速度的偏差超过标准范围', '700', '0', '0', 'Z22230018', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300182', '其他（手写）', '其他（手写）', '710', '0', '0', 'Z22230018', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300191', '调整不良', '调整不良', '720', '0', '0', 'Z22230019', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300192', '未调整', '未调整', '730', '0', '0', 'Z22230019', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300193', '滑动导靴损坏', '滑动导靴损坏', '740', '0', '0', 'Z22230019', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300194', '其他（手写）', '其他（手写）', '750', '0', '0', 'Z22230019', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300201', '开关缺失', '开关缺失', '760', '0', '0', 'Z22230020', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300202', '开关损坏', '开关损坏', '770', '0', '0', 'Z22230020', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222300203', '开关安装尺寸不良，不能有效动作', '开关安装尺寸不良，不能有效动作', '780', '0', '0', 'Z22230020', '0', sysdate, '0', sysdate, '0',
   '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222300204', '由于进水，开关未安装，安全回路短接', '由于进水，开关未安装，安全回路短接', '790', '0', '0', 'Z22230020', '0', sysdate, '0', sysdate,
   '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300205', '其他（手写）', '其他（手写）', '800', '0', '0', 'Z22230020', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300211', '轿门固定螺丝紧固不良', '轿门固定螺丝紧固不良', '810', '0', '0', 'Z22230021', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300212', '其他（手写）', '其他（手写）', '820', '0', '0', 'Z22230021', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300221', '安装不良', '安装不良', '830', '0', '0', 'Z22230022', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300222', '其他（手写）', '其他（手写）', '840', '0', '0', 'Z22230022', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300231', '速度不良', '速度不良', '850', '0', '0', 'Z22230023', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300232', '其他（手写）', '其他（手写）', '860', '0', '0', 'Z22230023', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300241', '平层板安装误差大', '平层板安装误差大', '870', '0', '0', 'Z22230024', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300242', '非平层板安装原因', '非平层板安装原因', '880', '0', '0', 'Z22230024', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300243', '其他（手写）', '其他（手写）', '890', '0', '0', 'Z22230024', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300251', '光电或光幕损坏', '光电或光幕损坏', '900', '0', '0', 'Z22230025', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300252', '光电或光幕未安装', '光电或光幕未安装', '910', '0', '0', 'Z22230025', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300253', '其他（手写）', '其他（手写）', '920', '0', '0', 'Z22230025', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300261', '呼梯不正常', '呼梯不正常', '930', '0', '0', 'Z22230026', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300262', '残障功能不正常', '残障功能不正常', '940', '0', '0', 'Z22230026', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300263', '其他（手写）', '其他（手写）', '950', '0', '0', 'Z22230026', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300271', '连接器缺失，手动压接', '连接器缺失，手动压接', '960', '0', '0', 'Z22230027', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300272', '其他（手写）', '其他（手写）', '970', '0', '0', 'Z22230027', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222300281', '安全触板开关的伸出量不足', '安全触板开关的伸出量不足', '980', '0', '0', 'Z22230028', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222300282', '安全触板开关的伸出量过大', '安全触板开关的伸出量过大', '990', '0', '0', 'Z22230028', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300283', '其他（手写）', '其他（手写）', '1000', '0', '0', 'Z22230028', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300291', '门刀尺寸不良', '门刀尺寸不良', '1010', '0', '0', 'Z22230029', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300292', '其他（手写）', '其他（手写）', '1020', '0', '0', 'Z22230029', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222300301', '轿门大偏芯轮的偏芯位置不良', '轿门大偏芯轮的偏芯位置不良', '1030', '0', '0', 'Z22230030', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222300302', '小偏心轮与导轨间隙不良', '小偏心轮与导轨间隙不良', '1040', '0', '0', 'Z22230030', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300304', '其他（手写）', '其他（手写）', '1060', '0', '0', 'Z22230030', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300311', '接近开关不符合要求', '接近开关不符合要求', '1070', '0', '0', 'Z22230031', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300312', '其他（手写）', '其他（手写）', '1080', '0', '0', 'Z22230031', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300321', '门机皮带张力不良', '门机皮带张力不良', '1090', '0', '0', 'Z22230032', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300322', '其他（手写）', '其他（手写）', '1100', '0', '0', 'Z22230032', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300331', '开关缺失', '开关缺失', '1110', '0', '0', 'Z22230033', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300332', '开关调整不良', '开关调整不良', '1120', '0', '0', 'Z22230033', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300333', '走线方式不好', '走线方式不好', '1130', '0', '0', 'Z22230033', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300334', '其他（手写）', '其他（手写）', '1140', '0', '0', 'Z22230033', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300341', '开关缺失', '开关缺失', '1150', '0', '0', 'Z22230034', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300342', '开关调整不良', '开关调整不良', '1160', '0', '0', 'Z22230034', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300343', '走线方式不好', '走线方式不好', '1170', '0', '0', 'Z22230034', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300344', '其他（手写）', '其他（手写）', '1180', '0', '0', 'Z22230034', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222300351', '地坎安装不一致，导致部分楼层间隙符合标准，部分楼层间隙偏大或偏小', '地坎安装不一致，导致部分楼层间隙符合标准，部分楼层间隙偏大或偏小', '1190', '0', '0', 'Z22230035',
                 '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300352', '间隙过小', '间隙过小', '1200', '0', '0', 'Z22230035', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300353', '间隙过大', '间隙过大', '1210', '0', '0', 'Z22230035', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222300354', '其他（手写）', '其他（手写）', '1220', '0', '0', 'Z22230035', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23230001', '不良点Q1', '不良点Q1', '30', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23230002', '不良点Q2', '不良点Q2', '60', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23230003', '不良点Q3', '不良点Q3', '100', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23230004', '不良点Q4', '不良点Q4', '170', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23230005', '不良点Q5', '不良点Q5', '200', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23230006', '不良点Q6', '不良点Q6', '230', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23230007', '不良点Q7', '不良点Q7', '250', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23230008', '不良点Q8', '不良点Q8', '270', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23230009', '不良点Q9', '不良点Q9', '300', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23230010', '不良点Q10', '不良点Q10', '320', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23230011', '不良点Q11', '不良点Q11', '350', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23230012', '不良点Q12', '不良点Q12', '370', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23230013', '不良点Q13', '不良点Q13', '390', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23230014', '不良点Q14', '不良点Q14', '420', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23230015', '不良点Q15', '不良点Q15', '620', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23230016', '不良点Q16', '不良点Q16', '640', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23230017', '不良点Q17', '不良点Q17', '660', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23230018', '不良点Q18', '不良点Q18', '700', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23230019', '不良点Q19', '不良点Q19', '720', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23230020', '不良点Q20', '不良点Q20', '760', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23230021', '不良点Q21', '不良点Q21', '810', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23230022', '不良点Q22', '不良点Q22', '830', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23230023', '不良点Q23', '不良点Q23', '850', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23230024', '不良点Q24', '不良点Q24', '870', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23230025', '不良点Q25', '不良点Q25', '900', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23230026', '不良点Q26', '不良点Q26', '930', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23230027', '不良点Q27', '不良点Q27', '960', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23230028', '不良点Q28', '不良点Q28', '980', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23230029', '不良点Q29', '不良点Q29', '1010', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23230030', '不良点Q30', '不良点Q30', '1030', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23230031', '不良点Q31', '不良点Q31', '1070', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23230032', '不良点Q32', '不良点Q32', '1090', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23230033', '不良点Q33', '不良点Q33', '1110', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23230034', '不良点Q34', '不良点Q34', '1150', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23230035', '不良点Q35', '不良点Q35', '1190', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232300011', '调试员以故障报告形式反馈工厂', '调试员以故障报告形式反馈工厂', '30', '0', '0', 'Z23230001', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300013', '其他（手写）', '其他（手写）', '50', '0', '0', 'Z23230001', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300021', '安装责任者整改', '安装责任者整改', '60', '0', '0', 'Z23230002', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300024', '其他（手写）', '其他（手写）', '90', '0', '0', 'Z23230002', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232300031', '原因不明，故障报告反馈，并寻求支援', '原因不明，故障报告反馈，并寻求支援', '100', '0', '0', 'Z23230003', '0', sysdate, '0', sysdate,
   '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300037', '其他（手写）', '其他（手写）', '160', '0', '0', 'Z23230003', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300041', '要求甲方调整电源电压', '要求甲方调整电源电压', '170', '0', '0', 'Z23230004', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300043', '其他（手写）', '其他（手写）', '190', '0', '0', 'Z23230004', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300053', '其他（手写）', '其他（手写）', '220', '0', '0', 'Z23230005', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300061', '安装责任者整改', '安装责任者整改', '230', '0', '0', 'Z23230006', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300062', '其他（手写）', '其他（手写）', '240', '0', '0', 'Z23230006', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300071', '安装责任者整改', '安装责任者整改', '250', '0', '0', 'Z23230007', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300072', '其他（手写）', '其他（手写）', '260', '0', '0', 'Z23230007', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232300081', '电梯禁用，原因不明，故障报告反馈，并寻求支援', '电梯禁用，原因不明，故障报告反馈，并寻求支援', '270', '0', '0', 'Z23230008', '0', sysdate, '0',
                 sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232300082', '电梯禁用，抱闸不良，故障报告反馈，相关部门后续处理', '电梯禁用，抱闸不良，故障报告反馈，相关部门后续处理', '280', '0', '0', 'Z23230008', '0', sysdate,
                 '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300083', '其他（手写）', '其他（手写）', '290', '0', '0', 'Z23230008', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232300091', '电梯禁用，原因不明，故障报告反馈，并寻求支援', '电梯禁用，原因不明，故障报告反馈，并寻求支援', '300', '0', '0', 'Z23230009', '0', sysdate, '0',
                 sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300092', '其他（手写）', '其他（手写）', '310', '0', '0', 'Z23230009', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300101', '安装责任者整改', '安装责任者整改', '320', '0', '0', 'Z23230010', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232300102', '原因不明，故障报告反馈，并寻求支援', '原因不明，故障报告反馈，并寻求支援', '330', '0', '0', 'Z23230010', '0', sysdate, '0', sysdate,
   '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300103', '其他（手写）', '其他（手写）', '340', '0', '0', 'Z23230010', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232300111', '电梯禁用，抱闸不良，故障报告反馈，相关部门后续处理', '电梯禁用，抱闸不良，故障报告反馈，相关部门后续处理', '350', '0', '0', 'Z23230011', '0', sysdate,
                 '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300112', '其他（手写）', '其他（手写）', '360', '0', '0', 'Z23230011', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300121', '调试员以故障报告形式反馈工厂', '调试员以故障报告形式反馈工厂', '370', '0', '0', 'Z23230012', '0', sysdate, '0', sysdate, '0',
        '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300122', '其他（手写）', '其他（手写）', '380', '0', '0', 'Z23230012', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232300131', '原因不明，故障报告反馈，并寻求支援', '原因不明，故障报告反馈，并寻求支援', '390', '0', '0', 'Z23230013', '0', sysdate, '0', sysdate,
   '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300132', '其他（手写）', '其他（手写）', '400', '0', '0', 'Z23230013', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232300141', '原因不明，故障报告反馈，并寻求支援', '原因不明，故障报告反馈，并寻求支援', '420', '0', '0', 'Z23230014', '0', sysdate, '0', sysdate,
   '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z2323001420', '其他（手写）', '其他（手写）', '610', '0', '0', 'Z23230014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232300151', '原因不明，故障报告反馈，并寻求支援', '原因不明，故障报告反馈，并寻求支援', '620', '0', '0', 'Z23230015', '0', sysdate, '0', sysdate,
   '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300152', '其他（手写）', '其他（手写）', '630', '0', '0', 'Z23230015', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232300161', '由责任方故障处理或购买补齐部品后重新申请调试', '由责任方故障处理或购买补齐部品后重新申请调试', '640', '0', '0', 'Z23230016', '0', sysdate, '0',
                 sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300162', '其他（手写）', '其他（手写）', '650', '0', '0', 'Z23230016', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300171', '相关部门确认', '相关部门确认', '660', '0', '0', 'Z23230017', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300172', '其他（手写）', '其他（手写）', '670', '0', '0', 'Z23230017', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300173', '相关部门确认', '相关部门确认', '680', '0', '0', 'Z23230017', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300174', '其他（手写）', '其他（手写）', '690', '0', '0', 'Z23230017', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300181', '相关部门确认', '相关部门确认', '700', '0', '0', 'Z23230018', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300182', '其他（手写）', '其他（手写）', '710', '0', '0', 'Z23230018', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232300191', '由责任方故障处理或购买补齐部品', '由责任方故障处理或购买补齐部品', '720', '0', '0', 'Z23230019', '0', sysdate, '0', sysdate, '0',
   '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300192', '调试员寻求支援整改', '调试员寻求支援整改', '730', '0', '0', 'Z23230019', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300194', '其他（手写）', '其他（手写）', '750', '0', '0', 'Z23230019', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232300201', '由责任方故障处理或购买补齐部品', '由责任方故障处理或购买补齐部品', '760', '0', '0', 'Z23230020', '0', sysdate, '0', sysdate, '0',
   '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300202', '安装责任者整改', '安装责任者整改', '770', '0', '0', 'Z23230020', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232300203', '进水不可使用，水干后安装责任者装好开关', '进水不可使用，水干后安装责任者装好开关', '780', '0', '0', 'Z23230020', '0', sysdate, '0', sysdate,
   '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300205', '其他（手写）', '其他（手写）', '800', '0', '0', 'Z23230020', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300211', '安装责任者整改', '安装责任者整改', '810', '0', '0', 'Z23230021', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300212', '其他（手写）', '其他（手写）', '820', '0', '0', 'Z23230021', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300221', '安装责任者整改', '安装责任者整改', '830', '0', '0', 'Z23230022', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300222', '其他（手写）', '其他（手写）', '840', '0', '0', 'Z23230022', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232300231', '原因不明，故障报告反馈，并寻求支援', '原因不明，故障报告反馈，并寻求支援', '850', '0', '0', 'Z23230023', '0', sysdate, '0', sysdate,
   '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300232', '其他（手写）', '其他（手写）', '860', '0', '0', 'Z23230023', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300241', '安装责任者整改', '安装责任者整改', '870', '0', '0', 'Z23230024', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232300242', '原因不明，故障报告反馈，并寻求支援', '原因不明，故障报告反馈，并寻求支援', '880', '0', '0', 'Z23230024', '0', sysdate, '0', sysdate,
   '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300243', '其他（手写）', '其他（手写）', '890', '0', '0', 'Z23230024', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232300251', '由责任方故障处理或购买补齐部品', '由责任方故障处理或购买补齐部品', '900', '0', '0', 'Z23230025', '0', sysdate, '0', sysdate, '0',
   '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300252', '安装责任者整改', '安装责任者整改', '910', '0', '0', 'Z23230025', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300253', '其他（手写）', '其他（手写）', '920', '0', '0', 'Z23230025', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232300261', '原因不明，故障报告反馈，并寻求支援', '原因不明，故障报告反馈，并寻求支援', '930', '0', '0', 'Z23230026', '0', sysdate, '0', sysdate,
   '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300263', '其他（手写）', '其他（手写）', '950', '0', '0', 'Z23230026', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232300271', '由责任方故障处理或购买补齐部品', '由责任方故障处理或购买补齐部品', '960', '0', '0', 'Z23230027', '0', sysdate, '0', sysdate, '0',
   '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300272', '其他（手写）', '其他（手写）', '970', '0', '0', 'Z23230027', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300281', '安装责任者整改', '安装责任者整改', '980', '0', '0', 'Z23230028', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300283', '其他（手写）', '其他（手写）', '1000', '0', '0', 'Z23230028', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300291', '安装责任者整改', '安装责任者整改', '1010', '0', '0', 'Z23230029', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300292', '其他（手写）', '其他（手写）', '1020', '0', '0', 'Z23230029', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300301', '安装责任者整改', '安装责任者整改', '1030', '0', '0', 'Z23230030', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300304', '其他（手写）', '其他（手写）', '1060', '0', '0', 'Z23230030', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300311', '安装责任者整改', '安装责任者整改', '1070', '0', '0', 'Z23230031', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300312', '其他（手写）', '其他（手写）', '1080', '0', '0', 'Z23230031', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300321', '安装责任者整改', '安装责任者整改', '1090', '0', '0', 'Z23230032', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300322', '其他（手写）', '其他（手写）', '1100', '0', '0', 'Z23230032', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232300331', '由责任方故障处理或购买补齐部品', '由责任方故障处理或购买补齐部品', '1110', '0', '0', 'Z23230033', '0', sysdate, '0', sysdate, '0',
   '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300332', '安装责任者整改', '安装责任者整改', '1120', '0', '0', 'Z23230033', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300334', '其他（手写）', '其他（手写）', '1140', '0', '0', 'Z23230033', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232300341', '由责任方故障处理或购买补齐部品', '由责任方故障处理或购买补齐部品', '1150', '0', '0', 'Z23230034', '0', sysdate, '0', sysdate, '0',
   '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300342', '安装责任者整改', '安装责任者整改', '1160', '0', '0', 'Z23230034', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300344', '其他（手写）', '其他（手写）', '1180', '0', '0', 'Z23230034', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300351', '安装责任者整改', '安装责任者整改', '1190', '0', '0', 'Z23230035', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232300354', '其他（手写）', '其他（手写）', '1220', '0', '0', 'Z23230035', '0', sysdate, '0', sysdate, '0', '0');
