INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21280001', '部品B1', '部品B1', '30', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21280002', '部品B2', '部品B2', '60', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21280003', '部品B3', '部品B3', '100', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21280004', '部品B4', '部品B4', '170', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21280005', '部品B5', '部品B5', '200', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21280006', '部品B6', '部品B6', '230', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21280007', '部品B7', '部品B7', '250', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21280008', '部品B8', '部品B8', '270', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21280009', '部品B9', '部品B9', '300', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21280010', '部品B10', '部品B10', '320', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21280011', '部品B11', '部品B11', '350', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21280012', '部品B12', '部品B12', '370', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21280013', '部品B13', '部品B13', '390', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21280014', '部品B14', '部品B14', '410', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21280015', '部品B15', '部品B15', '610', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21280016', '部品B16', '部品B16', '630', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21280017', '部品B17', '部品B17', '650', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21280018', '部品B18', '部品B18', '690', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21280019', '部品B19', '部品B19', '710', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21280020', '部品B20', '部品B20', '750', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21280021', '部品B21', '部品B21', '800', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21280022', '部品B22', '部品B22', '820', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21280023', '部品B23', '部品B23', '840', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21280024', '部品B24', '部品B24', '860', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21280025', '部品B25', '部品B25', '890', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21280026', '部品B26', '部品B26', '920', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21280027', '部品B27', '部品B27', '950', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21280028', '部品B28', '部品B28', '970', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21280029', '部品B29', '部品B29', '1000', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21280030', '部品B30', '部品B30', '1020', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21280031', '部品B31', '部品B31', '1060', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21280032', '部品B32', '部品B32', '1080', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21280033', '部品B33', '部品B33', '1100', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21280034', '部品B34', '部品B34', '1140', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21280035', '部品B35', '部品B35', '1180', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212800011', '控制柜', '控制柜', '30', '0', '0', 'Z21280001', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212800012', '马达', '马达', '40', '0', '0', 'Z21280001', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212800021', '限速器', '限速器', '60', '0', '0', 'Z21280002', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212800022', '反绳轮', '反绳轮', '70', '0', '0', 'Z21280002', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212800023', '涨紧轮', '涨紧轮', '80', '0', '0', 'Z21280002', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212800061', 'PG', 'PG', '230', '0', '0', 'Z21280006', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212800071', '马达', '马达', '250', '0', '0', 'Z21280007', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212800111', '制动器', '制动器', '350', '0', '0', 'Z21280011', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212800121', '控制柜', '控制柜', '370', '0', '0', 'Z21280012', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212800191', '轿厢滚轮导靴', '轿厢滚轮导靴', '710', '0', '0', 'Z21280019', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212800192', '对重滚轮导靴', '对重滚轮导靴', '720', '0', '0', 'Z21280019', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212800211', '轿门', '轿门', '800', '0', '0', 'Z21280021', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212800212', '轿门', '轿门', '810', '0', '0', 'Z21280021', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212800221', '轿门', '轿门', '820', '0', '0', 'Z21280022', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212800222', '厅门', '厅门', '830', '0', '0', 'Z21280022', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212800231', '轿门', '轿门', '840', '0', '0', 'Z21280023', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212800232', '厅门', '厅门', '850', '0', '0', 'Z21280023', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212800251', '门光电', '门光电', '890', '0', '0', 'Z21280025', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212800252', '门关幕', '门关幕', '900', '0', '0', 'Z21280025', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212800281', '安全触板', '安全触板', '970', '0', '0', 'Z21280028', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212800291', '门刀', '门刀', '1000', '0', '0', 'Z21280029', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212800301', '轿门大偏心轮', '轿门大偏心轮', '1020', '0', '0', 'Z21280030', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212800303', '轿门小偏心轮', '轿门小偏心轮', '1040', '0', '0', 'Z21280030', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212800311', '轿门接近开关', '轿门接近开关', '1060', '0', '0', 'Z21280031', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212800321', '门机皮带', '门机皮带', '1080', '0', '0', 'Z21280032', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212800331', '安全触板', '安全触板', '1100', '0', '0', 'Z21280033', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212800341', '轿门开关', '轿门开关', '1140', '0', '0', 'Z21280034', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212800351', '门刀', '门刀', '1180', '0', '0', 'Z21280035', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22280001', '不良点Q1', '不良点Q1', '30', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22280002', '不良点Q2', '不良点Q2', '60', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22280003', '不良点Q3', '不良点Q3', '100', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22280004', '不良点Q4', '不良点Q4', '170', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22280005', '不良点Q5', '不良点Q5', '200', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22280006', '不良点Q6', '不良点Q6', '230', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22280007', '不良点Q7', '不良点Q7', '250', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22280008', '不良点Q8', '不良点Q8', '270', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22280009', '不良点Q9', '不良点Q9', '300', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22280010', '不良点Q10', '不良点Q10', '320', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22280011', '不良点Q11', '不良点Q11', '350', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22280012', '不良点Q12', '不良点Q12', '370', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22280013', '不良点Q13', '不良点Q13', '390', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22280014', '不良点Q14', '不良点Q14', '410', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22280015', '不良点Q15', '不良点Q15', '610', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22280016', '不良点Q16', '不良点Q16', '630', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22280017', '不良点Q17', '不良点Q17', '650', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22280018', '不良点Q18', '不良点Q18', '690', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22280019', '不良点Q19', '不良点Q19', '710', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22280020', '不良点Q20', '不良点Q20', '750', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22280021', '不良点Q21', '不良点Q21', '800', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22280022', '不良点Q22', '不良点Q22', '820', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22280023', '不良点Q23', '不良点Q23', '840', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22280024', '不良点Q24', '不良点Q24', '860', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22280025', '不良点Q25', '不良点Q25', '890', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22280026', '不良点Q26', '不良点Q26', '920', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22280027', '不良点Q27', '不良点Q27', '950', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22280028', '不良点Q28', '不良点Q28', '970', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22280029', '不良点Q29', '不良点Q29', '1000', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22280030', '不良点Q30', '不良点Q30', '1020', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22280031', '不良点Q31', '不良点Q31', '1060', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22280032', '不良点Q32', '不良点Q32', '1080', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22280033', '不良点Q33', '不良点Q33', '1100', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22280034', '不良点Q34', '不良点Q34', '1140', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22280035', '不良点Q35', '不良点Q35', '1180', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800011', '电源欠相保护机能无效', '电源欠相保护机能无效', '30', '0', '0', 'Z22280001', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800012', '马达温度监控装置无效', '马达温度监控装置无效', '40', '0', '0', 'Z22280001', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800013', '其他（手写）', '其他（手写）', '50', '0', '0', 'Z22280001', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800021', '限速器轴润滑不良', '限速器轴润滑不良', '60', '0', '0', 'Z22280002', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800022', '反绳轮轴润滑不良', '反绳轮轴润滑不良', '70', '0', '0', 'Z22280002', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800023', '涨紧轮轴润滑不良', '涨紧轮轴润滑不良', '80', '0', '0', 'Z22280002', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800024', '其他（手写）', '其他（手写）', '90', '0', '0', 'Z22280002', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800031', '电源回路绝缘不良', '电源回路绝缘不良', '100', '0', '0', 'Z22280003', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800032', '电机回路绝缘不良', '电机回路绝缘不良', '110', '0', '0', 'Z22280003', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800033', '照明回路绝缘不良', '照明回路绝缘不良', '120', '0', '0', 'Z22280003', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800034', '操作回路绝缘不良', '操作回路绝缘不良', '130', '0', '0', 'Z22280003', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800035', '显示回路绝缘不良', '显示回路绝缘不良', '140', '0', '0', 'Z22280003', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800036', '保险丝规格不符', '保险丝规格不符', '150', '0', '0', 'Z22280003', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800037', '其他（手写）', '其他（手写）', '160', '0', '0', 'Z22280003', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800041', '电源电源过高', '电源电源过高', '170', '0', '0', 'Z22280004', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800042', '电源电源不足', '电源电源不足', '180', '0', '0', 'Z22280004', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800043', '其他（手写）', '其他（手写）', '190', '0', '0', 'Z22280004', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800051', '电压过高', '电压过高', '200', '0', '0', 'Z22280005', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800052', '电压不足', '电压不足', '210', '0', '0', 'Z22280005', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800053', '其他（手写）', '其他（手写）', '220', '0', '0', 'Z22280005', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800061', 'PG电缆线未单独铺设', 'PG电缆线未单独铺设', '230', '0', '0', 'Z22280006', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800062', '其他（手写）', '其他（手写）', '240', '0', '0', 'Z22280006', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800071', '未使用端子', '未使用端子', '250', '0', '0', 'Z22280007', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800072', '其他（手写）', '其他（手写）', '260', '0', '0', 'Z22280007', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800081', '不能有效平层', '不能有效平层', '270', '0', '0', 'Z22280008', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800082', '不能有效制停', '不能有效制停', '280', '0', '0', 'Z22280008', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800083', '其他（手写）', '其他（手写）', '290', '0', '0', 'Z22280008', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222800091', '轿厢在110%载重实验未符合要求', '轿厢在110%载重实验未符合要求', '300', '0', '0', 'Z22280009', '0', sysdate, '0', sysdate, '0',
   '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800092', '其他（手写）', '其他（手写）', '310', '0', '0', 'Z22280009', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800101', '安全钳不能有效制停轿厢', '安全钳不能有效制停轿厢', '320', '0', '0', 'Z22280010', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800102', '轿厢制停后，马达不能实现空转', '轿厢制停后，马达不能实现空转', '330', '0', '0', 'Z22280010', '0', sysdate, '0', sysdate, '0',
        '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800103', '其他（手写）', '其他（手写）', '340', '0', '0', 'Z22280010', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800111', '滑距不符合要求', '滑距不符合要求', '350', '0', '0', 'Z22280011', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800112', '其他（手写）', '其他（手写）', '360', '0', '0', 'Z22280011', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800121', '抱闸电压超标', '抱闸电压超标', '370', '0', '0', 'Z22280012', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800122', '其他（手写）', '其他（手写）', '380', '0', '0', 'Z22280012', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800131', '载重补偿的设定不良', '载重补偿的设定不良', '390', '0', '0', 'Z22280013', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800132', '其他（手写）', '其他（手写）', '400', '0', '0', 'Z22280013', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800141', '两台并联功能不良', '两台并联功能不良', '410', '0', '0', 'Z22280014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800142', '专用控制功能不良', '专用控制功能不良', '420', '0', '0', 'Z22280014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800143', '司机功能不良', '司机功能不良', '430', '0', '0', 'Z22280014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800144', '停电自动平层装置不良', '停电自动平层装置不良', '440', '0', '0', 'Z22280014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222800145', '轿厢内管制运行显示灯不良', '轿厢内管制运行显示灯不良', '450', '0', '0', 'Z22280014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800146', '火灾管制运行功能不良', '火灾管制运行功能不良', '460', '0', '0', 'Z22280014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222800147', '火灾管制运行回归信号触点', '火灾管制运行回归信号触点', '470', '0', '0', 'Z22280014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800148', '消防功能不良', '消防功能不良', '480', '0', '0', 'Z22280014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222800149', '光电管轿门安全触板功能不良', '光电管轿门安全触板功能不良', '490', '0', '0', 'Z22280014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z2228001410', '光幕轿门安全触板功能不良', '光幕轿门安全触板功能不良', '500', '0', '0', 'Z22280014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z2228001411', '超声波轿门安全触板功能不良', '超声波轿门安全触板功能不良', '510', '0', '0', 'Z22280014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z2228001412', '基准层回归控制功能不良', '基准层回归控制功能不良', '520', '0', '0', 'Z22280014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z2228001413', '满员通过功能不良', '满员通过功能不良', '530', '0', '0', 'Z22280014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z2228001414', '轿厢内监控（ＣＣＤ）摄像头不良', '轿厢内监控（ＣＣＤ）摄像头不良', '540', '0', '0', 'Z22280014', '0', sysdate, '0', sysdate, '0',
   '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z2228001415', 'IC卡管制功能不良', 'IC卡管制功能不良', '550', '0', '0', 'Z22280014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z2228001416', '监控盘功能不良', '监控盘功能不良', '560', '0', '0', 'Z22280014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z2228001417', '到站铃不良', '到站铃不良', '570', '0', '0', 'Z22280014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z2228001418', '轿厢内ＢＧＭ功能不良', '轿厢内ＢＧＭ功能不良', '580', '0', '0', 'Z22280014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z2228001419', '对讲机不良', '对讲机不良', '590', '0', '0', 'Z22280014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z2228001420', '其他（手写）', '其他（手写）', '600', '0', '0', 'Z22280014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800151', '系统时间无法设定完成', '系统时间无法设定完成', '610', '0', '0', 'Z22280015', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800152', '其他（手写）', '其他（手写）', '620', '0', '0', 'Z22280015', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222800161', '对重块缺失，平衡系数无法达到标准', '对重块缺失，平衡系数无法达到标准', '630', '0', '0', 'Z22280016', '0', sysdate, '0', sysdate, '0',
   '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800162', '其他（手写）', '其他（手写）', '640', '0', '0', 'Z22280016', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222800171', '100%载重时马达电流超过定额电流的1.1倍', '100%载重时马达电流超过定额电流的1.1倍', '650', '0', '0', 'Z22280017', '0', sysdate, '0',
                 sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800172', '其他（手写）', '其他（手写）', '660', '0', '0', 'Z22280017', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222800173', '110%载重时马达电流超过定额电流的1.2倍', '110%载重时马达电流超过定额电流的1.2倍', '670', '0', '0', 'Z22280017', '0', sysdate, '0',
                 sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800174', '其他（手写）', '其他（手写）', '680', '0', '0', 'Z22280017', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222800181', '额定速度的偏差超过标准范围', '额定速度的偏差超过标准范围', '690', '0', '0', 'Z22280018', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800182', '其他（手写）', '其他（手写）', '700', '0', '0', 'Z22280018', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800191', '调整不良', '调整不良', '710', '0', '0', 'Z22280019', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800192', '未调整', '未调整', '720', '0', '0', 'Z22280019', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800193', '滚轮导靴损坏', '滚轮导靴损坏', '730', '0', '0', 'Z22280019', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800194', '其他（手写）', '其他（手写）', '740', '0', '0', 'Z22280019', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800201', '开关缺失', '开关缺失', '750', '0', '0', 'Z22280020', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800202', '开关损坏', '开关损坏', '760', '0', '0', 'Z22280020', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222800203', '开关安装尺寸不良，不能有效动作', '开关安装尺寸不良，不能有效动作', '770', '0', '0', 'Z22280020', '0', sysdate, '0', sysdate, '0',
   '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222800204', '由于进水，开关未安装，安全回路短接', '由于进水，开关未安装，安全回路短接', '780', '0', '0', 'Z22280020', '0', sysdate, '0', sysdate,
   '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800205', '其他（手写）', '其他（手写）', '790', '0', '0', 'Z22280020', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800211', '轿门固定螺丝紧固不良', '轿门固定螺丝紧固不良', '800', '0', '0', 'Z22280021', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800212', '其他（手写）', '其他（手写）', '810', '0', '0', 'Z22280021', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800221', '安装不良', '安装不良', '820', '0', '0', 'Z22280022', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800222', '其他（手写）', '其他（手写）', '830', '0', '0', 'Z22280022', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800231', '速度不良', '速度不良', '840', '0', '0', 'Z22280023', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800232', '其他（手写）', '其他（手写）', '850', '0', '0', 'Z22280023', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800241', '平层板安装误差大', '平层板安装误差大', '860', '0', '0', 'Z22280024', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800242', '非平层板安装原因', '非平层板安装原因', '870', '0', '0', 'Z22280024', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800243', '其他（手写）', '其他（手写）', '880', '0', '0', 'Z22280024', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800251', '光电或光幕损坏', '光电或光幕损坏', '890', '0', '0', 'Z22280025', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800252', '光电或光幕未安装', '光电或光幕未安装', '900', '0', '0', 'Z22280025', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800253', '其他（手写）', '其他（手写）', '910', '0', '0', 'Z22280025', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800261', '呼梯不正常', '呼梯不正常', '920', '0', '0', 'Z22280026', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800262', '残障功能不正常', '残障功能不正常', '930', '0', '0', 'Z22280026', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800263', '其他（手写）', '其他（手写）', '940', '0', '0', 'Z22280026', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800271', '连接器缺失，手动压接', '连接器缺失，手动压接', '950', '0', '0', 'Z22280027', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800272', '其他（手写）', '其他（手写）', '960', '0', '0', 'Z22280027', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222800281', '安全触板开关的伸出量不足', '安全触板开关的伸出量不足', '970', '0', '0', 'Z22280028', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222800282', '安全触板开关的伸出量过大', '安全触板开关的伸出量过大', '980', '0', '0', 'Z22280028', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800283', '其他（手写）', '其他（手写）', '990', '0', '0', 'Z22280028', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800291', '门刀尺寸不良', '门刀尺寸不良', '1000', '0', '0', 'Z22280029', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800292', '其他（手写）', '其他（手写）', '1010', '0', '0', 'Z22280029', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222800301', '轿门大偏芯轮的偏芯位置不良', '轿门大偏芯轮的偏芯位置不良', '1020', '0', '0', 'Z22280030', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222800302', '小偏心轮与导轨间隙不良', '小偏心轮与导轨间隙不良', '1030', '0', '0', 'Z22280030', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800304', '其他（手写）', '其他（手写）', '1050', '0', '0', 'Z22280030', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800311', '接近开关不符合要求', '接近开关不符合要求', '1060', '0', '0', 'Z22280031', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800312', '其他（手写）', '其他（手写）', '1070', '0', '0', 'Z22280031', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800321', '门机皮带张力不良', '门机皮带张力不良', '1080', '0', '0', 'Z22280032', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800322', '其他（手写）', '其他（手写）', '1090', '0', '0', 'Z22280032', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800331', '开关缺失', '开关缺失', '1100', '0', '0', 'Z22280033', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800332', '开关调整不良', '开关调整不良', '1110', '0', '0', 'Z22280033', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800333', '走线方式不好', '走线方式不好', '1120', '0', '0', 'Z22280033', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800334', '其他（手写）', '其他（手写）', '1130', '0', '0', 'Z22280033', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800341', '开关缺失', '开关缺失', '1140', '0', '0', 'Z22280034', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800342', '开关调整不良', '开关调整不良', '1150', '0', '0', 'Z22280034', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800343', '走线方式不好', '走线方式不好', '1160', '0', '0', 'Z22280034', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800344', '其他（手写）', '其他（手写）', '1170', '0', '0', 'Z22280034', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z222800351', '地坎安装不一致，导致部分楼层间隙符合标准，部分楼层间隙偏大或偏小', '地坎安装不一致，导致部分楼层间隙符合标准，部分楼层间隙偏大或偏小', '1180', '0', '0', 'Z22280035',
                 '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800352', '间隙过小', '间隙过小', '1190', '0', '0', 'Z22280035', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800353', '间隙过大', '间隙过大', '1200', '0', '0', 'Z22280035', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222800354', '其他（手写）', '其他（手写）', '1210', '0', '0', 'Z22280035', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23280001', '不良点Q1', '不良点Q1', '30', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23280002', '不良点Q2', '不良点Q2', '60', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23280003', '不良点Q3', '不良点Q3', '100', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23280004', '不良点Q4', '不良点Q4', '170', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23280005', '不良点Q5', '不良点Q5', '200', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23280006', '不良点Q6', '不良点Q6', '230', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23280007', '不良点Q7', '不良点Q7', '250', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23280008', '不良点Q8', '不良点Q8', '270', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23280009', '不良点Q9', '不良点Q9', '300', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23280010', '不良点Q10', '不良点Q10', '320', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23280011', '不良点Q11', '不良点Q11', '350', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23280012', '不良点Q12', '不良点Q12', '370', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23280013', '不良点Q13', '不良点Q13', '390', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23280014', '不良点Q14', '不良点Q14', '410', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23280015', '不良点Q15', '不良点Q15', '610', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23280016', '不良点Q16', '不良点Q16', '630', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23280017', '不良点Q17', '不良点Q17', '650', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23280018', '不良点Q18', '不良点Q18', '690', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23280019', '不良点Q19', '不良点Q19', '710', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23280020', '不良点Q20', '不良点Q20', '750', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23280021', '不良点Q21', '不良点Q21', '800', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23280022', '不良点Q22', '不良点Q22', '820', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23280023', '不良点Q23', '不良点Q23', '840', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23280024', '不良点Q24', '不良点Q24', '860', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23280025', '不良点Q25', '不良点Q25', '890', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23280026', '不良点Q26', '不良点Q26', '920', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23280027', '不良点Q27', '不良点Q27', '950', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23280028', '不良点Q28', '不良点Q28', '970', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23280029', '不良点Q29', '不良点Q29', '1000', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23280030', '不良点Q30', '不良点Q30', '1020', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23280031', '不良点Q31', '不良点Q31', '1060', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23280032', '不良点Q32', '不良点Q32', '1080', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23280033', '不良点Q33', '不良点Q33', '1100', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23280034', '不良点Q34', '不良点Q34', '1140', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23280035', '不良点Q35', '不良点Q35', '1180', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232800011', '调试员以故障报告形式反馈工厂', '调试员以故障报告形式反馈工厂', '30', '0', '0', 'Z23280001', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800013', '其他（手写）', '其他（手写）', '50', '0', '0', 'Z23280001', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800021', '安装责任者整改', '安装责任者整改', '60', '0', '0', 'Z23280002', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800024', '其他（手写）', '其他（手写）', '90', '0', '0', 'Z23280002', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232800031', '原因不明，故障报告反馈，并寻求支援', '原因不明，故障报告反馈，并寻求支援', '100', '0', '0', 'Z23280003', '0', sysdate, '0', sysdate,
   '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800037', '其他（手写）', '其他（手写）', '160', '0', '0', 'Z23280003', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800041', '要求甲方调整电源电压', '要求甲方调整电源电压', '170', '0', '0', 'Z23280004', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800043', '其他（手写）', '其他（手写）', '190', '0', '0', 'Z23280004', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800053', '其他（手写）', '其他（手写）', '220', '0', '0', 'Z23280005', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800061', '安装责任者整改', '安装责任者整改', '230', '0', '0', 'Z23280006', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800062', '其他（手写）', '其他（手写）', '240', '0', '0', 'Z23280006', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800071', '安装责任者整改', '安装责任者整改', '250', '0', '0', 'Z23280007', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800072', '其他（手写）', '其他（手写）', '260', '0', '0', 'Z23280007', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232800081', '电梯禁用，原因不明，故障报告反馈，并寻求支援', '电梯禁用，原因不明，故障报告反馈，并寻求支援', '270', '0', '0', 'Z23280008', '0', sysdate, '0',
                 sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232800082', '电梯禁用，抱闸不良，故障报告反馈，相关部门后续处理', '电梯禁用，抱闸不良，故障报告反馈，相关部门后续处理', '280', '0', '0', 'Z23280008', '0', sysdate,
                 '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800083', '其他（手写）', '其他（手写）', '290', '0', '0', 'Z23280008', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232800091', '电梯禁用，原因不明，故障报告反馈，并寻求支援', '电梯禁用，原因不明，故障报告反馈，并寻求支援', '300', '0', '0', 'Z23280009', '0', sysdate, '0',
                 sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800092', '其他（手写）', '其他（手写）', '310', '0', '0', 'Z23280009', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800101', '安装责任者整改', '安装责任者整改', '320', '0', '0', 'Z23280010', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232800102', '原因不明，故障报告反馈，并寻求支援', '原因不明，故障报告反馈，并寻求支援', '330', '0', '0', 'Z23280010', '0', sysdate, '0', sysdate,
   '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800103', '其他（手写）', '其他（手写）', '340', '0', '0', 'Z23280010', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232800111', '电梯禁用，抱闸不良，故障报告反馈，相关部门后续处理', '电梯禁用，抱闸不良，故障报告反馈，相关部门后续处理', '350', '0', '0', 'Z23280011', '0', sysdate,
                 '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800112', '其他（手写）', '其他（手写）', '360', '0', '0', 'Z23280011', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800121', '调试员以故障报告形式反馈工厂', '调试员以故障报告形式反馈工厂', '370', '0', '0', 'Z23280012', '0', sysdate, '0', sysdate, '0',
        '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800122', '其他（手写）', '其他（手写）', '380', '0', '0', 'Z23280012', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232800131', '原因不明，故障报告反馈，并寻求支援', '原因不明，故障报告反馈，并寻求支援', '390', '0', '0', 'Z23280013', '0', sysdate, '0', sysdate,
   '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800132', '其他（手写）', '其他（手写）', '400', '0', '0', 'Z23280013', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232800141', '原因不明，故障报告反馈，并寻求支援', '原因不明，故障报告反馈，并寻求支援', '410', '0', '0', 'Z23280014', '0', sysdate, '0', sysdate,
   '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z2328001420', '其他（手写）', '其他（手写）', '600', '0', '0', 'Z23280014', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232800151', '原因不明，故障报告反馈，并寻求支援', '原因不明，故障报告反馈，并寻求支援', '610', '0', '0', 'Z23280015', '0', sysdate, '0', sysdate,
   '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800152', '其他（手写）', '其他（手写）', '620', '0', '0', 'Z23280015', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232800161', '由责任方故障处理或购买补齐部品后重新申请调试', '由责任方故障处理或购买补齐部品后重新申请调试', '630', '0', '0', 'Z23280016', '0', sysdate, '0',
                 sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800162', '其他（手写）', '其他（手写）', '640', '0', '0', 'Z23280016', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800171', '相关部门确认', '相关部门确认', '650', '0', '0', 'Z23280017', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800172', '其他（手写）', '其他（手写）', '660', '0', '0', 'Z23280017', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800173', '相关部门确认', '相关部门确认', '670', '0', '0', 'Z23280017', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800174', '其他（手写）', '其他（手写）', '680', '0', '0', 'Z23280017', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800181', '相关部门确认', '相关部门确认', '690', '0', '0', 'Z23280018', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800182', '其他（手写）', '其他（手写）', '700', '0', '0', 'Z23280018', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232800191', '由责任方故障处理或购买补齐部品', '由责任方故障处理或购买补齐部品', '710', '0', '0', 'Z23280019', '0', sysdate, '0', sysdate, '0',
   '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800192', '调试员寻求支援整改', '调试员寻求支援整改', '720', '0', '0', 'Z23280019', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800194', '其他（手写）', '其他（手写）', '740', '0', '0', 'Z23280019', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232800201', '由责任方故障处理或购买补齐部品', '由责任方故障处理或购买补齐部品', '750', '0', '0', 'Z23280020', '0', sysdate, '0', sysdate, '0',
   '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800202', '安装责任者整改', '安装责任者整改', '760', '0', '0', 'Z23280020', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232800203', '进水不可使用，水干后安装责任者装好开关', '进水不可使用，水干后安装责任者装好开关', '770', '0', '0', 'Z23280020', '0', sysdate, '0', sysdate,
   '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800205', '其他（手写）', '其他（手写）', '790', '0', '0', 'Z23280020', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800211', '安装责任者整改', '安装责任者整改', '800', '0', '0', 'Z23280021', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800212', '其他（手写）', '其他（手写）', '810', '0', '0', 'Z23280021', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800221', '安装责任者整改', '安装责任者整改', '820', '0', '0', 'Z23280022', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800222', '其他（手写）', '其他（手写）', '830', '0', '0', 'Z23280022', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232800231', '原因不明，故障报告反馈，并寻求支援', '原因不明，故障报告反馈，并寻求支援', '840', '0', '0', 'Z23280023', '0', sysdate, '0', sysdate,
   '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800232', '其他（手写）', '其他（手写）', '850', '0', '0', 'Z23280023', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800241', '安装责任者整改', '安装责任者整改', '860', '0', '0', 'Z23280024', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232800242', '原因不明，故障报告反馈，并寻求支援', '原因不明，故障报告反馈，并寻求支援', '870', '0', '0', 'Z23280024', '0', sysdate, '0', sysdate,
   '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800243', '其他（手写）', '其他（手写）', '880', '0', '0', 'Z23280024', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232800251', '由责任方故障处理或购买补齐部品', '由责任方故障处理或购买补齐部品', '890', '0', '0', 'Z23280025', '0', sysdate, '0', sysdate, '0',
   '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800252', '安装责任者整改', '安装责任者整改', '900', '0', '0', 'Z23280025', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800253', '其他（手写）', '其他（手写）', '910', '0', '0', 'Z23280025', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232800261', '原因不明，故障报告反馈，并寻求支援', '原因不明，故障报告反馈，并寻求支援', '920', '0', '0', 'Z23280026', '0', sysdate, '0', sysdate,
   '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800263', '其他（手写）', '其他（手写）', '940', '0', '0', 'Z23280026', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232800271', '由责任方故障处理或购买补齐部品', '由责任方故障处理或购买补齐部品', '950', '0', '0', 'Z23280027', '0', sysdate, '0', sysdate, '0',
   '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800272', '其他（手写）', '其他（手写）', '960', '0', '0', 'Z23280027', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800281', '安装责任者整改', '安装责任者整改', '970', '0', '0', 'Z23280028', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800283', '其他（手写）', '其他（手写）', '990', '0', '0', 'Z23280028', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800291', '安装责任者整改', '安装责任者整改', '1000', '0', '0', 'Z23280029', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800292', '其他（手写）', '其他（手写）', '1010', '0', '0', 'Z23280029', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800301', '安装责任者整改', '安装责任者整改', '1020', '0', '0', 'Z23280030', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800304', '其他（手写）', '其他（手写）', '1050', '0', '0', 'Z23280030', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800311', '安装责任者整改', '安装责任者整改', '1060', '0', '0', 'Z23280031', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800312', '其他（手写）', '其他（手写）', '1070', '0', '0', 'Z23280031', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800321', '安装责任者整改', '安装责任者整改', '1080', '0', '0', 'Z23280032', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800322', '其他（手写）', '其他（手写）', '1090', '0', '0', 'Z23280032', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232800331', '由责任方故障处理或购买补齐部品', '由责任方故障处理或购买补齐部品', '1100', '0', '0', 'Z23280033', '0', sysdate, '0', sysdate, '0',
   '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800332', '安装责任者整改', '安装责任者整改', '1110', '0', '0', 'Z23280033', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800334', '其他（手写）', '其他（手写）', '1130', '0', '0', 'Z23280033', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232800341', '由责任方故障处理或购买补齐部品', '由责任方故障处理或购买补齐部品', '1140', '0', '0', 'Z23280034', '0', sysdate, '0', sysdate, '0',
   '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800342', '安装责任者整改', '安装责任者整改', '1150', '0', '0', 'Z23280034', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800344', '其他（手写）', '其他（手写）', '1170', '0', '0', 'Z23280034', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800351', '安装责任者整改', '安装责任者整改', '1180', '0', '0', 'Z23280035', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232800354', '其他（手写）', '其他（手写）', '1210', '0', '0', 'Z23280035', '0', sysdate, '0', sysdate, '0', '0');
