

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21290003', '部品B3', '部品B3', '30', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21290006', '部品B6', '部品B6', '60', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21290009', '部品B9', '部品B9', '90', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21290012', '部品B12', '部品B12', '120', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21290015', '部品B15', '部品B15', '150', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21290018', '部品B18', '部品B18', '180', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21290020', '部品B20', '部品B20', '200', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21290024', '部品B24', '部品B24', '240', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21290027', '部品B27', '部品B27', '270', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21290029', '部品B29', '部品B29', '290', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21290032', '部品B32', '部品B32', '320', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21290036', '部品B36', '部品B36', '360', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21290040', '部品B40', '部品B40', '400', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21290042', '部品B42', '部品B42', '420', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21290046', '部品B46', '部品B46', '460', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21290049', '部品B49', '部品B49', '490', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21290053', '部品B53', '部品B53', '530', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21290057', '部品B57', '部品B57', '570', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21290060', '部品B60', '部品B60', '600', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21290066', '部品B66', '部品B66', '660', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21290068', '部品B68', '部品B68', '680', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21290071', '部品B71', '部品B71', '710', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21290074', '部品B74', '部品B74', '740', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21290078', '部品B78', '部品B78', '780', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21290081', '部品B81', '部品B81', '810', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21290084', '部品B84', '部品B84', '840', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21290086', '部品B86', '部品B86', '860', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z21290088', '部品B88', '部品B88', '880', '0', '0', 'Z21', '0', sysdate, '0', sysdate, '0', '0');




INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212900031', '主电源', '主电源', '30', '0', '0', 'Z21290003', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212900121', '保险丝', '保险丝', '120', '0', '0', 'Z21290012', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212900151', '控制柜', '控制柜', '150', '0', '0', 'Z21290015', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212900181', '控制柜', '控制柜', '180', '0', '0', 'Z21290018', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212900241', '滑动导靴', '滑动导靴', '240', '0', '0', 'Z21290024', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212900242', '滚动导靴', '滚动导靴', '250', '0', '0', 'Z21290024', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212900243', '平衡重块', '平衡重块', '260', '0', '0', 'Z21290024', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212900271', '导轨', '导轨', '270', '0', '0', 'Z21290027', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212900291', '安全钳', '安全钳', '290', '0', '0', 'Z21290029', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212900321', '抱闸微动开关', '抱闸微动开关', '320', '0', '0', 'Z21290032', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212900361', '门控器', '门控器', '360', '0', '0', 'Z21290036', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212900364', '门机马达', '门机马达', '390', '0', '0', 'Z21290036', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212900571', 'COP', 'COP', '570', '0', '0', 'Z21290057', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212900601', '风扇', '风扇', '600', '0', '0', 'Z21290060', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212900602', '灯', '灯', '610', '0', '0', 'Z21290060', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212900681', '外呼', '外呼', '680', '0', '0', 'Z21290068', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z212900741', '对讲机', '对讲机', '740', '0', '0', 'Z21290074', '0', sysdate, '0', sysdate, '0', '0');




INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22290003', '不良点Q3', '不良点Q3', '30', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22290006', '不良点Q6', '不良点Q6', '60', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22290009', '不良点Q9', '不良点Q9', '90', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22290012', '不良点Q12', '不良点Q12', '120', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22290015', '不良点Q15', '不良点Q15', '150', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22290018', '不良点Q18', '不良点Q18', '180', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22290020', '不良点Q20', '不良点Q20', '200', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22290024', '不良点Q24', '不良点Q24', '240', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22290027', '不良点Q27', '不良点Q27', '270', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22290029', '不良点Q29', '不良点Q29', '290', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22290032', '不良点Q32', '不良点Q32', '320', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22290036', '不良点Q36', '不良点Q36', '360', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22290040', '不良点Q40', '不良点Q40', '400', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22290042', '不良点Q42', '不良点Q42', '420', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22290046', '不良点Q46', '不良点Q46', '460', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22290049', '不良点Q49', '不良点Q49', '490', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22290053', '不良点Q53', '不良点Q53', '530', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22290057', '不良点Q57', '不良点Q57', '570', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22290060', '不良点Q60', '不良点Q60', '600', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22290066', '不良点Q66', '不良点Q66', '660', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22290068', '不良点Q68', '不良点Q68', '680', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22290071', '不良点Q71', '不良点Q71', '710', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22290074', '不良点Q74', '不良点Q74', '740', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22290078', '不良点Q78', '不良点Q78', '780', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22290081', '不良点Q81', '不良点Q81', '810', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22290084', '不良点Q84', '不良点Q84', '840', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22290086', '不良点Q86', '不良点Q86', '860', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z22290088', '不良点Q88', '不良点Q88', '880', '0', '0', 'Z22', '0', sysdate, '0', sysdate, '0', '0');




INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900031', '电压过高', '电压过高', '30', '0', '0', 'Z22290003', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900032', '电压过低', '电压过低', '40', '0', '0', 'Z22290003', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900033', '其他（手写）', '其他（手写）', '50', '0', '0', 'Z22290003', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900061', '门回路不通', '门回路不通', '60', '0', '0', 'Z22290006', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900062', '门回路短接', '门回路短接', '70', '0', '0', 'Z22290006', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900063', '其他（手写）', '其他（手写）', '80', '0', '0', 'Z22290006', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900091', '安全回路不通', '安全回路不通', '90', '0', '0', 'Z22290009', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900092', '安全回路短接', '安全回路短接', '100', '0', '0', 'Z22290009', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900093', '其他（手写）', '其他（手写）', '110', '0', '0', 'Z22290009', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900121', '保险丝规格不符', '保险丝规格不符', '120', '0', '0', 'Z22290012', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900122', '保险丝短接', '保险丝短接', '130', '0', '0', 'Z22290012', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900123', '其他（手写）', '其他（手写）', '140', '0', '0', 'Z22290012', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900151', '控制柜绝缘不良', '控制柜绝缘不良', '150', '0', '0', 'Z22290015', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900153', '其他（手写）', '其他（手写）', '170', '0', '0', 'Z22290015', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900181', '控制柜内线路不整洁', '控制柜内线路不整洁', '180', '0', '0', 'Z22290018', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900182', '其他（手写）', '其他（手写）', '190', '0', '0', 'Z22290018', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900201', '电梯高速运行时有异响', '电梯高速运行时有异响', '200', '0', '0', 'Z22290020', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900202', '部品不良或损坏', '部品不良或损坏', '210', '0', '0', 'Z22290020', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900204', '其他（手写）', '其他（手写）', '230', '0', '0', 'Z22290020', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900241', '滑动导靴（滚动导靴）调整不良', '滑动导靴（滚动导靴）调整不良', '240', '0', '0', 'Z22290024', '0', sysdate, '0', sysdate, '0',
        '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900242', '静态平衡设置不正确', '静态平衡设置不正确', '250', '0', '0', 'Z22290024', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900243', '其他（手写）', '其他（手写）', '260', '0', '0', 'Z22290024', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900271', '导轨污浊', '导轨污浊', '270', '0', '0', 'Z22290027', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900272', '其他（手写）', '其他（手写）', '280', '0', '0', 'Z22290027', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900291', '安全钳不能有效制停轿厢', '安全钳不能有效制停轿厢', '290', '0', '0', 'Z22290029', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900292', '安全钳调整不良', '安全钳调整不良', '300', '0', '0', 'Z22290029', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900293', '其他（手写）', '其他（手写）', '310', '0', '0', 'Z22290029', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900321', '开关动作不良', '开关动作不良', '320', '0', '0', 'Z22290032', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900322', '开关坏', '开关坏', '330', '0', '0', 'Z22290032', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900323', '开关短接', '开关短接', '340', '0', '0', 'Z22290032', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900324', '其他（手写）', '其他（手写）', '350', '0', '0', 'Z22290032', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900361', '门速调整不良', '门速调整不良', '360', '0', '0', 'Z22290036', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900362', '部品不良或损坏', '部品不良或损坏', '370', '0', '0', 'Z22290036', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900364', '其他（手写）', '其他（手写）', '390', '0', '0', 'Z22290036', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900401', '平衡系数不正确', '平衡系数不正确', '400', '0', '0', 'Z22290040', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900402', '其他（手写）', '其他（手写）', '410', '0', '0', 'Z22290040', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900421', '超满载设定不正确', '超满载设定不正确', '420', '0', '0', 'Z22290042', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900422', '部品不良或损坏', '部品不良或损坏', '430', '0', '0', 'Z22290042', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900424', '其他（手写）', '其他（手写）', '450', '0', '0', 'Z22290042', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900461', '舒适感调整不良', '舒适感调整不良', '460', '0', '0', 'Z22290046', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900463', '其他（手写）', '其他（手写）', '480', '0', '0', 'Z22290046', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900491', '电流，电压数据缺失', '电流，电压数据缺失', '490', '0', '0', 'Z22290049', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900492', '电流，电压数据不准确', '电流，电压数据不准确', '500', '0', '0', 'Z22290049', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900493', '调试报告没有', '调试报告没有', '510', '0', '0', 'Z22290049', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900494', '其他（手写）', '其他（手写）', '520', '0', '0', 'Z22290049', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900531', '甲方电源不良', '甲方电源不良', '530', '0', '0', 'Z22290053', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900532', '临时使用的电源线不规范', '临时使用的电源线不规范', '540', '0', '0', 'Z22290053', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900534', '其他（手写）', '其他（手写）', '560', '0', '0', 'Z22290053', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900571', '呼梯不正常', '呼梯不正常', '570', '0', '0', 'Z22290057', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900572', '显示不正常', '显示不正常', '580', '0', '0', 'Z22290057', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900573', '其他（手写）', '其他（手写）', '590', '0', '0', 'Z22290057', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900601', '风扇功能不良', '风扇功能不良', '600', '0', '0', 'Z22290060', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900602', '照明功能不良', '照明功能不良', '610', '0', '0', 'Z22290060', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900603', '应急灯功能不良', '应急灯功能不良', '620', '0', '0', 'Z22290060', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900604', '司机功能不良', '司机功能不良', '630', '0', '0', 'Z22290060', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900605', '专用功能不良', '专用功能不良', '640', '0', '0', 'Z22290060', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900606', '其他（手写）', '其他（手写）', '650', '0', '0', 'Z22290060', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900661', '孔洞未封堵', '孔洞未封堵', '660', '0', '0', 'Z22290066', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900662', '其他（手写）', '其他（手写）', '670', '0', '0', 'Z22290066', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900681', '乘场显示不良', '乘场显示不良', '680', '0', '0', 'Z22290068', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900682', '乘场呼梯不良', '乘场呼梯不良', '690', '0', '0', 'Z22290068', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900683', '其他（手写）', '其他（手写）', '700', '0', '0', 'Z22290068', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900711', '消防运行不良', '消防运行不良', '710', '0', '0', 'Z22290071', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900712', '火灾管制不良', '火灾管制不良', '720', '0', '0', 'Z22290071', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900713', '其他（手写）', '其他（手写）', '730', '0', '0', 'Z22290071', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900741', '五方通话不良', '五方通话不良', '740', '0', '0', 'Z22290074', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900742', '部品不良或损坏', '部品不良或损坏', '750', '0', '0', 'Z22290074', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900744', '其他（手写）', '其他（手写）', '770', '0', '0', 'Z22290074', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900781', '联动不正常', '联动不正常', '780', '0', '0', 'Z22290078', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900782', '群控不正常', '群控不正常', '790', '0', '0', 'Z22290078', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900783', '其他（手写）', '其他（手写）', '800', '0', '0', 'Z22290078', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900811', '呼梯不正常', '呼梯不正常', '810', '0', '0', 'Z22290081', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900812', '残障功能不正常', '残障功能不正常', '820', '0', '0', 'Z22290081', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900813', '其他（手写）', '其他（手写）', '830', '0', '0', 'Z22290081', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900842', '其他（手写）', '其他（手写）', '850', '0', '0', 'Z22290084', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900862', '其他（手写）', '其他（手写）', '870', '0', '0', 'Z22290086', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z222900882', '其他（手写）', '其他（手写）', '890', '0', '0', 'Z22290088', '0', sysdate, '0', sysdate, '0', '0');



INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23290003', '不良点Q3', '不良点Q3', '30', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23290006', '不良点Q6', '不良点Q6', '60', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23290009', '不良点Q9', '不良点Q9', '90', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23290012', '不良点Q12', '不良点Q12', '120', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23290015', '不良点Q15', '不良点Q15', '150', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23290018', '不良点Q18', '不良点Q18', '180', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23290020', '不良点Q20', '不良点Q20', '200', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23290024', '不良点Q24', '不良点Q24', '240', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23290027', '不良点Q27', '不良点Q27', '270', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23290029', '不良点Q29', '不良点Q29', '290', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23290032', '不良点Q32', '不良点Q32', '320', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23290036', '不良点Q36', '不良点Q36', '360', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23290040', '不良点Q40', '不良点Q40', '400', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23290042', '不良点Q42', '不良点Q42', '420', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23290046', '不良点Q46', '不良点Q46', '460', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23290049', '不良点Q49', '不良点Q49', '490', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23290053', '不良点Q53', '不良点Q53', '530', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23290057', '不良点Q57', '不良点Q57', '570', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23290060', '不良点Q60', '不良点Q60', '600', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23290066', '不良点Q66', '不良点Q66', '660', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23290068', '不良点Q68', '不良点Q68', '680', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23290071', '不良点Q71', '不良点Q71', '710', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23290074', '不良点Q74', '不良点Q74', '740', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23290078', '不良点Q78', '不良点Q78', '780', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23290081', '不良点Q81', '不良点Q81', '810', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23290084', '不良点Q84', '不良点Q84', '840', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23290086', '不良点Q86', '不良点Q86', '860', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z23290088', '不良点Q88', '不良点Q88', '880', '0', '0', 'Z23', '0', sysdate, '0', sysdate, '0', '0');




INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900031', '代理店协调甲方处理', '代理店协调甲方处理', '30', '0', '0', 'Z23290003', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900033', '其他（手写）', '其他（手写）', '50', '0', '0', 'Z23290003', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900061', '代理店检查处理', '代理店检查处理', '60', '0', '0', 'Z23290006', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900062', '拆除短接,教育相关人员', '拆除短接,教育相关人员', '70', '0', '0', 'Z23290006', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900063', '其他（手写）', '其他（手写）', '80', '0', '0', 'Z23290006', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900091', '代理店检查处理', '代理店检查处理', '90', '0', '0', 'Z23290009', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900092', '拆除短接,教育相关人员', '拆除短接,教育相关人员', '100', '0', '0', 'Z23290009', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900093', '其他（手写）', '其他（手写）', '110', '0', '0', 'Z23290009', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900121', '代理店更换相符保险丝', '代理店更换相符保险丝', '120', '0', '0', 'Z23290012', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232900122', '拆除短接,更换相符保险丝并教育相关人员', '拆除短接,更换相符保险丝并教育相关人员', '130', '0', '0', 'Z23290012', '0', sysdate, '0', sysdate,
   '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900123', '其他（手写）', '其他（手写）', '140', '0', '0', 'Z23290012', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900151', '代理店查找原因并整改', '代理店查找原因并整改', '150', '0', '0', 'Z23290015', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900152', '原因不明,寻求公司指导或支援', '原因不明,寻求公司指导或支援', '160', '0', '0', 'Z23290015', '0', sysdate, '0', sysdate, '0',
        '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900153', '其他（手写）', '其他（手写）', '170', '0', '0', 'Z23290015', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900181', '代理店整改', '代理店整改', '180', '0', '0', 'Z23290018', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900182', '其他（手写）', '其他（手写）', '190', '0', '0', 'Z23290018', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900201', '代理店查找原因并整改', '代理店查找原因并整改', '200', '0', '0', 'Z23290020', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232900202', '代理店或分公司上报品质系统处理', '代理店或分公司上报品质系统处理', '210', '0', '0', 'Z23290020', '0', sysdate, '0', sysdate, '0',
   '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900203', '原因不明,寻求公司指导或支援', '原因不明,寻求公司指导或支援', '220', '0', '0', 'Z23290020', '0', sysdate, '0', sysdate, '0',
        '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900204', '其他（手写）', '其他（手写）', '230', '0', '0', 'Z23290020', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900241', '代理店查找原因并整改', '代理店查找原因并整改', '240', '0', '0', 'Z23290024', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900243', '其他（手写）', '其他（手写）', '260', '0', '0', 'Z23290024', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900271', '代理店查找原因并整改', '代理店查找原因并整改', '270', '0', '0', 'Z23290027', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900272', '其他（手写）', '其他（手写）', '280', '0', '0', 'Z23290027', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900291', '代理店查找原因并整改,', '代理店查找原因并整改,', '290', '0', '0', 'Z23290029', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900292', '原因不明,电梯禁用,寻求公司指导或支援处理', '原因不明,电梯禁用,寻求公司指导或支援处理', '300', '0', '0', 'Z23290029', '0', sysdate, '0',
                      sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900293', '其他（手写）', '其他（手写）', '310', '0', '0', 'Z23290029', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900321', '代理店查找原因并整改,', '代理店查找原因并整改,', '320', '0', '0', 'Z23290032', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232900322', '代理店或分公司上报品质系统处理', '代理店或分公司上报品质系统处理', '330', '0', '0', 'Z23290032', '0', sysdate, '0', sysdate, '0',
   '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900323', '拆除短接,教育相关人员', '拆除短接,教育相关人员', '340', '0', '0', 'Z23290032', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900324', '其他（手写）', '其他（手写）', '350', '0', '0', 'Z23290032', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900361', '代理店查找原因并整改,', '代理店查找原因并整改,', '360', '0', '0', 'Z23290036', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232900362', '代理店或分公司上报品质系统处理', '代理店或分公司上报品质系统处理', '370', '0', '0', 'Z23290036', '0', sysdate, '0', sysdate, '0',
   '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900363', '原因不明,寻求公司指导或支援', '原因不明,寻求公司指导或支援', '380', '0', '0', 'Z23290036', '0', sysdate, '0', sysdate, '0',
        '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900364', '其他（手写）', '其他（手写）', '390', '0', '0', 'Z23290036', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900401', '代理店查找原因并整改,', '代理店查找原因并整改,', '400', '0', '0', 'Z23290040', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900402', '其他（手写）', '其他（手写）', '410', '0', '0', 'Z23290040', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900421', '代理店查找原因并整改,', '代理店查找原因并整改,', '420', '0', '0', 'Z23290042', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232900422', '代理店或分公司上报品质系统处理', '代理店或分公司上报品质系统处理', '430', '0', '0', 'Z23290042', '0', sysdate, '0', sysdate, '0',
   '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900423', '原因不明,寻求公司指导或支援', '原因不明,寻求公司指导或支援', '440', '0', '0', 'Z23290042', '0', sysdate, '0', sysdate, '0',
        '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900424', '其他（手写）', '其他（手写）', '450', '0', '0', 'Z23290042', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900461', '代理店查找原因并整改,', '代理店查找原因并整改,', '460', '0', '0', 'Z23290046', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900462', '原因不明,寻求公司指导或支援', '原因不明,寻求公司指导或支援', '470', '0', '0', 'Z23290046', '0', sysdate, '0', sysdate, '0',
        '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900463', '其他（手写）', '其他（手写）', '480', '0', '0', 'Z23290046', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900491', '代理店查找原因并整改,', '代理店查找原因并整改,', '490', '0', '0', 'Z23290049', '0', sysdate, '0', sysdate, '0', '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900494', '其他（手写）', '其他（手写）', '520', '0', '0', 'Z23290049', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900531', '代理店协调甲方处理', '代理店协调甲方处理', '530', '0', '0', 'Z23290053', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900532', '代理店查找原因并整改,', '代理店查找原因并整改,', '540', '0', '0', 'Z23290053', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900533', '原因不明,寻求公司指导或支援', '原因不明,寻求公司指导或支援', '550', '0', '0', 'Z23290053', '0', sysdate, '0', sysdate, '0',
        '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900534', '其他（手写）', '其他（手写）', '560', '0', '0', 'Z23290053', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900571', '代理店查找原因并整改,', '代理店查找原因并整改,', '570', '0', '0', 'Z23290057', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900572', '原因不明,寻求公司指导或支援', '原因不明,寻求公司指导或支援', '580', '0', '0', 'Z23290057', '0', sysdate, '0', sysdate, '0',
        '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900573', '其他（手写）', '其他（手写）', '590', '0', '0', 'Z23290057', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900601', '代理店查找原因并整改,', '代理店查找原因并整改,', '600', '0', '0', 'Z23290060', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900602', '原因不明,寻求公司指导或支援', '原因不明,寻求公司指导或支援', '610', '0', '0', 'Z23290060', '0', sysdate, '0', sysdate, '0',
        '0');


INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900606', '其他（手写）', '其他（手写）', '650', '0', '0', 'Z23290060', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900661', '电梯禁用,代理店协调甲方处理', '电梯禁用,代理店协调甲方处理', '660', '0', '0', 'Z23290066', '0', sysdate, '0', sysdate, '0',
        '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900662', '其他（手写）', '其他（手写）', '670', '0', '0', 'Z23290066', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900681', '代理店查找原因并整改,', '代理店查找原因并整改,', '680', '0', '0', 'Z23290068', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900682', '原因不明,寻求公司指导或支援', '原因不明,寻求公司指导或支援', '690', '0', '0', 'Z23290068', '0', sysdate, '0', sysdate, '0',
        '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900683', '其他（手写）', '其他（手写）', '700', '0', '0', 'Z23290068', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900711', '代理店查找原因并整改,', '代理店查找原因并整改,', '710', '0', '0', 'Z23290071', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900712', '原因不明,寻求公司指导或支援', '原因不明,寻求公司指导或支援', '720', '0', '0', 'Z23290071', '0', sysdate, '0', sysdate, '0',
        '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900713', '其他（手写）', '其他（手写）', '730', '0', '0', 'Z23290071', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900741', '代理店查找原因并整改,', '代理店查找原因并整改,', '740', '0', '0', 'Z23290074', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232900742', '代理店或分公司上报品质系统处理', '代理店或分公司上报品质系统处理', '750', '0', '0', 'Z23290074', '0', sysdate, '0', sysdate, '0',
   '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900743', '原因不明,寻求公司指导或支援', '原因不明,寻求公司指导或支援', '760', '0', '0', 'Z23290074', '0', sysdate, '0', sysdate, '0',
        '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900744', '其他（手写）', '其他（手写）', '770', '0', '0', 'Z23290074', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900781', '代理店查找原因并整改,', '代理店查找原因并整改,', '780', '0', '0', 'Z23290078', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900782', '原因不明,寻求公司指导或支援', '原因不明,寻求公司指导或支援', '790', '0', '0', 'Z23290078', '0', sysdate, '0', sysdate, '0',
        '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900783', '其他（手写）', '其他（手写）', '800', '0', '0', 'Z23290078', '0', sysdate, '0', sysdate, '0', '0');
INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES
  ('Z232900811', '原因不明，故障报告反馈，并寻求支援', '原因不明，故障报告反馈，并寻求支援', '810', '0', '0', 'Z23290081', '0', sysdate, '0', sysdate,
   '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900813', '其他（手写）', '其他（手写）', '830', '0', '0', 'Z23290081', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900842', '其他（手写）', '其他（手写）', '850', '0', '0', 'Z23290084', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900862', '其他（手写）', '其他（手写）', '870', '0', '0', 'Z23290086', '0', sysdate, '0', sysdate, '0', '0');

INSERT INTO SYSTEM_CODE (CODE, CODE_DESC_EN, CODE_DESC_ZH, PRIORITY, DISABLED, NEED_CONTROL, PARENT_CODE, VERSION, CREATED_DTM, CREATED_BY, LAST_MODIFIED_DTM, LAST_MODIFIED_BY, DELETED)
VALUES ('Z232900882', '其他（手写）', '其他（手写）', '890', '0', '0', 'Z23290088', '0', sysdate, '0', sysdate, '0', '0');



Insert into SYSTEM_CODE (CODE,CODE_DESC_EN,CODE_DESC_ZH,PRIORITY,DISABLED,NEED_CONTROL,PARENT_CODE,VERSION,CREATED_DTM,CREATED_BY,LAST_MODIFIED_DTM,LAST_MODIFIED_BY,DELETED) values ('Z212900032','其他（手写）','其他（手写）',40,0,0,'Z21290003',0,sysdate,0,sysdate,0,0);
Insert into SYSTEM_CODE (CODE,CODE_DESC_EN,CODE_DESC_ZH,PRIORITY,DISABLED,NEED_CONTROL,PARENT_CODE,VERSION,CREATED_DTM,CREATED_BY,LAST_MODIFIED_DTM,LAST_MODIFIED_BY,DELETED) values ('Z212900061','其他（手写）','其他（手写）',10,0,0,'Z21290006',0,sysdate,0,sysdate,0,0);
Insert into SYSTEM_CODE (CODE,CODE_DESC_EN,CODE_DESC_ZH,PRIORITY,DISABLED,NEED_CONTROL,PARENT_CODE,VERSION,CREATED_DTM,CREATED_BY,LAST_MODIFIED_DTM,LAST_MODIFIED_BY,DELETED) values ('Z212900091','其他（手写）','其他（手写）',10,0,0,'Z21290009',0,sysdate,0,sysdate,0,0);
Insert into SYSTEM_CODE (CODE,CODE_DESC_EN,CODE_DESC_ZH,PRIORITY,DISABLED,NEED_CONTROL,PARENT_CODE,VERSION,CREATED_DTM,CREATED_BY,LAST_MODIFIED_DTM,LAST_MODIFIED_BY,DELETED) values ('Z212900122','其他（手写）','其他（手写）',130,0,0,'Z21290012',0,sysdate,0,sysdate,0,0);
Insert into SYSTEM_CODE (CODE,CODE_DESC_EN,CODE_DESC_ZH,PRIORITY,DISABLED,NEED_CONTROL,PARENT_CODE,VERSION,CREATED_DTM,CREATED_BY,LAST_MODIFIED_DTM,LAST_MODIFIED_BY,DELETED) values ('Z212900152','其他（手写）','其他（手写）',160,0,0,'Z21290015',0,sysdate,0,sysdate,0,0);
Insert into SYSTEM_CODE (CODE,CODE_DESC_EN,CODE_DESC_ZH,PRIORITY,DISABLED,NEED_CONTROL,PARENT_CODE,VERSION,CREATED_DTM,CREATED_BY,LAST_MODIFIED_DTM,LAST_MODIFIED_BY,DELETED) values ('Z212900182','其他（手写）','其他（手写）',190,0,0,'Z21290018',0,sysdate,0,sysdate,0,0);
Insert into SYSTEM_CODE (CODE,CODE_DESC_EN,CODE_DESC_ZH,PRIORITY,DISABLED,NEED_CONTROL,PARENT_CODE,VERSION,CREATED_DTM,CREATED_BY,LAST_MODIFIED_DTM,LAST_MODIFIED_BY,DELETED) values ('Z212900201','其他（手写）','其他（手写）',10,0,0,'Z21290020',0,sysdate,0,sysdate,0,0);
Insert into SYSTEM_CODE (CODE,CODE_DESC_EN,CODE_DESC_ZH,PRIORITY,DISABLED,NEED_CONTROL,PARENT_CODE,VERSION,CREATED_DTM,CREATED_BY,LAST_MODIFIED_DTM,LAST_MODIFIED_BY,DELETED) values ('Z212900244','其他（手写）','其他（手写）',270,0,0,'Z21290024',0,sysdate,0,sysdate,0,0);
Insert into SYSTEM_CODE (CODE,CODE_DESC_EN,CODE_DESC_ZH,PRIORITY,DISABLED,NEED_CONTROL,PARENT_CODE,VERSION,CREATED_DTM,CREATED_BY,LAST_MODIFIED_DTM,LAST_MODIFIED_BY,DELETED) values ('Z212900272','其他（手写）','其他（手写）',280,0,0,'Z21290027',0,sysdate,0,sysdate,0,0);
Insert into SYSTEM_CODE (CODE,CODE_DESC_EN,CODE_DESC_ZH,PRIORITY,DISABLED,NEED_CONTROL,PARENT_CODE,VERSION,CREATED_DTM,CREATED_BY,LAST_MODIFIED_DTM,LAST_MODIFIED_BY,DELETED) values ('Z212900292','其他（手写）','其他（手写）',300,0,0,'Z21290029',0,sysdate,0,sysdate,0,0);
Insert into SYSTEM_CODE (CODE,CODE_DESC_EN,CODE_DESC_ZH,PRIORITY,DISABLED,NEED_CONTROL,PARENT_CODE,VERSION,CREATED_DTM,CREATED_BY,LAST_MODIFIED_DTM,LAST_MODIFIED_BY,DELETED) values ('Z212900322','其他（手写）','其他（手写）',330,0,0,'Z21290032',0,sysdate,0,sysdate,0,0);
Insert into SYSTEM_CODE (CODE,CODE_DESC_EN,CODE_DESC_ZH,PRIORITY,DISABLED,NEED_CONTROL,PARENT_CODE,VERSION,CREATED_DTM,CREATED_BY,LAST_MODIFIED_DTM,LAST_MODIFIED_BY,DELETED) values ('Z212900365','其他（手写）','其他（手写）',400,0,0,'Z21290036',0,sysdate,0,sysdate,0,0);
Insert into SYSTEM_CODE (CODE,CODE_DESC_EN,CODE_DESC_ZH,PRIORITY,DISABLED,NEED_CONTROL,PARENT_CODE,VERSION,CREATED_DTM,CREATED_BY,LAST_MODIFIED_DTM,LAST_MODIFIED_BY,DELETED) values ('Z212900401','其他（手写）','其他（手写）',10,0,0,'Z21290040',0,sysdate,0,sysdate,0,0);
Insert into SYSTEM_CODE (CODE,CODE_DESC_EN,CODE_DESC_ZH,PRIORITY,DISABLED,NEED_CONTROL,PARENT_CODE,VERSION,CREATED_DTM,CREATED_BY,LAST_MODIFIED_DTM,LAST_MODIFIED_BY,DELETED) values ('Z212900421','其他（手写）','其他（手写）',10,0,0,'Z21290042',0,sysdate,0,sysdate,0,0);
Insert into SYSTEM_CODE (CODE,CODE_DESC_EN,CODE_DESC_ZH,PRIORITY,DISABLED,NEED_CONTROL,PARENT_CODE,VERSION,CREATED_DTM,CREATED_BY,LAST_MODIFIED_DTM,LAST_MODIFIED_BY,DELETED) values ('Z212900461','其他（手写）','其他（手写）',10,0,0,'Z21290046',0,sysdate,0,sysdate,0,0);
Insert into SYSTEM_CODE (CODE,CODE_DESC_EN,CODE_DESC_ZH,PRIORITY,DISABLED,NEED_CONTROL,PARENT_CODE,VERSION,CREATED_DTM,CREATED_BY,LAST_MODIFIED_DTM,LAST_MODIFIED_BY,DELETED) values ('Z212900491','其他（手写）','其他（手写）',10,0,0,'Z21290049',0,sysdate,0,sysdate,0,0);
Insert into SYSTEM_CODE (CODE,CODE_DESC_EN,CODE_DESC_ZH,PRIORITY,DISABLED,NEED_CONTROL,PARENT_CODE,VERSION,CREATED_DTM,CREATED_BY,LAST_MODIFIED_DTM,LAST_MODIFIED_BY,DELETED) values ('Z212900531','其他（手写）','其他（手写）',10,0,0,'Z21290053',0,sysdate,0,sysdate,0,0);
Insert into SYSTEM_CODE (CODE,CODE_DESC_EN,CODE_DESC_ZH,PRIORITY,DISABLED,NEED_CONTROL,PARENT_CODE,VERSION,CREATED_DTM,CREATED_BY,LAST_MODIFIED_DTM,LAST_MODIFIED_BY,DELETED) values ('Z212900572','其他（手写）','其他（手写）',580,0,0,'Z21290057',0,sysdate,0,sysdate,0,0);
Insert into SYSTEM_CODE (CODE,CODE_DESC_EN,CODE_DESC_ZH,PRIORITY,DISABLED,NEED_CONTROL,PARENT_CODE,VERSION,CREATED_DTM,CREATED_BY,LAST_MODIFIED_DTM,LAST_MODIFIED_BY,DELETED) values ('Z212900603','其他（手写）','其他（手写）',620,0,0,'Z21290060',0,sysdate,0,sysdate,0,0);
Insert into SYSTEM_CODE (CODE,CODE_DESC_EN,CODE_DESC_ZH,PRIORITY,DISABLED,NEED_CONTROL,PARENT_CODE,VERSION,CREATED_DTM,CREATED_BY,LAST_MODIFIED_DTM,LAST_MODIFIED_BY,DELETED) values ('Z212900661','其他（手写）','其他（手写）',10,0,0,'Z21290066',0,sysdate,0,sysdate,0,0);
Insert into SYSTEM_CODE (CODE,CODE_DESC_EN,CODE_DESC_ZH,PRIORITY,DISABLED,NEED_CONTROL,PARENT_CODE,VERSION,CREATED_DTM,CREATED_BY,LAST_MODIFIED_DTM,LAST_MODIFIED_BY,DELETED) values ('Z212900682','其他（手写）','其他（手写）',690,0,0,'Z21290068',0,sysdate,0,sysdate,0,0);
Insert into SYSTEM_CODE (CODE,CODE_DESC_EN,CODE_DESC_ZH,PRIORITY,DISABLED,NEED_CONTROL,PARENT_CODE,VERSION,CREATED_DTM,CREATED_BY,LAST_MODIFIED_DTM,LAST_MODIFIED_BY,DELETED) values ('Z212900711','其他（手写）','其他（手写）',10,0,0,'Z21290071',0,sysdate,0,sysdate,0,0);
Insert into SYSTEM_CODE (CODE,CODE_DESC_EN,CODE_DESC_ZH,PRIORITY,DISABLED,NEED_CONTROL,PARENT_CODE,VERSION,CREATED_DTM,CREATED_BY,LAST_MODIFIED_DTM,LAST_MODIFIED_BY,DELETED) values ('Z212900742','其他（手写）','其他（手写）',750,0,0,'Z21290074',0,sysdate,0,sysdate,0,0);
Insert into SYSTEM_CODE (CODE,CODE_DESC_EN,CODE_DESC_ZH,PRIORITY,DISABLED,NEED_CONTROL,PARENT_CODE,VERSION,CREATED_DTM,CREATED_BY,LAST_MODIFIED_DTM,LAST_MODIFIED_BY,DELETED) values ('Z212900781','其他（手写）','其他（手写）',10,0,0,'Z21290078',0,sysdate,0,sysdate,0,0);
Insert into SYSTEM_CODE (CODE,CODE_DESC_EN,CODE_DESC_ZH,PRIORITY,DISABLED,NEED_CONTROL,PARENT_CODE,VERSION,CREATED_DTM,CREATED_BY,LAST_MODIFIED_DTM,LAST_MODIFIED_BY,DELETED) values ('Z212900811','其他（手写）','其他（手写）',10,0,0,'Z21290081',0,sysdate,0,sysdate,0,0);
Insert into SYSTEM_CODE (CODE,CODE_DESC_EN,CODE_DESC_ZH,PRIORITY,DISABLED,NEED_CONTROL,PARENT_CODE,VERSION,CREATED_DTM,CREATED_BY,LAST_MODIFIED_DTM,LAST_MODIFIED_BY,DELETED) values ('Z212900841','其他（手写）','其他（手写）',10,0,0,'Z21290084',0,sysdate,0,sysdate,0,0);
Insert into SYSTEM_CODE (CODE,CODE_DESC_EN,CODE_DESC_ZH,PRIORITY,DISABLED,NEED_CONTROL,PARENT_CODE,VERSION,CREATED_DTM,CREATED_BY,LAST_MODIFIED_DTM,LAST_MODIFIED_BY,DELETED) values ('Z212900861','其他（手写）','其他（手写）',10,0,0,'Z21290086',0,sysdate,0,sysdate,0,0);
Insert into SYSTEM_CODE (CODE,CODE_DESC_EN,CODE_DESC_ZH,PRIORITY,DISABLED,NEED_CONTROL,PARENT_CODE,VERSION,CREATED_DTM,CREATED_BY,LAST_MODIFIED_DTM,LAST_MODIFIED_BY,DELETED) values ('Z212900881','其他（手写）','其他（手写）',10,0,0,'Z21290088',0,sysdate,0,sysdate,0,0);
