spring:
  profiles: default

server:
  port: 8090

management:
  security:
    enabled: false

security:
  basic:
    enabled: false


endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

authentication:
  oauth:
    clientid: authserverapp
    secret: mySecretOAuthSecret
    # Token is valid 24 hours 
    tokenValidityInSeconds: 86400

logic:
  jndi:
    master:
      name: jdbc/facts_master
      factory: org.apache.commons.dbcp2.BasicDataSourceFactory
      maxActive: 5
      maxIdle: 2
      initialSize: 1
      maxWait: 5000
      test-on-borrow: true
      validation-query: select 1
    slave:
      name: jdbc/facts_slave
      factory: org.apache.commons.dbcp2.BasicDataSourceFactory
      maxActive: 5
      maxIdle: 2
      initialSize: 1
      maxWait: 5000
      test-on-borrow: true
      validation-query: select 1
  swagger:
    version: 0.0.1
    host:
    basePath: /system/rest
    description: Logic Solutions System Server.
    title: System Server
    licence:
    licenceUrl:
    contact:
    termsOfServiceUrl:
    resourcePackage: com.logic.system.ws
  file:
    path:
      local: #configure in every config file specificly
      remote: #configure in every config file specificly
