package com.logic.common.enums;

public enum TableNameEnum {
	//1、System
	SYSTEM_ADDRESS,
	SYSTEM_ORGANIZATION,
	SYSTEM_USER,//用户表
	SYSTEM_ORG_USER,
	SYSTEM_PERSONAL_INFO,
	SYSTEM_CODE,
	SYSTEM_ROLE,
	SYSTEM_USER_ROLE,
	SYSTEM_MOBILE_DEVICE,//安卓设备信息表
	SYSTEM_MOBILE_DEVICE_POSITION,//轨迹表
	SYSTEM_TASK,//任务表
	SYSTEM_TASK_PEOPLE,
	SYSTEM_TASK_DATE,
	SYSTEM_TASK_COMMENT,
	SYSTEM_TASK_LOG,
	SYSTEM_TASK_REFERENCE,//任务表
	//form
	SYSTEM_FORM,
	SYSTEM_FORM_ELEMENT,
	SYSTEM_FORM_ELE_OPT_ANSWER,
	SYSTEM_FORM_STEP,
	SYSTEM_FORM_SECTION,
	SYSTEM_FORM_RESPONSE_MASTER,
	SYSTEM_FORM_RESPONSE_DETAIL,
	SYSTEM_FILE,//知识库
	SYSTEM_MOBILE_NOTIFICATION_LOG,//消息表
	SYSTEM_ONLINE_HELP,//常见问题
	//同步日志表
	SYSTEM_MOBILE_DATA_SYNC, 
	SYSTEM_MOBILE_DATA_SYNCLOG,
	
	SYSTEM_TASK_FORM,
	
	//2、Toshiba_1
	PD_REQUEST_MIDDLE_CHECK,
	PD_REQUEST_DIAG,
	PD_REQUEST_OVERALL_CHECK,	
	PD_MACHINE_INFO,
	PD_PROJECT_INFO,
	PD_DIAGNOSE_DATA,
	
	//3、Toshiba_2
	EH_CORRECTIVE_ACTION_MASTER,
	EHS_CORRECTIVE_ACTION_DETAIL,

	DIAGNOS_DATA;

}
