package com.logic.system.persistence.read;

import com.logic.system.domain.DiagnoseData;

import java.util.List;

public interface DiagnoseDataReadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PD_DIAGNOSE_DATA
     *
     * @mbggenerated Thu Feb 04 17:16:45 CST 2016
     */
    DiagnoseData selectByPrimaryKey(Integer id);

    List<DiagnoseData> selectDiagnoseDatasByDiagRequestId(Integer id);
}