package com.logic.system.persistence.read;

import com.logic.system.domain.MobileDevicePosition;

public interface MobileDevicePositionReadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_MOBILE_DEVICE_POSITION
     *
     * @mbggenerated Fri Jan 22 18:38:44 CST 2016
     */
    MobileDevicePosition selectByPrimaryKey(Integer id);
}