package com.logic.system.persistence.read;

import com.logic.system.domain.MobileDevice;


public interface MobileDeviceReadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_MOBILE_DEVICE
     *
     * @mbggenerated Fri Jan 22 18:38:44 CST 2016
     */
    MobileDevice selectByPrimaryKey(Integer id);

    MobileDevice selectMobileDeviceByUserId(Integer id);
}