package com.logic.system.persistence.read;


import com.logic.system.domain.PDCorrectiveActionMaster;

import java.util.List;


public interface PDCorrectiveActionMasterReadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PD_CORRECTIVE_ACTION_MASTER
     *
     * @mbggenerated Fri Jan 15 16:40:56 CST 2016
     */
    PDCorrectiveActionMaster selectByPrimaryKey(Integer id);
    List<PDCorrectiveActionMaster> getPDCorrectiveActionMasterListByTaskId(Integer taskId);
    PDCorrectiveActionMaster selectByFormId(Integer id);
}