package com.logic.system.persistence.read;

import com.logic.common.ws.dto.system.TaskPeopleDTO;
import com.logic.system.domain.TaskPeople;
import java.math.BigDecimal;
import java.util.List;

public interface TaskPeopleReadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_TASK_PEOPLE
     *
     * @mbggenerated Fri Dec 18 13:43:11 CST 2015
     */
    TaskPeople selectByPrimaryKey(Integer id);

    List<TaskPeople> selectByTaskId(Integer id);

    List<TaskPeopleDTO> selectDTOByTaskId(Integer id);

    int checkPersonExistForTask(String task_id, String user_id, String responsibility);

    int selectResponsibilityCountForTask(String task_id, String responsibility);

    TaskPeople selectAssignByTaskId(Integer id);
}