package com.logic.system.persistence.read;

import com.logic.common.ws.dto.system.TaskLogRootDTO;
import com.logic.system.domain.TaskLog;
import java.math.BigDecimal;
import java.util.List;

public interface TaskLogReadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_TASK_LOG
     *
     * @mbggenerated Fri Dec 18 13:43:11 CST 2015
     */
    TaskLog selectByPrimaryKey(Integer id);

    List<TaskLog> selectByTaskId(Integer taskId);

    List<TaskLogRootDTO> selectRootByTaskId(Integer taskId);
}