package com.logic.system.persistence.read;

import com.logic.system.domain.TaskDate;
import java.util.List;

public interface TaskDateReadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_TASK_DATE
     *
     * @mbggenerated Fri Dec 18 13:43:11 CST 2015
     */
    TaskDate selectByPrimaryKey(Integer id);

    List<TaskDate> selectByTaskId(Integer id);

    int checkDateExistForTask(String task_id, String date_type);
}