package com.logic.system.persistence.write;

import com.logic.system.domain.OAuthAccessToken;

public interface OAuthAccessTokenWriteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OAUTH_ACCESS_TOKEN
     *
     * @mbggenerated Tue Dec 15 17:27:53 CST 2015
     */
    int deleteByPrimaryKey(String authenticationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OAUTH_ACCESS_TOKEN
     *
     * @mbggenerated Tue Dec 15 17:27:53 CST 2015
     */
    int insert(OAuthAccessToken record);

    int update(OAuthAccessToken record);
}