package com.logic.system.persistence.write;

import com.logic.system.domain.OAuthRefreshToken;

public interface OAuthRefreshTokenWriteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OAUTH_REFRESH_TOKEN
     *
     * @mbggenerated Tue Dec 15 17:27:53 CST 2015
     */
    int insert(OAuthRefreshToken record);

    int deleteByTokenId(String tokenId);
}