package com.logic.system.persistence.write;


import com.logic.system.domain.PDCorrectiveActionDetail;

import java.util.List;

public interface PDCorrectiveActionDetailWriteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PD_CORRECTIVE_ACTION_DETAIL
     *
     * @mbggenerated Fri Jan 15 16:41:02 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PD_CORRECTIVE_ACTION_DETAIL
     *
     * @mbggenerated Fri Jan 15 16:41:02 CST 2016
     */
    int insert(PDCorrectiveActionDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PD_CORRECTIVE_ACTION_DETAIL
     *
     * @mbggenerated Fri Jan 15 16:41:02 CST 2016
     */
    int insertSelective(PDCorrectiveActionDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PD_CORRECTIVE_ACTION_DETAIL
     *
     * @mbggenerated Fri Jan 15 16:41:02 CST 2016
     */
    int updateByPrimaryKeySelective(PDCorrectiveActionDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PD_CORRECTIVE_ACTION_DETAIL
     *
     * @mbggenerated Fri Jan 15 16:41:02 CST 2016
     */
    int updateByPrimaryKey(PDCorrectiveActionDetail record);

    void insertBatch(List<PDCorrectiveActionDetail> pdCorrectiveActionDetailList);
}