package com.logic.system.persistence.write;


import com.logic.system.domain.PDCorrectiveActionMaster;

public interface PDCorrectiveActionMasterWriteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PD_CORRECTIVE_ACTION_MASTER
     *
     * @mbggenerated Fri Jan 15 16:41:02 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PD_CORRECTIVE_ACTION_MASTER
     *
     * @mbggenerated Fri Jan 15 16:41:02 CST 2016
     */
    int insert(PDCorrectiveActionMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PD_CORRECTIVE_ACTION_MASTER
     *
     * @mbggenerated Fri Jan 15 16:41:02 CST 2016
     */
    int insertSelective(PDCorrectiveActionMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PD_CORRECTIVE_ACTION_MASTER
     *
     * @mbggenerated Fri Jan 15 16:41:02 CST 2016
     */
    int updateByPrimaryKeySelective(PDCorrectiveActionMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PD_CORRECTIVE_ACTION_MASTER
     *
     * @mbggenerated Fri Jan 15 16:41:02 CST 2016
     */
    int updateByPrimaryKey(PDCorrectiveActionMaster record);
}