package com.logic.system.persistence.write;


import com.logic.system.domain.PDRequestOverallCheck;

import java.math.BigDecimal;

public interface PDRequestOverallCheckWriteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PD_REQUEST_OVERALL_CHECK
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PD_REQUEST_OVERALL_CHECK
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    int insert(PDRequestOverallCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PD_REQUEST_OVERALL_CHECK
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    int insertSelective(PDRequestOverallCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PD_REQUEST_OVERALL_CHECK
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    int updateByPrimaryKeySelective(PDRequestOverallCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PD_REQUEST_OVERALL_CHECK
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    int updateByPrimaryKey(PDRequestOverallCheck record);
}