package com.logic.system.persistence.write;

import com.logic.system.domain.TaskPeople;
import java.math.BigDecimal;

public interface TaskPeopleWriteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_TASK_PEOPLE
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    int deleteByPrimaryKey(Integer integer);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_TASK_PEOPLE
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    int insert(TaskPeople record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_TASK_PEOPLE
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    int insertSelective(TaskPeople record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_TASK_PEOPLE
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    int updateByPrimaryKeySelective(TaskPeople record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_TASK_PEOPLE
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    int updateByPrimaryKey(TaskPeople record);
}