package com.logic.system.persistence.write;

import com.logic.system.domain.Task;

public interface TaskWriteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_TASK
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_TASK
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    int insert(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_TASK
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    int insertSelective(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_TASK
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    int updateByPrimaryKeySelective(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_TASK
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    int updateByPrimaryKey(Task record);

    int updateWritebackStatus(String taskId, String taskType, String writebackStatus);
}