package com.logic.system.persistence.write;

import com.logic.system.domain.TaskComment;
import java.math.BigDecimal;

public interface TaskCommentWriteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_TASK_COMMENT
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    int deleteByPrimaryKey(Integer integer);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_TASK_COMMENT
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    int insert(TaskComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_TASK_COMMENT
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    int insertSelective(TaskComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_TASK_COMMENT
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    int updateByPrimaryKeySelective(TaskComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_TASK_COMMENT
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    int updateByPrimaryKey(TaskComment record);
}