package com.logic.system.persistence.write;

import com.logic.system.domain.TaskDate;
import java.math.BigDecimal;

public interface TaskDateWriteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_TASK_DATE
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_TASK_DATE
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    int insert(TaskDate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_TASK_DATE
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    int insertSelective(TaskDate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_TASK_DATE
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    int updateByPrimaryKeySelective(TaskDate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_TASK_DATE
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    int updateByPrimaryKey(TaskDate record);
}