package com.logic.system.persistence.write;

import com.logic.system.domain.TaskLog;
import java.math.BigDecimal;

public interface TaskLogWriteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_TASK_LOG
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    int deleteByPrimaryKey(Integer integer);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_TASK_LOG
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    int insert(TaskLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_TASK_LOG
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    int insertSelective(TaskLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_TASK_LOG
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    int updateByPrimaryKeySelective(TaskLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_TASK_LOG
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    int updateByPrimaryKey(TaskLog record);
}