package com.logic.system.domain;

import com.logic.common.domain.BasePojo;

import java.util.Date;

public class DiagnoseData extends BasePojo{

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_DIAGNOSE_DATA.DIAG_REQUET_ID
     *
     * @mbggenerated Thu Feb 04 17:16:45 CST 2016
     */
    private Integer diagRequetId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_DIAGNOSE_DATA.KEY
     *
     * @mbggenerated Thu Feb 04 17:16:45 CST 2016
     */
    private String key;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_DIAGNOSE_DATA.BEFORE_VALUE
     *
     * @mbggenerated Thu Feb 04 17:16:45 CST 2016
     */
    private String beforeValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_DIAGNOSE_DATA.VALUE
     *
     * @mbggenerated Thu Feb 04 17:16:45 CST 2016
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_DIAGNOSE_DATA.AFTER_VALUE
     *
     * @mbggenerated Thu Feb 04 17:16:45 CST 2016
     */
    private String afterValue;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_DIAGNOSE_DATA.DIAG_REQUET_ID
     *
     * @return the value of PD_DIAGNOSE_DATA.DIAG_REQUET_ID
     *
     * @mbggenerated Thu Feb 04 17:16:45 CST 2016
     */
    public Integer getDiagRequetId() {
        return diagRequetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_DIAGNOSE_DATA.DIAG_REQUET_ID
     *
     * @param diagRequetId the value for PD_DIAGNOSE_DATA.DIAG_REQUET_ID
     *
     * @mbggenerated Thu Feb 04 17:16:45 CST 2016
     */
    public void setDiagRequetId(Integer diagRequetId) {
        this.diagRequetId = diagRequetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_DIAGNOSE_DATA.KEY
     *
     * @return the value of PD_DIAGNOSE_DATA.KEY
     *
     * @mbggenerated Thu Feb 04 17:16:45 CST 2016
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_DIAGNOSE_DATA.KEY
     *
     * @param key the value for PD_DIAGNOSE_DATA.KEY
     *
     * @mbggenerated Thu Feb 04 17:16:45 CST 2016
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_DIAGNOSE_DATA.BEFORE_VALUE
     *
     * @return the value of PD_DIAGNOSE_DATA.BEFORE_VALUE
     *
     * @mbggenerated Thu Feb 04 17:16:45 CST 2016
     */
    public String getBeforeValue() {
        return beforeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_DIAGNOSE_DATA.BEFORE_VALUE
     *
     * @param beforeValue the value for PD_DIAGNOSE_DATA.BEFORE_VALUE
     *
     * @mbggenerated Thu Feb 04 17:16:45 CST 2016
     */
    public void setBeforeValue(String beforeValue) {
        this.beforeValue = beforeValue == null ? null : beforeValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_DIAGNOSE_DATA.VALUE
     *
     * @return the value of PD_DIAGNOSE_DATA.VALUE
     *
     * @mbggenerated Thu Feb 04 17:16:45 CST 2016
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_DIAGNOSE_DATA.VALUE
     *
     * @param value the value for PD_DIAGNOSE_DATA.VALUE
     *
     * @mbggenerated Thu Feb 04 17:16:45 CST 2016
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_DIAGNOSE_DATA.AFTER_VALUE
     *
     * @return the value of PD_DIAGNOSE_DATA.AFTER_VALUE
     *
     * @mbggenerated Thu Feb 04 17:16:45 CST 2016
     */
    public String getAfterValue() {
        return afterValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_DIAGNOSE_DATA.AFTER_VALUE
     *
     * @param afterValue the value for PD_DIAGNOSE_DATA.AFTER_VALUE
     *
     * @mbggenerated Thu Feb 04 17:16:45 CST 2016
     */
    public void setAfterValue(String afterValue) {
        this.afterValue = afterValue == null ? null : afterValue.trim();
    }

}