package com.logic.system.domain;

import org.springframework.security.oauth2.common.OAuth2AccessToken;
import org.springframework.security.oauth2.provider.OAuth2Authentication;

import java.io.Serializable;

public class OAuthAccessToken implements Serializable {
    private static final long serialVersionUID = -2554218714794204444L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OAUTH_ACCESS_TOKEN.AUTHENTICATION_ID
     *
     * @mbggenerated Tue Dec 15 17:27:53 CST 2015
     */
    private String authenticationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OAUTH_ACCESS_TOKEN.TOKEN_ID
     *
     * @mbggenerated Tue Dec 15 17:27:53 CST 2015
     */
    private String tokenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OAUTH_ACCESS_TOKEN.USER_NAME
     *
     * @mbggenerated Tue Dec 15 17:27:53 CST 2015
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OAUTH_ACCESS_TOKEN.CLIENT_ID
     *
     * @mbggenerated Tue Dec 15 17:27:53 CST 2015
     */
    private String clientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OAUTH_ACCESS_TOKEN.REFRESH_TOKEN
     *
     * @mbggenerated Tue Dec 15 17:27:53 CST 2015
     */
    private String refreshToken;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OAUTH_ACCESS_TOKEN.AUTHENTICATION_ID
     *
     * @return the value of OAUTH_ACCESS_TOKEN.AUTHENTICATION_ID
     *
     * @mbggenerated Tue Dec 15 17:27:53 CST 2015
     */

    /**
     * Added by Omer
     */
    private byte[] authentication;

    /**
     * Added by Omer
     */
    private byte[] token;



    public String getAuthenticationId() {
        return authenticationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OAUTH_ACCESS_TOKEN.AUTHENTICATION_ID
     *
     * @param authenticationId the value for OAUTH_ACCESS_TOKEN.AUTHENTICATION_ID
     *
     * @mbggenerated Tue Dec 15 17:27:53 CST 2015
     */
    public void setAuthenticationId(String authenticationId) {
        this.authenticationId = authenticationId == null ? null : authenticationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OAUTH_ACCESS_TOKEN.TOKEN_ID
     *
     * @return the value of OAUTH_ACCESS_TOKEN.TOKEN_ID
     *
     * @mbggenerated Tue Dec 15 17:27:53 CST 2015
     */
    public String getTokenId() {
        return tokenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OAUTH_ACCESS_TOKEN.TOKEN_ID
     *
     * @param tokenId the value for OAUTH_ACCESS_TOKEN.TOKEN_ID
     *
     * @mbggenerated Tue Dec 15 17:27:53 CST 2015
     */
    public void setTokenId(String tokenId) {
        this.tokenId = tokenId == null ? null : tokenId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OAUTH_ACCESS_TOKEN.USER_NAME
     *
     * @return the value of OAUTH_ACCESS_TOKEN.USER_NAME
     *
     * @mbggenerated Tue Dec 15 17:27:53 CST 2015
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OAUTH_ACCESS_TOKEN.USER_NAME
     *
     * @param userName the value for OAUTH_ACCESS_TOKEN.USER_NAME
     *
     * @mbggenerated Tue Dec 15 17:27:53 CST 2015
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OAUTH_ACCESS_TOKEN.CLIENT_ID
     *
     * @return the value of OAUTH_ACCESS_TOKEN.CLIENT_ID
     *
     * @mbggenerated Tue Dec 15 17:27:53 CST 2015
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OAUTH_ACCESS_TOKEN.CLIENT_ID
     *
     * @param clientId the value for OAUTH_ACCESS_TOKEN.CLIENT_ID
     *
     * @mbggenerated Tue Dec 15 17:27:53 CST 2015
     */
    public void setClientId(String clientId) {
        this.clientId = clientId == null ? null : clientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OAUTH_ACCESS_TOKEN.REFRESH_TOKEN
     *
     * @return the value of OAUTH_ACCESS_TOKEN.REFRESH_TOKEN
     *
     * @mbggenerated Tue Dec 15 17:27:53 CST 2015
     */
    public String getRefreshToken() {
        return refreshToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OAUTH_ACCESS_TOKEN.REFRESH_TOKEN
     *
     * @param refreshToken the value for OAUTH_ACCESS_TOKEN.REFRESH_TOKEN
     *
     * @mbggenerated Tue Dec 15 17:27:53 CST 2015
     */
    public void setRefreshToken(String refreshToken) {
        this.refreshToken = refreshToken == null ? null : refreshToken.trim();
    }



    public byte[] getAuthentication() {
        return authentication;
    }

    public void setAuthentication(byte[] authentication) {
        this.authentication = authentication;
    }

    public byte[] getToken() {
        return token;
    }

    public void setToken(byte[] token) {
        this.token = token;
    }
}