package com.logic.system.domain;

import org.springframework.security.oauth2.common.OAuth2RefreshToken;
import org.springframework.security.oauth2.provider.OAuth2Authentication;

import java.io.Serializable;

public class OAuthRefreshToken implements Serializable{
    private static final long serialVersionUID = -2554218714794205555L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OAUTH_REFRESH_TOKEN.TOKEN_ID
     *
     * @mbggenerated Tue Dec 15 17:27:53 CST 2015
     */
    private String tokenId;

    /**
     * Added by Omer
     */
    private byte[] token;

    /**
     * Added by Omer
     */
    private byte[] authentication;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OAUTH_REFRESH_TOKEN.TOKEN_ID
     *
     * @return the value of OAUTH_REFRESH_TOKEN.TOKEN_ID
     *
     * @mbggenerated Tue Dec 15 17:27:53 CST 2015
     */
    public String getTokenId() {
        return tokenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OAUTH_REFRESH_TOKEN.TOKEN_ID
     *
     * @param tokenId the value for OAUTH_REFRESH_TOKEN.TOKEN_ID
     *
     * @mbggenerated Tue Dec 15 17:27:53 CST 2015
     */
    public void setTokenId(String tokenId) {
        this.tokenId = tokenId == null ? null : tokenId.trim();
    }

    public byte[] getToken() {
        return token;
    }

    public void setToken(byte[] token) {
        this.token = token;
    }

    public byte[] getAuthentication() {
        return authentication;
    }

    public void setAuthentication(byte[] authentication) {
        this.authentication = authentication;
    }
}