package com.logic.system.domain;


import com.logic.common.domain.BasePojo;
import com.logic.common.domain.BasePojoOracle;

import java.util.Date;

public class PDCorrectiveActionMaster extends BasePojo{


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_CORRECTIVE_ACTION_MASTER.SUBJECT
     *
     * @mbggenerated Fri Jan 15 16:37:47 CST 2016
     */
    private String subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_CORRECTIVE_ACTION_MASTER.DAYS_FOR_CORRECT
     *
     * @mbggenerated Fri Jan 15 16:37:47 CST 2016
     */
    private Integer daysForCorrect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_CORRECTIVE_ACTION_MASTER.DATE_FOR_CORRECTED
     *
     * @mbggenerated Fri Jan 15 16:37:47 CST 2016
     */
    private Date dateForCorrected;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_CORRECTIVE_ACTION_MASTER.COMMENTS
     *
     * @mbggenerated Fri Jan 15 16:37:47 CST 2016
     */
    private String comments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_CORRECTIVE_ACTION_MASTER.ATTACHMENTS
     *
     * @mbggenerated Fri Jan 15 16:37:47 CST 2016
     */
    private String attachments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_CORRECTIVE_ACTION_MASTER.TASK_ID
     *
     * @mbggenerated Fri Jan 15 16:37:47 CST 2016
     */
    private Integer taskId;

    private Integer formId;
  
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_CORRECTIVE_ACTION_MASTER.SUBJECT
     *
     * @return the value of PD_CORRECTIVE_ACTION_MASTER.SUBJECT
     *
     * @mbggenerated Fri Jan 15 16:37:47 CST 2016
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_CORRECTIVE_ACTION_MASTER.SUBJECT
     *
     * @param subject the value for PD_CORRECTIVE_ACTION_MASTER.SUBJECT
     *
     * @mbggenerated Fri Jan 15 16:37:47 CST 2016
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_CORRECTIVE_ACTION_MASTER.DAYS_FOR_CORRECT
     *
     * @return the value of PD_CORRECTIVE_ACTION_MASTER.DAYS_FOR_CORRECT
     *
     * @mbggenerated Fri Jan 15 16:37:47 CST 2016
     */
    public Integer getDaysForCorrect() {
        return daysForCorrect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_CORRECTIVE_ACTION_MASTER.DAYS_FOR_CORRECT
     *
     * @param daysForCorrect the value for PD_CORRECTIVE_ACTION_MASTER.DAYS_FOR_CORRECT
     *
     * @mbggenerated Fri Jan 15 16:37:47 CST 2016
     */
    public void setDaysForCorrect(Integer daysForCorrect) {
        this.daysForCorrect = daysForCorrect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_CORRECTIVE_ACTION_MASTER.DATE_FOR_CORRECTED
     *
     * @return the value of PD_CORRECTIVE_ACTION_MASTER.DATE_FOR_CORRECTED
     *
     * @mbggenerated Fri Jan 15 16:37:47 CST 2016
     */
    public Date getDateForCorrected() {
        return dateForCorrected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_CORRECTIVE_ACTION_MASTER.DATE_FOR_CORRECTED
     *
     * @param dateForCorrected the value for PD_CORRECTIVE_ACTION_MASTER.DATE_FOR_CORRECTED
     *
     * @mbggenerated Fri Jan 15 16:37:47 CST 2016
     */
    public void setDateForCorrected(Date dateForCorrected) {
        this.dateForCorrected = dateForCorrected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_CORRECTIVE_ACTION_MASTER.COMMENTS
     *
     * @return the value of PD_CORRECTIVE_ACTION_MASTER.COMMENTS
     *
     * @mbggenerated Fri Jan 15 16:37:47 CST 2016
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_CORRECTIVE_ACTION_MASTER.COMMENTS
     *
     * @param comments the value for PD_CORRECTIVE_ACTION_MASTER.COMMENTS
     *
     * @mbggenerated Fri Jan 15 16:37:47 CST 2016
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_CORRECTIVE_ACTION_MASTER.ATTACHMENTS
     *
     * @return the value of PD_CORRECTIVE_ACTION_MASTER.ATTACHMENTS
     *
     * @mbggenerated Fri Jan 15 16:37:47 CST 2016
     */
    public String getAttachments() {
        return attachments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_CORRECTIVE_ACTION_MASTER.ATTACHMENTS
     *
     * @param attachments the value for PD_CORRECTIVE_ACTION_MASTER.ATTACHMENTS
     *
     * @mbggenerated Fri Jan 15 16:37:47 CST 2016
     */
    public void setAttachments(String attachments) {
        this.attachments = attachments == null ? null : attachments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_CORRECTIVE_ACTION_MASTER.TASK_ID
     *
     * @return the value of PD_CORRECTIVE_ACTION_MASTER.TASK_ID
     *
     * @mbggenerated Fri Jan 15 16:37:47 CST 2016
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_CORRECTIVE_ACTION_MASTER.TASK_ID
     *
     * @param taskId the value for PD_CORRECTIVE_ACTION_MASTER.TASK_ID
     *
     * @mbggenerated Fri Jan 15 16:37:47 CST 2016
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    public Integer getFormId() {
        return formId;
    }

    public void setFormId(Integer formId) {
        this.formId = formId;
    }
}