package com.logic.system.domain;

import com.logic.common.domain.BasePojo;
import com.logic.common.domain.BasePojoOracle;

public class PDCorrectiveActionDetail extends BasePojo {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_CORRECTIVE_ACTION_DETAIL.MASTER_ID
     *
     * @mbggenerated Fri Jan 15 16:37:47 CST 2016
     */
    private Integer masterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_CORRECTIVE_ACTION_DETAIL.FORM_RESPONSE_DETAIL_ID
     *
     * @mbggenerated Fri Jan 15 16:37:47 CST 2016
     */
    private Integer formResponseDetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_CORRECTIVE_ACTION_DETAIL.ERROR_CAUSE
     *
     * @mbggenerated Fri Jan 15 16:37:47 CST 2016
     */
    private String errorCause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_CORRECTIVE_ACTION_DETAIL.OTHER_CAUSE
     *
     * @mbggenerated Fri Jan 15 16:37:47 CST 2016
     */
    private String otherCause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_CORRECTIVE_ACTION_DETAIL.CORRECTIVE_ACTION
     *
     * @mbggenerated Fri Jan 15 16:37:47 CST 2016
     */
    private String correctiveAction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_CORRECTIVE_ACTION_DETAIL.OTHER_CORRECTIVE_ACTION
     *
     * @mbggenerated Fri Jan 15 16:37:47 CST 2016
     */
    private String otherCorrectiveAction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_CORRECTIVE_ACTION_DETAIL.RESP_PARTY
     *
     * @mbggenerated Fri Jan 15 16:37:47 CST 2016
     */
    private String respParty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_CORRECTIVE_ACTION_DETAIL.COMMENTS
     *
     * @mbggenerated Fri Jan 15 16:37:47 CST 2016
     */
    private String comments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_CORRECTIVE_ACTION_DETAIL.OTHER_1
     *
     * @mbggenerated Fri Jan 15 16:37:47 CST 2016
     */
    private String other1;

    /**
  

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_CORRECTIVE_ACTION_DETAIL.MASTER_ID
     *
     * @return the value of PD_CORRECTIVE_ACTION_DETAIL.MASTER_ID
     *
     * @mbggenerated Fri Jan 15 16:37:47 CST 2016
     */
    public Integer getMasterId() {
        return masterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_CORRECTIVE_ACTION_DETAIL.MASTER_ID
     *
     * @param masterId the value for PD_CORRECTIVE_ACTION_DETAIL.MASTER_ID
     *
     * @mbggenerated Fri Jan 15 16:37:47 CST 2016
     */
    public void setMasterId(Integer masterId) {
        this.masterId = masterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_CORRECTIVE_ACTION_DETAIL.FORM_RESPONSE_DETAIL_ID
     *
     * @return the value of PD_CORRECTIVE_ACTION_DETAIL.FORM_RESPONSE_DETAIL_ID
     *
     * @mbggenerated Fri Jan 15 16:37:47 CST 2016
     */
    public Integer getFormResponseDetailId() {
        return formResponseDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_CORRECTIVE_ACTION_DETAIL.FORM_RESPONSE_DETAIL_ID
     *
     * @param formResponseDetailId the value for PD_CORRECTIVE_ACTION_DETAIL.FORM_RESPONSE_DETAIL_ID
     *
     * @mbggenerated Fri Jan 15 16:37:47 CST 2016
     */
    public void setFormResponseDetailId(Integer formResponseDetailId) {
        this.formResponseDetailId = formResponseDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_CORRECTIVE_ACTION_DETAIL.ERROR_CAUSE
     *
     * @return the value of PD_CORRECTIVE_ACTION_DETAIL.ERROR_CAUSE
     *
     * @mbggenerated Fri Jan 15 16:37:47 CST 2016
     */
    public String getErrorCause() {
        return errorCause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_CORRECTIVE_ACTION_DETAIL.ERROR_CAUSE
     *
     * @param errorCause the value for PD_CORRECTIVE_ACTION_DETAIL.ERROR_CAUSE
     *
     * @mbggenerated Fri Jan 15 16:37:47 CST 2016
     */
    public void setErrorCause(String errorCause) {
        this.errorCause = errorCause == null ? null : errorCause.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_CORRECTIVE_ACTION_DETAIL.OTHER_CAUSE
     *
     * @return the value of PD_CORRECTIVE_ACTION_DETAIL.OTHER_CAUSE
     *
     * @mbggenerated Fri Jan 15 16:37:47 CST 2016
     */
    public String getOtherCause() {
        return otherCause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_CORRECTIVE_ACTION_DETAIL.OTHER_CAUSE
     *
     * @param otherCause the value for PD_CORRECTIVE_ACTION_DETAIL.OTHER_CAUSE
     *
     * @mbggenerated Fri Jan 15 16:37:47 CST 2016
     */
    public void setOtherCause(String otherCause) {
        this.otherCause = otherCause == null ? null : otherCause.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_CORRECTIVE_ACTION_DETAIL.CORRECTIVE_ACTION
     *
     * @return the value of PD_CORRECTIVE_ACTION_DETAIL.CORRECTIVE_ACTION
     *
     * @mbggenerated Fri Jan 15 16:37:47 CST 2016
     */
    public String getCorrectiveAction() {
        return correctiveAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_CORRECTIVE_ACTION_DETAIL.CORRECTIVE_ACTION
     *
     * @param correctiveAction the value for PD_CORRECTIVE_ACTION_DETAIL.CORRECTIVE_ACTION
     *
     * @mbggenerated Fri Jan 15 16:37:47 CST 2016
     */
    public void setCorrectiveAction(String correctiveAction) {
        this.correctiveAction = correctiveAction == null ? null : correctiveAction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_CORRECTIVE_ACTION_DETAIL.OTHER_CORRECTIVE_ACTION
     *
     * @return the value of PD_CORRECTIVE_ACTION_DETAIL.OTHER_CORRECTIVE_ACTION
     *
     * @mbggenerated Fri Jan 15 16:37:47 CST 2016
     */
    public String getOtherCorrectiveAction() {
        return otherCorrectiveAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_CORRECTIVE_ACTION_DETAIL.OTHER_CORRECTIVE_ACTION
     *
     * @param otherCorrectiveAction the value for PD_CORRECTIVE_ACTION_DETAIL.OTHER_CORRECTIVE_ACTION
     *
     * @mbggenerated Fri Jan 15 16:37:47 CST 2016
     */
    public void setOtherCorrectiveAction(String otherCorrectiveAction) {
        this.otherCorrectiveAction = otherCorrectiveAction == null ? null : otherCorrectiveAction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_CORRECTIVE_ACTION_DETAIL.RESP_PARTY
     *
     * @return the value of PD_CORRECTIVE_ACTION_DETAIL.RESP_PARTY
     *
     * @mbggenerated Fri Jan 15 16:37:47 CST 2016
     */
    public String getRespParty() {
        return respParty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_CORRECTIVE_ACTION_DETAIL.RESP_PARTY
     *
     * @param respParty the value for PD_CORRECTIVE_ACTION_DETAIL.RESP_PARTY
     *
     * @mbggenerated Fri Jan 15 16:37:47 CST 2016
     */
    public void setRespParty(String respParty) {
        this.respParty = respParty == null ? null : respParty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_CORRECTIVE_ACTION_DETAIL.COMMENTS
     *
     * @return the value of PD_CORRECTIVE_ACTION_DETAIL.COMMENTS
     *
     * @mbggenerated Fri Jan 15 16:37:47 CST 2016
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_CORRECTIVE_ACTION_DETAIL.COMMENTS
     *
     * @param comments the value for PD_CORRECTIVE_ACTION_DETAIL.COMMENTS
     *
     * @mbggenerated Fri Jan 15 16:37:47 CST 2016
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_CORRECTIVE_ACTION_DETAIL.OTHER_1
     *
     * @return the value of PD_CORRECTIVE_ACTION_DETAIL.OTHER_1
     *
     * @mbggenerated Fri Jan 15 16:37:47 CST 2016
     */
    public String getOther1() {
        return other1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_CORRECTIVE_ACTION_DETAIL.OTHER_1
     *
     * @param other1 the value for PD_CORRECTIVE_ACTION_DETAIL.OTHER_1
     *
     * @mbggenerated Fri Jan 15 16:37:47 CST 2016
     */
    public void setOther1(String other1) {
        this.other1 = other1 == null ? null : other1.trim();
    }

}