package com.logic.system.domain;

import com.logic.common.domain.BasePojoOracle;

import java.math.BigDecimal;
import java.util.Date;

public class PDRequestMiddleCheck extends BasePojoOracle {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_MIDDLE_CHECK.MACHINE_NO
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private Integer machineSeqid;

    private String projectManager;

    private String selfCheckResult;

    private String companyEmployeeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_MIDDLE_CHECK.INSTALL_DIRECTOR
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private String installDirector;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_MIDDLE_CHECK.HALF_INSTALL_DIRECTOR_PHONE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private String halfInstallDirectorPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_MIDDLE_CHECK.APPLY_STATUS
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private String applyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_MIDDLE_CHECK.CHECK_PHASES
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private String checkPhases;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_MIDDLE_CHECK.APPLY_DATE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private Date applyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_MIDDLE_CHECK.INSTALL_START_REAL_DATE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private Date installStartRealDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_MIDDLE_CHECK.SCHEDULE_DATE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private Date scheduleDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_MIDDLE_CHECK.INSTALL_LOGS
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private String installLogs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_MIDDLE_CHECK.NOTES
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private String notes;

    private String rMidQualityPersonId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_MIDDLE_CHECK.R_MID_QUALITY_PERSON
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private String rMidQualityPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_MIDDLE_CHECK.R_MID_QUALITY_SCORE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private BigDecimal rMidQualityScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_MIDDLE_CHECK.R_MID_END_DATE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private Date rMidEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_MIDDLE_CHECK.R_MID_ACCEPTANCE_DATE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private Date rMidAcceptanceDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_MIDDLE_CHECK.R_MID_CHECK_RESULT
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private BigDecimal rMidCheckResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_MIDDLE_CHECK.R_MID_RECTIFICATION_DAYS
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private BigDecimal rMidRectificationDays;

    private String rMidRecheckInspectorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_MIDDLE_CHECK.R_MID_RECHECK_INSPECTOR
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private String rMidRecheckInspector;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_MIDDLE_CHECK.R_MID_RECHECK_DATE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private Date rMidRecheckDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_MIDDLE_CHECK.R_MID_RECHECK_SCORE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private BigDecimal rMidRecheckScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_MIDDLE_CHECK.R_MID_RECHECK_RESULT
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private BigDecimal rMidRecheckResult;

    private BigDecimal writeBackStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_MIDDLE_CHECK.MACHINE_NO
     *
     * @return the value of PD_REQUEST_MIDDLE_CHECK.MACHINE_NO
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public Integer getMachineSeqid() {
        return machineSeqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_MIDDLE_CHECK.MACHINE_NO
     *
     * @param machineSeqid the value for PD_REQUEST_MIDDLE_CHECK.MACHINE_NO
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setMachineSeqid(Integer machineSeqid) {
        this.machineSeqid = machineSeqid == null ? null : machineSeqid;
    }

    public String getProjectManager() {
        return projectManager;
    }

    public void setProjectManager(String projectManager) {
        this.projectManager = projectManager;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_MIDDLE_CHECK.INSTALL_DIRECTOR
     *
     * @return the value of PD_REQUEST_MIDDLE_CHECK.INSTALL_DIRECTOR
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public String getInstallDirector() {
        return installDirector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_MIDDLE_CHECK.INSTALL_DIRECTOR
     *
     * @param installDirector the value for PD_REQUEST_MIDDLE_CHECK.INSTALL_DIRECTOR
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setInstallDirector(String installDirector) {
        this.installDirector = installDirector == null ? null : installDirector.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_MIDDLE_CHECK.HALF_INSTALL_DIRECTOR_PHONE
     *
     * @return the value of PD_REQUEST_MIDDLE_CHECK.HALF_INSTALL_DIRECTOR_PHONE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public String getHalfInstallDirectorPhone() {
        return halfInstallDirectorPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_MIDDLE_CHECK.HALF_INSTALL_DIRECTOR_PHONE
     *
     * @param halfInstallDirectorPhone the value for PD_REQUEST_MIDDLE_CHECK.HALF_INSTALL_DIRECTOR_PHONE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setHalfInstallDirectorPhone(String halfInstallDirectorPhone) {
        this.halfInstallDirectorPhone = halfInstallDirectorPhone == null ? null : halfInstallDirectorPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_MIDDLE_CHECK.APPLY_STATUS
     *
     * @return the value of PD_REQUEST_MIDDLE_CHECK.APPLY_STATUS
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public String getApplyType() {
        return applyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_MIDDLE_CHECK.APPLY_STATUS
     *
     * @param applyType the value for PD_REQUEST_MIDDLE_CHECK.APPLY_STATUS
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setApplyType(String applyType) {
        this.applyType = applyType == null ? null : applyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_MIDDLE_CHECK.CHECK_PHASES
     *
     * @return the value of PD_REQUEST_MIDDLE_CHECK.CHECK_PHASES
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public String getCheckPhases() {
        return checkPhases;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_MIDDLE_CHECK.CHECK_PHASES
     *
     * @param checkPhases the value for PD_REQUEST_MIDDLE_CHECK.CHECK_PHASES
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setCheckPhases(String checkPhases) {
        this.checkPhases = checkPhases == null ? null : checkPhases.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_MIDDLE_CHECK.APPLY_DATE
     *
     * @return the value of PD_REQUEST_MIDDLE_CHECK.APPLY_DATE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public Date getApplyDate() {
        return applyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_MIDDLE_CHECK.APPLY_DATE
     *
     * @param applyDate the value for PD_REQUEST_MIDDLE_CHECK.APPLY_DATE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setApplyDate(Date applyDate) {
        this.applyDate = applyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_MIDDLE_CHECK.INSTALL_START_REAL_DATE
     *
     * @return the value of PD_REQUEST_MIDDLE_CHECK.INSTALL_START_REAL_DATE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public Date getInstallStartRealDate() {
        return installStartRealDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_MIDDLE_CHECK.INSTALL_START_REAL_DATE
     *
     * @param installStartRealDate the value for PD_REQUEST_MIDDLE_CHECK.INSTALL_START_REAL_DATE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setInstallStartRealDate(Date installStartRealDate) {
        this.installStartRealDate = installStartRealDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_MIDDLE_CHECK.SCHEDULE_DATE
     *
     * @return the value of PD_REQUEST_MIDDLE_CHECK.SCHEDULE_DATE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public Date getScheduleDate() {
        return scheduleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_MIDDLE_CHECK.SCHEDULE_DATE
     *
     * @param scheduleDate the value for PD_REQUEST_MIDDLE_CHECK.SCHEDULE_DATE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setScheduleDate(Date scheduleDate) {
        this.scheduleDate = scheduleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_MIDDLE_CHECK.INSTALL_LOGS
     *
     * @return the value of PD_REQUEST_MIDDLE_CHECK.INSTALL_LOGS
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public String getInstallLogs() {
        return installLogs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_MIDDLE_CHECK.INSTALL_LOGS
     *
     * @param installLogs the value for PD_REQUEST_MIDDLE_CHECK.INSTALL_LOGS
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setInstallLogs(String installLogs) {
        this.installLogs = installLogs == null ? null : installLogs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_MIDDLE_CHECK.NOTES
     *
     * @return the value of PD_REQUEST_MIDDLE_CHECK.NOTES
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_MIDDLE_CHECK.NOTES
     *
     * @param notes the value for PD_REQUEST_MIDDLE_CHECK.NOTES
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setNotes(String notes) {
        this.notes = notes == null ? null : notes.trim();
    }

    public String getrMidQualityPersonId() {
        return rMidQualityPersonId;
    }

    public void setrMidQualityPersonId(String rMidQualityPersonId) {
        this.rMidQualityPersonId = rMidQualityPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_MIDDLE_CHECK.R_MID_QUALITY_PERSON
     *
     * @return the value of PD_REQUEST_MIDDLE_CHECK.R_MID_QUALITY_PERSON
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public String getrMidQualityPerson() {
        return rMidQualityPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_MIDDLE_CHECK.R_MID_QUALITY_PERSON
     *
     * @param rMidQualityPerson the value for PD_REQUEST_MIDDLE_CHECK.R_MID_QUALITY_PERSON
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setrMidQualityPerson(String rMidQualityPerson) {
        this.rMidQualityPerson = rMidQualityPerson == null ? null : rMidQualityPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_MIDDLE_CHECK.R_MID_QUALITY_SCORE
     *
     * @return the value of PD_REQUEST_MIDDLE_CHECK.R_MID_QUALITY_SCORE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public BigDecimal getrMidQualityScore() {
        return rMidQualityScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_MIDDLE_CHECK.R_MID_QUALITY_SCORE
     *
     * @param rMidQualityScore the value for PD_REQUEST_MIDDLE_CHECK.R_MID_QUALITY_SCORE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setrMidQualityScore(BigDecimal rMidQualityScore) {
        this.rMidQualityScore = rMidQualityScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_MIDDLE_CHECK.R_MID_END_DATE
     *
     * @return the value of PD_REQUEST_MIDDLE_CHECK.R_MID_END_DATE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public Date getrMidEndDate() {
        return rMidEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_MIDDLE_CHECK.R_MID_END_DATE
     *
     * @param rMidEndDate the value for PD_REQUEST_MIDDLE_CHECK.R_MID_END_DATE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setrMidEndDate(Date rMidEndDate) {
        this.rMidEndDate = rMidEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_MIDDLE_CHECK.R_MID_ACCEPTANCE_DATE
     *
     * @return the value of PD_REQUEST_MIDDLE_CHECK.R_MID_ACCEPTANCE_DATE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public Date getrMidAcceptanceDate() {
        return rMidAcceptanceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_MIDDLE_CHECK.R_MID_ACCEPTANCE_DATE
     *
     * @param rMidAcceptanceDate the value for PD_REQUEST_MIDDLE_CHECK.R_MID_ACCEPTANCE_DATE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setrMidAcceptanceDate(Date rMidAcceptanceDate) {
        this.rMidAcceptanceDate = rMidAcceptanceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_MIDDLE_CHECK.R_MID_CHECK_RESULT
     *
     * @return the value of PD_REQUEST_MIDDLE_CHECK.R_MID_CHECK_RESULT
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public BigDecimal getrMidCheckResult() {
        return rMidCheckResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_MIDDLE_CHECK.R_MID_CHECK_RESULT
     *
     * @param rMidCheckResult the value for PD_REQUEST_MIDDLE_CHECK.R_MID_CHECK_RESULT
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setrMidCheckResult(BigDecimal rMidCheckResult) {
        this.rMidCheckResult = rMidCheckResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_MIDDLE_CHECK.R_MID_RECTIFICATION_DAYS
     *
     * @return the value of PD_REQUEST_MIDDLE_CHECK.R_MID_RECTIFICATION_DAYS
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public BigDecimal getrMidRectificationDays() {
        return rMidRectificationDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_MIDDLE_CHECK.R_MID_RECTIFICATION_DAYS
     *
     * @param rMidRectificationDays the value for PD_REQUEST_MIDDLE_CHECK.R_MID_RECTIFICATION_DAYS
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setrMidRectificationDays(BigDecimal rMidRectificationDays) {
        this.rMidRectificationDays = rMidRectificationDays;
    }

    public String getrMidRecheckInspectorId() {
        return rMidRecheckInspectorId;
    }

    public void setrMidRecheckInspectorId(String rMidRecheckInspectorId) {
        this.rMidRecheckInspectorId = rMidRecheckInspectorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_MIDDLE_CHECK.R_MID_RECHECK_INSPECTOR
     *
     * @return the value of PD_REQUEST_MIDDLE_CHECK.R_MID_RECHECK_INSPECTOR
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public String getrMidRecheckInspector() {
        return rMidRecheckInspector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_MIDDLE_CHECK.R_MID_RECHECK_INSPECTOR
     *
     * @param rMidRecheckInspector the value for PD_REQUEST_MIDDLE_CHECK.R_MID_RECHECK_INSPECTOR
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setrMidRecheckInspector(String rMidRecheckInspector) {
        this.rMidRecheckInspector = rMidRecheckInspector == null ? null : rMidRecheckInspector.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_MIDDLE_CHECK.R_MID_RECHECK_DATE
     *
     * @return the value of PD_REQUEST_MIDDLE_CHECK.R_MID_RECHECK_DATE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public Date getrMidRecheckDate() {
        return rMidRecheckDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_MIDDLE_CHECK.R_MID_RECHECK_DATE
     *
     * @param rMidRecheckDate the value for PD_REQUEST_MIDDLE_CHECK.R_MID_RECHECK_DATE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setrMidRecheckDate(Date rMidRecheckDate) {
        this.rMidRecheckDate = rMidRecheckDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_MIDDLE_CHECK.R_MID_RECHECK_SCORE
     *
     * @return the value of PD_REQUEST_MIDDLE_CHECK.R_MID_RECHECK_SCORE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public BigDecimal getrMidRecheckScore() {
        return rMidRecheckScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_MIDDLE_CHECK.R_MID_RECHECK_SCORE
     *
     * @param rMidRecheckScore the value for PD_REQUEST_MIDDLE_CHECK.R_MID_RECHECK_SCORE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setrMidRecheckScore(BigDecimal rMidRecheckScore) {
        this.rMidRecheckScore = rMidRecheckScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_MIDDLE_CHECK.R_MID_RECHECK_RESULT
     *
     * @return the value of PD_REQUEST_MIDDLE_CHECK.R_MID_RECHECK_RESULT
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public BigDecimal getrMidRecheckResult() {
        return rMidRecheckResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_MIDDLE_CHECK.R_MID_RECHECK_RESULT
     *
     * @param rMidRecheckResult the value for PD_REQUEST_MIDDLE_CHECK.R_MID_RECHECK_RESULT
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setrMidRecheckResult(BigDecimal rMidRecheckResult) {
        this.rMidRecheckResult = rMidRecheckResult;
    }

    public BigDecimal getWriteBackStatus() {
        return writeBackStatus;
    }

    public void setWriteBackStatus(BigDecimal writeBackStatus) {
        this.writeBackStatus = writeBackStatus;
    }

    public String getSelfCheckResult() {
        return selfCheckResult;
    }

    public void setSelfCheckResult(String selfCheckResult) {
        this.selfCheckResult = selfCheckResult;
    }

    public String getCompanyEmployeeId() {
        return companyEmployeeId;
    }

    public void setCompanyEmployeeId(String companyEmployeeId) {
        this.companyEmployeeId = companyEmployeeId;
    }
}