package com.logic.system.domain;

import com.logic.common.domain.BasePojo;
import com.logic.common.domain.BasePojoOracle;

import java.math.BigDecimal;
import java.util.Date;

public class PDRequestDiag extends BasePojo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_DIAG.MACHINE_NO
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private Integer machineSeqid;

    private String projectManager;

    private String w109;
    private String w272;
    private String w610s;
    private String w610e;
    private Date applyDate;
    private String companyEmployeeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_DIAG.DIAG_SIDE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private String diagSide;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_DIAG.DIAG_VENDOR_ID
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private String diagVendorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_DIAG.WOF_CD_106
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private String w106;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_DIAG.WOF_CD_108
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private String w108;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_DIAG.WOF_CD_255
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private String w255;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_DIAG.WOF_CD_252
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private String w252;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_DIAG.WOF_CD_A153
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private String wA153;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_DIAG.WOF_CD_256
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private String w256;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_DIAG.WOF_CD_257
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private String w257;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_DIAG.WOF_CD_429
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private String w429;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_DIAG.WOF_CD_271
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private String w271;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_DIAG.WOF_CD_259
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private String w259;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_DIAG.WOF_CD_258
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private String w258;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_DIAG.WOF_CD_508
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private String w508;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_DIAG.WOF_CD_531
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private String w531;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_DIAG.DIAG_APPLY_STATUS
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private String applyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_DIAG.R_DIAG_ACT_START_DATE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private Date rDiagActStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_DIAG.R_DIAG_ACT_END_DATE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private Date rDiagActEndDate;

    private BigDecimal writeBackStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_DIAG.MACHINE_NO
     *
     * @return the value of PD_REQUEST_DIAG.MACHINE_NO
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public Integer getMachineSeqid() {
        return machineSeqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_DIAG.MACHINE_NO
     *
     * @param machineSeqid the value for PD_REQUEST_DIAG.MACHINE_NO
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setMachineSeqid(Integer machineSeqid) {
        this.machineSeqid = machineSeqid == null ? null : machineSeqid;
    }

    public String getProjectManager() {
        return projectManager;
    }

    public void setProjectManager(String projectManager) {
        this.projectManager = projectManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_DIAG.DIAG_SIDE
     *
     * @return the value of PD_REQUEST_DIAG.DIAG_SIDE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public String getDiagSide() {
        return diagSide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_DIAG.DIAG_SIDE
     *
     * @param diagSide the value for PD_REQUEST_DIAG.DIAG_SIDE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setDiagSide(String diagSide) {
        this.diagSide = diagSide == null ? null : diagSide.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_DIAG.DIAG_VENDOR_ID
     *
     * @return the value of PD_REQUEST_DIAG.DIAG_VENDOR_ID
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public String getDiagVendorId() {
        return diagVendorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_DIAG.DIAG_VENDOR_ID
     *
     * @param diagVendorId the value for PD_REQUEST_DIAG.DIAG_VENDOR_ID
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setDiagVendorId(String diagVendorId) {
        this.diagVendorId = diagVendorId == null ? null : diagVendorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_DIAG.WOF_CD_106
     *
     * @return the value of PD_REQUEST_DIAG.WOF_CD_106
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public String getW106() {
        return w106;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_DIAG.WOF_CD_106
     *
     * @param w106 the value for PD_REQUEST_DIAG.WOF_CD_106
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setW106(String w106) {
        this.w106 = w106 == null ? null : w106.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_DIAG.WOF_CD_108
     *
     * @return the value of PD_REQUEST_DIAG.WOF_CD_108
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public String getW108() {
        return w108;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_DIAG.WOF_CD_108
     *
     * @param w108 the value for PD_REQUEST_DIAG.WOF_CD_108
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setW108(String w108) {
        this.w108 = w108 == null ? null : w108.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_DIAG.WOF_CD_255
     *
     * @return the value of PD_REQUEST_DIAG.WOF_CD_255
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public String getW255() {
        return w255;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_DIAG.WOF_CD_255
     *
     * @param w255 the value for PD_REQUEST_DIAG.WOF_CD_255
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setW255(String w255) {
        this.w255 = w255 == null ? null : w255.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_DIAG.WOF_CD_252
     *
     * @return the value of PD_REQUEST_DIAG.WOF_CD_252
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public String getW252() {
        return w252;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_DIAG.WOF_CD_252
     *
     * @param w252 the value for PD_REQUEST_DIAG.WOF_CD_252
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setW252(String w252) {
        this.w252 = w252 == null ? null : w252.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_DIAG.WOF_CD_A153
     *
     * @return the value of PD_REQUEST_DIAG.WOF_CD_A153
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public String getWA153() {
        return wA153;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_DIAG.WOF_CD_A153
     *
     * @param wA153 the value for PD_REQUEST_DIAG.WOF_CD_A153
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setWA153(String wA153) {
        this.wA153 = wA153 == null ? null : wA153.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_DIAG.WOF_CD_256
     *
     * @return the value of PD_REQUEST_DIAG.WOF_CD_256
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public String getW256() {
        return w256;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_DIAG.WOF_CD_256
     *
     * @param w256 the value for PD_REQUEST_DIAG.WOF_CD_256
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setW256(String w256) {
        this.w256 = w256 == null ? null : w256.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_DIAG.WOF_CD_257
     *
     * @return the value of PD_REQUEST_DIAG.WOF_CD_257
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public String getW257() {
        return w257;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_DIAG.WOF_CD_257
     *
     * @param w257 the value for PD_REQUEST_DIAG.WOF_CD_257
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setW257(String w257) {
        this.w257 = w257 == null ? null : w257.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_DIAG.WOF_CD_429
     *
     * @return the value of PD_REQUEST_DIAG.WOF_CD_429
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public String getW429() {
        return w429;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_DIAG.WOF_CD_429
     *
     * @param w429 the value for PD_REQUEST_DIAG.WOF_CD_429
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setW429(String w429) {
        this.w429 = w429 == null ? null : w429.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_DIAG.WOF_CD_271
     *
     * @return the value of PD_REQUEST_DIAG.WOF_CD_271
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public String getW271() {
        return w271;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_DIAG.WOF_CD_271
     *
     * @param w271 the value for PD_REQUEST_DIAG.WOF_CD_271
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setW271(String w271) {
        this.w271 = w271 == null ? null : w271.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_DIAG.WOF_CD_259
     *
     * @return the value of PD_REQUEST_DIAG.WOF_CD_259
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public String getW259() {
        return w259;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_DIAG.WOF_CD_259
     *
     * @param w259 the value for PD_REQUEST_DIAG.WOF_CD_259
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setW259(String w259) {
        this.w259 = w259 == null ? null : w259.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_DIAG.WOF_CD_258
     *
     * @return the value of PD_REQUEST_DIAG.WOF_CD_258
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public String getW258() {
        return w258;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_DIAG.WOF_CD_258
     *
     * @param w258 the value for PD_REQUEST_DIAG.WOF_CD_258
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setW258(String w258) {
        this.w258 = w258 == null ? null : w258.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_DIAG.WOF_CD_508
     *
     * @return the value of PD_REQUEST_DIAG.WOF_CD_508
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public String getW508() {
        return w508;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_DIAG.WOF_CD_508
     *
     * @param w508 the value for PD_REQUEST_DIAG.WOF_CD_508
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setW508(String w508) {
        this.w508 = w508 == null ? null : w508.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_DIAG.WOF_CD_531
     *
     * @return the value of PD_REQUEST_DIAG.WOF_CD_531
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public String getW531() {
        return w531;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_DIAG.WOF_CD_531
     *
     * @param w531 the value for PD_REQUEST_DIAG.WOF_CD_531
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setW531(String w531) {
        this.w531 = w531 == null ? null : w531.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_DIAG.DIAG_APPLY_STATUS
     *
     * @return the value of PD_REQUEST_DIAG.DIAG_APPLY_STATUS
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public String getApplyType() {
        return applyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_DIAG.DIAG_APPLY_STATUS
     *
     * @param applyType the value for PD_REQUEST_DIAG.DIAG_APPLY_STATUS
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setApplyType(String applyType) {
        this.applyType = applyType == null ? null : applyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_DIAG.R_DIAG_ACT_START_DATE
     *
     * @return the value of PD_REQUEST_DIAG.R_DIAG_ACT_START_DATE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public Date getrDiagActStartDate() {
        return rDiagActStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_DIAG.R_DIAG_ACT_START_DATE
     *
     * @param rDiagActStartDate the value for PD_REQUEST_DIAG.R_DIAG_ACT_START_DATE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setrDiagActStartDate(Date rDiagActStartDate) {
        this.rDiagActStartDate = rDiagActStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_DIAG.R_DIAG_ACT_END_DATE
     *
     * @return the value of PD_REQUEST_DIAG.R_DIAG_ACT_END_DATE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public Date getrDiagActEndDate() {
        return rDiagActEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_DIAG.R_DIAG_ACT_END_DATE
     *
     * @param rDiagActEndDate the value for PD_REQUEST_DIAG.R_DIAG_ACT_END_DATE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setrDiagActEndDate(Date rDiagActEndDate) {
        this.rDiagActEndDate = rDiagActEndDate;
    }

    public BigDecimal getWriteBackStatus() {
        return writeBackStatus;
    }

    public void setWriteBackStatus(BigDecimal writeBackStatus) {
        this.writeBackStatus = writeBackStatus;
    }

    public String getW109() {
        return w109;
    }

    public void setW109(String w109) {
        this.w109 = w109;
    }

    public String getW272() {
        return w272;
    }

    public void setW272(String w272) {
        this.w272 = w272;
    }

    public String getW610s() {
        return w610s;
    }

    public void setW610s(String w610s) {
        this.w610s = w610s;
    }

    public String getW610e() {
        return w610e;
    }

    public void setW610e(String w610e) {
        this.w610e = w610e;
    }

    public Date getApplyDate() {
        return applyDate;
    }

    public void setApplyDate(Date applyDate) {
        this.applyDate = applyDate;
    }

    public String getCompanyEmployeeId() {
        return companyEmployeeId;
    }

    public void setCompanyEmployeeId(String companyEmployeeId) {
        this.companyEmployeeId = companyEmployeeId;
    }
}