package com.logic.system.domain;

import com.logic.common.domain.BasePojoOracle;

import java.math.BigDecimal;
import java.util.Date;

public class PDRequestOverallCheck extends BasePojoOracle {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_OVERALL_CHECK.MACHINE_NO
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private Integer machineSeqid;

    private String projectManager;

    private Integer  rIsBeforeAuthority;
    private Integer  rHasBuiltRecords;

    private Date rectificationEndDate;
    private Date sndRectificationEndDate;
    private String companyEmployeeId;
    private String rectificationFiles;
    private Double rCheckScore;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_OVERALL_CHECK.INSTALL_DIRECTOR
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private String installDirector;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_OVERALL_CHECK.INSTALL_DIRECTOR_PHONE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private String installDirectorPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_OVERALL_CHECK.APPLY_STATUS
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private String applyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_OVERALL_CHECK.OVERALL_APPLY_DATE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private Date overallApplyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_OVERALL_CHECK.OVERALL_CHECK_DATE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private Date overallCheckDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_OVERALL_CHECK.DIAG_END_DATE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private Date diagEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_OVERALL_CHECK.INSTALL_LOGS
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private String installLogs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_OVERALL_CHECK.NOTES
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private String notes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_OVERALL_CHECK.DIAG_REPORT
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private String diagReport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_OVERALL_CHECK.R_CHECK_DATE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private Date rCheckDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_OVERALL_CHECK.R_CHECK_START_DATE_REAL
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private Date rCheckStartDateReal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_OVERALL_CHECK.R_CHECK_END_DATE_REAL
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private Date rCheckEndDateReal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_OVERALL_CHECK.R_CHECK_START_DATE_SCHEDULE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private Date rCheckStartDateSchedule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_OVERALL_CHECK.R_CHECK_END_DATE_SCHEDULE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private Date rCheckEndDateSchedule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_OVERALL_CHECK.R_QUALITY_PERSON_ID
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private String rQualityPersonId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_OVERALL_CHECK.R_QUALITY_PERSON
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private String rQualityPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_OVERALL_CHECK.R_CHECK_RESULT
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private BigDecimal rCheckResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_OVERALL_CHECK.R_ACCEPTANCE_DATE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private Date rAcceptanceDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_OVERALL_CHECK.R_RECHECK_INSPECTOR_ID
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private String rRecheckInspectorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_OVERALL_CHECK.R_RECHECK_DATE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private Date rRecheckDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_OVERALL_CHECK.R_RECHECK_RESULT
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private BigDecimal rRecheckResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_OVERALL_CHECK.R_SND_RECTIFICATION_DAYS
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private BigDecimal rSndRectificationDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_OVERALL_CHECK.R_SND_RECTIFICATION_END_DATE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_OVERALL_CHECK.R_TRD_CHECK_INSPECTOR_ID
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private String rTrdCheckInspectorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_OVERALL_CHECK.R_TRD_CHECK_INSPECTOR
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private String rTrdCheckInspector;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_OVERALL_CHECK.R_TRD_CHECK_DATE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private Date rTrdCheckDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PD_REQUEST_OVERALL_CHECK.R_TRD_CHECK_RESULT
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    private BigDecimal rTrdCheckResult;

    private BigDecimal writeBackStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_OVERALL_CHECK.MACHINE_NO
     *
     * @return the value of PD_REQUEST_OVERALL_CHECK.MACHINE_NO
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public Integer getMachineSeqid() {
        return machineSeqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_OVERALL_CHECK.MACHINE_NO
     *
     * @param machineSeqid the value for PD_REQUEST_OVERALL_CHECK.MACHINE_NO
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setMachineSeqid(Integer machineSeqid) {
        this.machineSeqid = machineSeqid == null ? null : machineSeqid;
    }

    public String getProjectManager() {
        return projectManager;
    }

    public void setProjectManager(String projectManager) {
        this.projectManager = projectManager;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_OVERALL_CHECK.INSTALL_DIRECTOR
     *
     * @return the value of PD_REQUEST_OVERALL_CHECK.INSTALL_DIRECTOR
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public String getInstallDirector() {
        return installDirector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_OVERALL_CHECK.INSTALL_DIRECTOR
     *
     * @param installDirector the value for PD_REQUEST_OVERALL_CHECK.INSTALL_DIRECTOR
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setInstallDirector(String installDirector) {
        this.installDirector = installDirector == null ? null : installDirector.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_OVERALL_CHECK.INSTALL_DIRECTOR_PHONE
     *
     * @return the value of PD_REQUEST_OVERALL_CHECK.INSTALL_DIRECTOR_PHONE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public String getInstallDirectorPhone() {
        return installDirectorPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_OVERALL_CHECK.INSTALL_DIRECTOR_PHONE
     *
     * @param installDirectorPhone the value for PD_REQUEST_OVERALL_CHECK.INSTALL_DIRECTOR_PHONE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setInstallDirectorPhone(String installDirectorPhone) {
        this.installDirectorPhone = installDirectorPhone == null ? null : installDirectorPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_OVERALL_CHECK.APPLY_STATUS
     *
     * @return the value of PD_REQUEST_OVERALL_CHECK.APPLY_STATUS
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public String getApplyType() {
        return applyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_OVERALL_CHECK.APPLY_STATUS
     *
     * @param applyType the value for PD_REQUEST_OVERALL_CHECK.APPLY_STATUS
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setApplyType(String applyType) {
        this.applyType = applyType == null ? null : applyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_OVERALL_CHECK.OVERALL_APPLY_DATE
     *
     * @return the value of PD_REQUEST_OVERALL_CHECK.OVERALL_APPLY_DATE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public Date getOverallApplyDate() {
        return overallApplyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_OVERALL_CHECK.OVERALL_APPLY_DATE
     *
     * @param overallApplyDate the value for PD_REQUEST_OVERALL_CHECK.OVERALL_APPLY_DATE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setOverallApplyDate(Date overallApplyDate) {
        this.overallApplyDate = overallApplyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_OVERALL_CHECK.OVERALL_CHECK_DATE
     *
     * @return the value of PD_REQUEST_OVERALL_CHECK.OVERALL_CHECK_DATE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public Date getOverallCheckDate() {
        return overallCheckDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_OVERALL_CHECK.OVERALL_CHECK_DATE
     *
     * @param overallCheckDate the value for PD_REQUEST_OVERALL_CHECK.OVERALL_CHECK_DATE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setOverallCheckDate(Date overallCheckDate) {
        this.overallCheckDate = overallCheckDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_OVERALL_CHECK.DIAG_END_DATE
     *
     * @return the value of PD_REQUEST_OVERALL_CHECK.DIAG_END_DATE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public Date getDiagEndDate() {
        return diagEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_OVERALL_CHECK.DIAG_END_DATE
     *
     * @param diagEndDate the value for PD_REQUEST_OVERALL_CHECK.DIAG_END_DATE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setDiagEndDate(Date diagEndDate) {
        this.diagEndDate = diagEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_OVERALL_CHECK.INSTALL_LOGS
     *
     * @return the value of PD_REQUEST_OVERALL_CHECK.INSTALL_LOGS
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public String getInstallLogs() {
        return installLogs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_OVERALL_CHECK.INSTALL_LOGS
     *
     * @param installLogs the value for PD_REQUEST_OVERALL_CHECK.INSTALL_LOGS
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setInstallLogs(String installLogs) {
        this.installLogs = installLogs == null ? null : installLogs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_OVERALL_CHECK.NOTES
     *
     * @return the value of PD_REQUEST_OVERALL_CHECK.NOTES
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_OVERALL_CHECK.NOTES
     *
     * @param notes the value for PD_REQUEST_OVERALL_CHECK.NOTES
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setNotes(String notes) {
        this.notes = notes == null ? null : notes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_OVERALL_CHECK.DIAG_REPORT
     *
     * @return the value of PD_REQUEST_OVERALL_CHECK.DIAG_REPORT
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public String getDiagReport() {
        return diagReport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_OVERALL_CHECK.DIAG_REPORT
     *
     * @param diagReport the value for PD_REQUEST_OVERALL_CHECK.DIAG_REPORT
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setDiagReport(String diagReport) {
        this.diagReport = diagReport == null ? null : diagReport.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_OVERALL_CHECK.R_CHECK_DATE
     *
     * @return the value of PD_REQUEST_OVERALL_CHECK.R_CHECK_DATE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public Date getrCheckDate() {
        return rCheckDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_OVERALL_CHECK.R_CHECK_DATE
     *
     * @param rCheckDate the value for PD_REQUEST_OVERALL_CHECK.R_CHECK_DATE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setrCheckDate(Date rCheckDate) {
        this.rCheckDate = rCheckDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_OVERALL_CHECK.R_CHECK_START_DATE_REAL
     *
     * @return the value of PD_REQUEST_OVERALL_CHECK.R_CHECK_START_DATE_REAL
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public Date getrCheckStartDateReal() {
        return rCheckStartDateReal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_OVERALL_CHECK.R_CHECK_START_DATE_REAL
     *
     * @param rCheckStartDateReal the value for PD_REQUEST_OVERALL_CHECK.R_CHECK_START_DATE_REAL
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setrCheckStartDateReal(Date rCheckStartDateReal) {
        this.rCheckStartDateReal = rCheckStartDateReal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_OVERALL_CHECK.R_CHECK_END_DATE_REAL
     *
     * @return the value of PD_REQUEST_OVERALL_CHECK.R_CHECK_END_DATE_REAL
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public Date getrCheckEndDateReal() {
        return rCheckEndDateReal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_OVERALL_CHECK.R_CHECK_END_DATE_REAL
     *
     * @param rCheckEndDateReal the value for PD_REQUEST_OVERALL_CHECK.R_CHECK_END_DATE_REAL
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setrCheckEndDateReal(Date rCheckEndDateReal) {
        this.rCheckEndDateReal = rCheckEndDateReal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_OVERALL_CHECK.R_CHECK_START_DATE_SCHEDULE
     *
     * @return the value of PD_REQUEST_OVERALL_CHECK.R_CHECK_START_DATE_SCHEDULE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public Date getrCheckStartDateSchedule() {
        return rCheckStartDateSchedule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_OVERALL_CHECK.R_CHECK_START_DATE_SCHEDULE
     *
     * @param rCheckStartDateSchedule the value for PD_REQUEST_OVERALL_CHECK.R_CHECK_START_DATE_SCHEDULE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setrCheckStartDateSchedule(Date rCheckStartDateSchedule) {
        this.rCheckStartDateSchedule = rCheckStartDateSchedule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_OVERALL_CHECK.R_CHECK_END_DATE_SCHEDULE
     *
     * @return the value of PD_REQUEST_OVERALL_CHECK.R_CHECK_END_DATE_SCHEDULE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public Date getrCheckEndDateSchedule() {
        return rCheckEndDateSchedule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_OVERALL_CHECK.R_CHECK_END_DATE_SCHEDULE
     *
     * @param rCheckEndDateSchedule the value for PD_REQUEST_OVERALL_CHECK.R_CHECK_END_DATE_SCHEDULE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setrCheckEndDateSchedule(Date rCheckEndDateSchedule) {
        this.rCheckEndDateSchedule = rCheckEndDateSchedule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_OVERALL_CHECK.R_QUALITY_PERSON_ID
     *
     * @return the value of PD_REQUEST_OVERALL_CHECK.R_QUALITY_PERSON_ID
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public String getrQualityPersonId() {
        return rQualityPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_OVERALL_CHECK.R_QUALITY_PERSON_ID
     *
     * @param rQualityPersonId the value for PD_REQUEST_OVERALL_CHECK.R_QUALITY_PERSON_ID
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setrQualityPersonId(String rQualityPersonId) {
        this.rQualityPersonId = rQualityPersonId == null ? null : rQualityPersonId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_OVERALL_CHECK.R_QUALITY_PERSON
     *
     * @return the value of PD_REQUEST_OVERALL_CHECK.R_QUALITY_PERSON
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public String getrQualityPerson() {
        return rQualityPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_OVERALL_CHECK.R_QUALITY_PERSON
     *
     * @param rQualityPerson the value for PD_REQUEST_OVERALL_CHECK.R_QUALITY_PERSON
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setrQualityPerson(String rQualityPerson) {
        this.rQualityPerson = rQualityPerson == null ? null : rQualityPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_OVERALL_CHECK.R_CHECK_RESULT
     *
     * @return the value of PD_REQUEST_OVERALL_CHECK.R_CHECK_RESULT
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public BigDecimal getrCheckResult() {
        return rCheckResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_OVERALL_CHECK.R_CHECK_RESULT
     *
     * @param rCheckResult the value for PD_REQUEST_OVERALL_CHECK.R_CHECK_RESULT
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setrCheckResult(BigDecimal rCheckResult) {
        this.rCheckResult = rCheckResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_OVERALL_CHECK.R_ACCEPTANCE_DATE
     *
     * @return the value of PD_REQUEST_OVERALL_CHECK.R_ACCEPTANCE_DATE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public Date getrAcceptanceDate() {
        return rAcceptanceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_OVERALL_CHECK.R_ACCEPTANCE_DATE
     *
     * @param rAcceptanceDate the value for PD_REQUEST_OVERALL_CHECK.R_ACCEPTANCE_DATE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setrAcceptanceDate(Date rAcceptanceDate) {
        this.rAcceptanceDate = rAcceptanceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_OVERALL_CHECK.R_RECHECK_INSPECTOR_ID
     *
     * @return the value of PD_REQUEST_OVERALL_CHECK.R_RECHECK_INSPECTOR_ID
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public String getrRecheckInspectorId() {
        return rRecheckInspectorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_OVERALL_CHECK.R_RECHECK_INSPECTOR_ID
     *
     * @param rRecheckInspectorId the value for PD_REQUEST_OVERALL_CHECK.R_RECHECK_INSPECTOR_ID
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setrRecheckInspectorId(String rRecheckInspectorId) {
        this.rRecheckInspectorId = rRecheckInspectorId == null ? null : rRecheckInspectorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_OVERALL_CHECK.R_RECHECK_DATE
     *
     * @return the value of PD_REQUEST_OVERALL_CHECK.R_RECHECK_DATE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public Date getrRecheckDate() {
        return rRecheckDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_OVERALL_CHECK.R_RECHECK_DATE
     *
     * @param rRecheckDate the value for PD_REQUEST_OVERALL_CHECK.R_RECHECK_DATE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setrRecheckDate(Date rRecheckDate) {
        this.rRecheckDate = rRecheckDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_OVERALL_CHECK.R_RECHECK_RESULT
     *
     * @return the value of PD_REQUEST_OVERALL_CHECK.R_RECHECK_RESULT
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public BigDecimal getrRecheckResult() {
        return rRecheckResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_OVERALL_CHECK.R_RECHECK_RESULT
     *
     * @param rRecheckResult the value for PD_REQUEST_OVERALL_CHECK.R_RECHECK_RESULT
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setrRecheckResult(BigDecimal rRecheckResult) {
        this.rRecheckResult = rRecheckResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_OVERALL_CHECK.R_SND_RECTIFICATION_DAYS
     *
     * @return the value of PD_REQUEST_OVERALL_CHECK.R_SND_RECTIFICATION_DAYS
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public BigDecimal getrSndRectificationDays() {
        return rSndRectificationDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_OVERALL_CHECK.R_SND_RECTIFICATION_DAYS
     *
     * @param rSndRectificationDays the value for PD_REQUEST_OVERALL_CHECK.R_SND_RECTIFICATION_DAYS
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setrSndRectificationDays(BigDecimal rSndRectificationDays) {
        this.rSndRectificationDays = rSndRectificationDays;
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_OVERALL_CHECK.R_TRD_CHECK_INSPECTOR_ID
     *
     * @return the value of PD_REQUEST_OVERALL_CHECK.R_TRD_CHECK_INSPECTOR_ID
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public String getrTrdCheckInspectorId() {
        return rTrdCheckInspectorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_OVERALL_CHECK.R_TRD_CHECK_INSPECTOR_ID
     *
     * @param rTrdCheckInspectorId the value for PD_REQUEST_OVERALL_CHECK.R_TRD_CHECK_INSPECTOR_ID
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setrTrdCheckInspectorId(String rTrdCheckInspectorId) {
        this.rTrdCheckInspectorId = rTrdCheckInspectorId == null ? null : rTrdCheckInspectorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_OVERALL_CHECK.R_TRD_CHECK_INSPECTOR
     *
     * @return the value of PD_REQUEST_OVERALL_CHECK.R_TRD_CHECK_INSPECTOR
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public String getrTrdCheckInspector() {
        return rTrdCheckInspector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_OVERALL_CHECK.R_TRD_CHECK_INSPECTOR
     *
     * @param rTrdCheckInspector the value for PD_REQUEST_OVERALL_CHECK.R_TRD_CHECK_INSPECTOR
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setrTrdCheckInspector(String rTrdCheckInspector) {
        this.rTrdCheckInspector = rTrdCheckInspector == null ? null : rTrdCheckInspector.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_OVERALL_CHECK.R_TRD_CHECK_DATE
     *
     * @return the value of PD_REQUEST_OVERALL_CHECK.R_TRD_CHECK_DATE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public Date getrTrdCheckDate() {
        return rTrdCheckDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_OVERALL_CHECK.R_TRD_CHECK_DATE
     *
     * @param rTrdCheckDate the value for PD_REQUEST_OVERALL_CHECK.R_TRD_CHECK_DATE
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setrTrdCheckDate(Date rTrdCheckDate) {
        this.rTrdCheckDate = rTrdCheckDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PD_REQUEST_OVERALL_CHECK.R_TRD_CHECK_RESULT
     *
     * @return the value of PD_REQUEST_OVERALL_CHECK.R_TRD_CHECK_RESULT
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public BigDecimal getrTrdCheckResult() {
        return rTrdCheckResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PD_REQUEST_OVERALL_CHECK.R_TRD_CHECK_RESULT
     *
     * @param rTrdCheckResult the value for PD_REQUEST_OVERALL_CHECK.R_TRD_CHECK_RESULT
     *
     * @mbggenerated Fri Dec 11 16:59:17 CST 2015
     */
    public void setrTrdCheckResult(BigDecimal rTrdCheckResult) {
        this.rTrdCheckResult = rTrdCheckResult;
    }

    public BigDecimal getWriteBackStatus() {
        return writeBackStatus;
    }

    public void setWriteBackStatus(BigDecimal writeBackStatus) {
        this.writeBackStatus = writeBackStatus;
    }

    public Integer getrIsBeforeAuthority() {
        return rIsBeforeAuthority;
    }

    public void setrIsBeforeAuthority(Integer rIsBeforeAuthority) {
        this.rIsBeforeAuthority = rIsBeforeAuthority;
    }

    public Integer getrHasBuiltRecords() {
        return rHasBuiltRecords;
    }

    public void setrHasBuiltRecords(Integer rHasBuiltRecords) {
        this.rHasBuiltRecords = rHasBuiltRecords;
    }

    public Date getRectificationEndDate() {
        return rectificationEndDate;
    }

    public void setRectificationEndDate(Date rectificationEndDate) {
        this.rectificationEndDate = rectificationEndDate;
    }

    public Date getSndRectificationEndDate() {
        return sndRectificationEndDate;
    }

    public void setSndRectificationEndDate(Date sndRectificationEndDate) {
        this.sndRectificationEndDate = sndRectificationEndDate;
    }

    public String getCompanyEmployeeId() {
        return companyEmployeeId;
    }

    public void setCompanyEmployeeId(String companyEmployeeId) {
        this.companyEmployeeId = companyEmployeeId;
    }

    public String getRectificationFiles() {
        return rectificationFiles;
    }

    public void setRectificationFiles(String rectificationFiles) {
        this.rectificationFiles = rectificationFiles;
    }

    public Double getrCheckScore() {
        return rCheckScore;
    }

    public void setrCheckScore(Double rCheckScore) {
        this.rCheckScore = rCheckScore;
    }
}