package com.logic.system.domain;

import com.logic.common.domain.BasePojo;

public class TaskComment extends BasePojo{

	/**
	 * 
	 */
	private static final long serialVersionUID = -6759582128256453428L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_TASK_COMMENT.TASK_ID
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    private Integer taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_TASK_COMMENT.USER_ID
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_TASK_COMMENT.COMMENTS
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    private String comments;

    /**

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_TASK_COMMENT.TASK_ID
     *
     * @return the value of SYSTEM_TASK_COMMENT.TASK_ID
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_TASK_COMMENT.TASK_ID
     *
     * @param taskId the value for SYSTEM_TASK_COMMENT.TASK_ID
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_TASK_COMMENT.USER_ID
     *
     * @return the value of SYSTEM_TASK_COMMENT.USER_ID
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_TASK_COMMENT.USER_ID
     *
     * @param userId the value for SYSTEM_TASK_COMMENT.USER_ID
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_TASK_COMMENT.COMMENTS
     *
     * @return the value of SYSTEM_TASK_COMMENT.COMMENTS
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_TASK_COMMENT.COMMENTS
     *
     * @param comments the value for SYSTEM_TASK_COMMENT.COMMENTS
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }

}