package com.logic.system.domain;


import java.util.Date;

import com.logic.common.domain.BasePojo;

public class TaskPeople extends BasePojo {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8064775862831600968L;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_TASK_PEOPLE.TASK_ID
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    private Integer taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_TASK_PEOPLE.RESPONSIBILITY
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    private String responsibility;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_TASK_PEOPLE.USER_ID
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    private Integer userId;

    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_TASK_PEOPLE.TASK_ID
     *
     * @return the value of SYSTEM_TASK_PEOPLE.TASK_ID
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_TASK_PEOPLE.TASK_ID
     *
     * @param taskId the value for SYSTEM_TASK_PEOPLE.TASK_ID
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_TASK_PEOPLE.RESPONSIBILITY
     *
     * @return the value of SYSTEM_TASK_PEOPLE.RESPONSIBILITY
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    public String getResponsibility() {
        return responsibility;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_TASK_PEOPLE.RESPONSIBILITY
     *
     * @param responsibility the value for SYSTEM_TASK_PEOPLE.RESPONSIBILITY
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    public void setResponsibility(String responsibility) {
        this.responsibility = responsibility == null ? null : responsibility.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_TASK_PEOPLE.USER_ID
     *
     * @return the value of SYSTEM_TASK_PEOPLE.USER_ID
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_TASK_PEOPLE.USER_ID
     *
     * @param userId the value for SYSTEM_TASK_PEOPLE.USER_ID
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

}