package com.logic.system.domain;


import java.util.Date;

import com.logic.common.domain.BasePojo;

public class TaskDate extends BasePojo{
    /**
	 * 
	 */
	private static final long serialVersionUID = -3623946048139032930L;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_TASK_DATE.TASK_ID
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    private Integer taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_TASK_DATE.DATE_TYPE
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    private String dateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_TASK_DATE.DATE_VALUE
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    private Date dateValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_TASK_DATE.TASK_ID
     *
     * @return the value of SYSTEM_TASK_DATE.TASK_ID
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_TASK_DATE.TASK_ID
     *
     * @param taskId the value for SYSTEM_TASK_DATE.TASK_ID
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_TASK_DATE.DATE_TYPE
     *
     * @return the value of SYSTEM_TASK_DATE.DATE_TYPE
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    public String getDateType() {
        return dateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_TASK_DATE.DATE_TYPE
     *
     * @param dateType the value for SYSTEM_TASK_DATE.DATE_TYPE
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    public void setDateType(String dateType) {
        this.dateType = dateType == null ? null : dateType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_TASK_DATE.DATE_VALUE
     *
     * @return the value of SYSTEM_TASK_DATE.DATE_VALUE
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    public Date getDateValue() {
        return dateValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_TASK_DATE.DATE_VALUE
     *
     * @param dateValue the value for SYSTEM_TASK_DATE.DATE_VALUE
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    public void setDateValue(Date dateValue) {
        this.dateValue = dateValue;
    }

}