package com.logic.system.domain;

import java.util.Date;

import com.logic.common.domain.BasePojo;

public class Task extends BasePojo{

    /**
	 * 
	 */
	private static final long serialVersionUID = 2549049687480837237L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_TASK.SUBJECT
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    private String subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_TASK.TASK_TYPE
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    private String taskType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_TASK.TASK_REF_ID
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    private Integer taskRefId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_TASK.STATUS
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_TASK.RESOLUTION
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    private String resolution;

    private String taskPriority;

    private String taskAssignType;


  
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_TASK.SUBJECT
     *
     * @return the value of SYSTEM_TASK.SUBJECT
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_TASK.SUBJECT
     *
     * @param subject the value for SYSTEM_TASK.SUBJECT
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_TASK.TASK_TYPE
     *
     * @return the value of SYSTEM_TASK.TASK_TYPE
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    public String getTaskType() {
        return taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_TASK.TASK_TYPE
     *
     * @param taskType the value for SYSTEM_TASK.TASK_TYPE
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    public void setTaskType(String taskType) {
        this.taskType = taskType == null ? null : taskType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_TASK.TASK_REF_ID
     *
     * @return the value of SYSTEM_TASK.TASK_REF_ID
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    public Integer getTaskRefId() {
        return taskRefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_TASK.TASK_REF_ID
     *
     * @param taskRefId the value for SYSTEM_TASK.TASK_REF_ID
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    public void setTaskRefId(Integer taskRefId) {
        this.taskRefId = taskRefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_TASK.STATUS
     *
     * @return the value of SYSTEM_TASK.STATUS
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_TASK.STATUS
     *
     * @param status the value for SYSTEM_TASK.STATUS
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_TASK.RESOLUTION
     *
     * @return the value of SYSTEM_TASK.RESOLUTION
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    public String getResolution() {
        return resolution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_TASK.RESOLUTION
     *
     * @param resolution the value for SYSTEM_TASK.RESOLUTION
     *
     * @mbggenerated Fri Dec 18 13:43:17 CST 2015
     */
    public void setResolution(String resolution) {
        this.resolution = resolution == null ? null : resolution.trim();
    }

    public String getTaskPriority() {
        return taskPriority;
    }

    public void setTaskPriority(String taskPriority) {
        this.taskPriority = taskPriority;
    }

    public String getTaskAssignType() {
        return taskAssignType;
    }

    public void setTaskAssignType(String taskAssignType) {
        this.taskAssignType = taskAssignType;
    }
}